### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1111]
http://beta.lmfdb.org/roadmap

since this is one of the links right below introduction, it may receive some attention, specially by experts. Is the content of it up-to-date?

**Comment by JohnCremona** [comment]
I thought that in Bristol a month ago we agreed to remove that from the sidebar.  Perhaps it should be there but only on beta?

**Comment by jvoight** [comment]
I wasn't at Bristol, but my understanding (@davidfarmer can confirm) is that it is indeed updated, and furthermore it is important to have this remain publicly visible so that when experts say "well what about XYZ?" we can point them to this.  Closing for now, but if there is more discussion required, we can reopen it.
