### ISSUE TITLE
Broken L-function links

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1117]
From Brian:

" The links on the page

http://www.lmfdb.org/L/degree2/

to zeros related to holomorphic modular forms seem
to all be broken. For example

http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/1/12/0/a/0/"

**Comment by JohnCremona** [comment]
That URL should be 1/12/1/a/0

**Comment by JohnCremona** [comment]
7/3/3 is an empty space so I think that should be 7.3.6.a since 
http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/7/3/6/a/0/
is fine and has the right zero at 7.214.

The next one similarly could be http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/5/6/4/a/1 as that has a zero at 6.7163 

I guess the others are similar: wrong labels.

The file degree2browsetable.yaml needs updating and then whatever is done to create Degree2.html from that, or simply edit the html for speed.

I would recommend that *every* URL in Degree2.html is tested in a test.

I can try to correct that html file now.

**Comment by JohnCremona** [comment]
I am giving up on fixing this now since it started well but now even the Delta function has disappeared:
ModularForm/GL2/Q/holomorphic/1/12/1/a/
now gives the error
The orbit 1.12.1.a is not in the database!

**Comment by JohnCremona** [comment]
PR #1118 fixes this.
