### ISSUE TITLE
Avoiding ensure_index/create_index

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1169]
Hello,

The functions: ensure_index/create_index must be avoided in the flask app.
Perhaps the exception is when app saves a knowl.
The two main reasons are:
- this operations must be done in the primary instance
- and can lock writes and reads.

If we are running a client in the cloud, and warwick is the primary, the ensure_index knowles adds a 5/10s delay.

Also, since 3.0, ensureIndex()  == createIndex(), see https://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/.

From: https://docs.mongodb.org/manual/core/index-creation/
> By default, creating an index blocks all other operations on a database. When building an index on a collection, the database that holds the collection is unavailable for read or write operations until the index build completes. Any operation that requires a read or write lock on all databases (e.g. listDatabases) will wait for the foreground index build to 

For example, in these 3 examples the index should be done after a write, not before a read:
- [x] lmfdb/lmfdb/knowledge/knowl.py
- [x] lmfdb/knowledge/main.py 
- [x] lmfdb/lmfdb/users/main.py 

I'm not sure what do with this one:
- [x] lmfdb/raw.py

**Comment by JohnCremona** [comment]
Agreed.  one can only do it when authenticated to write to the db anyway,
which surely the web app is not?

John

**Comment by edgarcosta** [comment]
the lmfdb user can make enough damage if they desire:

```
db.system.roles.find();
{ "_id" : "admin.index_and_list_collections", "role" : "index_and_list_collections", "db" : "admin", "privileges" : [ { "resource" : { "db" : "", "collection" : "" }, "actions" : [ "createIndex", "listCollections" ] } ], "roles" : [ ] }


db.system.users.find();
...
{ "_id" : "admin.lmfdb", "user" : "lmfdb", "db" : "admin", "credentials" : { "MONGODB-CR" : "13e13d846619ccc9f49ce62b72736d2c" }, "roles" : [ { "role" : "index_and_list_collections", "db" : "admin" }, { "role" : "readAnyDatabase", "db" : "admin" } ] }
...
```


those two actions: "createIndex", "listCollections", they re always performed in the primary, and should be avoided at all costs.

I was going to open another issue regarding listCollections and listDatabases.

**Comment by jwj61** [comment]
Once an index has been created, inserting data should already update the index.  So, I would favor commenting them out.  The commands should be in import scripts for data.  For users and knowls, perhaps they should have a single import script which does only this.

**Comment by jvoight** [comment]
@haraldschilly: assigned to you, because you have worked with backend for knowls.

**Comment by edgarcosta** [comment]
I did as suggested, see #1175.
Could someone please double check that I didn't break knowls and/or users?

I'm not sure what to do with raw.

**Comment by jwj61** [comment]
Raw was created before my time.  I think it was essentially a preliminary/debugging tool.  If you just go to /raw, you _should_ get a list of databases (I think).  This is from memory since it is broken now (without any of today's pull requests).

/raw is one of the "secret urls" in the sense that nothing links to it, so I think it is ok to break it for now, and then we can revisit it at a workshop to decide if it should be fixed/preserved, or removed.

**Comment by edgarcosta** [comment]
Once it gets merged I will close both issues.

**Comment by jwbober** [comment]
I just noticed this comment.

The createIndex permissions are there because of some sillyness with gridfs
in some versions of pymongo. Like, any gridfs operations result in pymongo
calling ensureIndex(), or something like that. Maybe we can rely on newer
versions of pymongo now, and get rid of these permissions, but there were
some difficulties working around bugs in various versions of various
components a few months ago.

I thought we had removed any explicit ensure_index/create_index calls in
the website code in November. Maybe some came back in while I wasn't
watching.
