### ISSUE TITLE
never do from something import *

### ISSUE THREAD

**Issue by haraldschilly** [LMFDB/lmfdb#122]
```
…/lmfdb/characters/test_characters.py:15: SyntaxWarning: import * only allowed at module level
  def test_Heckemethods(self):
```

This is just one part, also on module level we should never just import *. That's a very good practice and allows for static code checking like `pyFlakes` to work better!

(if you do not have `pyFlakes`, install it and run it on your files …)

**Comment by edgarcosta** [comment]
@AndrewVSutherland what about making running your code through pyflakes a standard thing?

**Comment by AndrewVSutherland** [comment]
@edgarcosta Yes, this should be in the developers guide, and this is something I would ask reviewers to start checking on pull requests, as I have done.  pyflakes is very lightweight (do sudo apt get pyflakes to install) and in addition to catching unneeded imports, it finds a lot of bugs (I found several in the siegel modular forms and lfunctions code using it); usually these are caused by spelling errors in variable names, which without a tool like pyflakes are very difficult to catch in python code if they are hiding in a line of code your tests do not hit.

**Comment by edgarcosta** [comment]
no need for apt-get or sudo, pyflakes is a pip package `pip install --upgrade pyflakes`, suffices.

**Comment by JohnCremona** [comment]
!
$ pip install --upgrade pyflakes
The program 'pip' is currently not installed. You can install it by typing:
sudo apt-get install python-pip

I normally use the python and pip in Sage, i.e. "sage -pip ..." and did install pyflakes that way but then did not know how to use it.  So in fact using apt-get to install pyflakes was useful.  (This is on lehner.)
