### ISSUE TITLE
Create link button on knowl edit page should use new syntax

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#1286]
The "create external link" button on the knowl editing page should use this newer syntax:

{{ LINK_EXT('http://www.numbertheory.org/ntw/lecture_notes.html', 'http://www.numbertheory.org/ntw/lecture_notes.html') }}

**Comment by AndrewVSutherland** [comment]
@kedlaya Can you give some context for this issue?  It's not clear to me what the goal is -- the standard markup syntax [label](link) will still work even if we made this change.  If the goal is to make it easier for us to track or control external links, I'm not sure this accomplishes that, unless we also have the code scan for markup links and convert them (which would not be hard), but if we do that, then it's not clear why this change needs to be made (unless we want to disable markup links entirely and require the use of LINK_EXT).

@davidfarmer Do you have an opinion about this?

I'm asking because I'm triaging issues and don't know how to categorize this one (which is why it is marked as pending) -- is it something we know that we definitely want to do?  If so, is it something that should be done now (i.e. for Release 1.1).

**Comment by roed314** [comment]
Was this issue resolved at the knowls workshop?

**Comment by AndrewVSutherland** [comment]
I'm not sure whether it was resolved or not, but given that the issue has been open for 3 years without anyone clarifying the reasons for it and no one mentioned it during the workshop I am going to close it (anyone who objects should feel free to reopen it or create a new issue)
