### ISSUE TITLE
MongoDB needs to be fully reindexed

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1294]
On Monday night all our MongoDB servers crashed several times due to corrupt indexes.
I believe we fixed the issue temporarily, Drew and I did a bunch of random fetches to try to recreate the bug and we didn't manage to bring down the MongoDB servers.
To be safe, we should rebuild all the indexes, perhaps when things calm down.

Perhaps a more important question. How come the indexes got corrupt?
The two collections that were clearly corrupt were: numberfields.fields and hmfs.forms. 

Best,
Edgar

**Comment by jwj61** [comment]
I don't know if we are sure that they were corrupt.  As Drew pointed out, the internal representation of the index can become inefficient over time with items added and removed.  Over the years, there have been lots of modifications, including additions, to the number field database.  Or, did you run some integrity check?

**Comment by edgarcosta** [comment]
Am I sure it is corrupt? I don't know.
reindexing fixed the issue? yes.

Before reindexing those two collections: Trying to get a small number random objects from the database crashed the MongoDB server, in the sense that server really stopped running, and exited with an error.

After reindexing: I was able to fetch 100k random objects without an issue.

> As Drew pointed out, the internal representation of the index can become inefficient over time with items added and removed.
Are you talking about index 'ainvs'? the issue there is that we are indexing an array, and even though it should work, we weren't able to get any speed up by indexing that.

**Comment by jwj61** [comment]
> > As Drew pointed out, the internal representation of the index can become inefficient over time with items added and removed.
> 
> Are you talking about index 'ainvs'?

No, I was referring back to an early comment about why reindexing is good after many insertions/deletions, and that number fields was an extreme case where it had had millions of additions without reindexing.

I am only half-surprised that indexing an array did not help.  I know mongo essentially treats arrays differently.  On the plus side, it supports queries as to whether an item is in the array or not.  I think it was designed to do things like hold tags for blog entries.

**Comment by AndrewVSutherland** [comment]
Just to clarify, 3 separate issues were mentioned above:

(1) As Edgar mentioned there were two indexes definitely causing problems indicative of corruption (a sufficient number of random accesses would consistently force a crash) that went away once the indexes were rebuilt (after rebuild, we tested with 100x the number of accesses previously needed to force a crash and found no problems).  The concern is that there could be similar problems in other indices that have gone unnoticed because they are used much less frequently.  This is a good reason to rebuild them all.

(2) As John mentioned, rebuilding may improve performance, which is another reason to do it.

(3) As Edgar mentioned, indexes on fields that are arrays is not very efficiently supported in pymongo (internally it creates a multikey index, it does not simply concatenate array the array into a single value).  This means, for example, that querying ainvs stored as ['1','0','1','123','456'] is much slower than querying ainvs stored as '[1,0,1,123,456]'.  This has nothing to do with the issue of rebuilding indexes (and Edgar, I'm sure John Jones was not referring to this).

One other comment:  Edgar and I tested building a large index in the background (on a separate server), and it still slowed down the system to the point where the LMFDB is likely to fail (and it takes longer).  I think we should assume that indexes need to be rebuilt while the database is offline.  On the plus side, this is reasonably quick (only a few minutes per index, even for our largest collections).

BTW, mongodb has a reindex command that automatically reindexes all the indexes on a specified collection, you don't need to iterate through the indexes.  The fact that they provide such a command suggests that reindexing is indeed something one might want to do on a somewhat regular basis (e.g. when a collection has changed significantly)

**Comment by JohnCremona** [comment]
If I knew it was worth it I could easily change the type of the ainvs from
a list of 5 strings to a single string.  We are surely never going to want
to search on values of any particular a_i.

More generally, someone with technical knowledge might look through how we
store all data and make suggestions on changing format.  Harald used to do
that regularly but people rarely took any notice since they just want to
get things to work.

**Comment by AndrewVSutherland** [comment]
@JohnCremona For finding the minimal twist it doesn't matter, now that the j-invariant is included in the query, but for doing direct lookups on ainvs (e.g. when someone types them into the search box), it would make this much faster.  So probably worth doing.  

I'm sure your aware of this, but for the benefit of those who may not be, I'll note that in order to make a change like this safely and cleanly you need to proceed in 3 stages:

(1) add a new field that stores ainvs as a string (strip whitespace) and  update (or better recreate) all the records in the collection and change the code to look for the new field name (and parse the string if it is their) but fallback to the old field name if necessary (which it might be if the code is running on old data, e.g. due to a restore from backup).

(2) once the new code is up and running on both beta and prod, reload the data with the old ainvs field removed.

(3) once we are sure the code will never need to fall back to the old ainvs, remove the code that does this (this is not strictly necessary, but prevents code creep and possible confusion in the future)

The moral is that changing data formats is a pain, and anyone setting out to store new data in the LMFDB should really sit down and think hard about how the want to do this (and consult with someone more experienced with the issues if necessary).

**Comment by AndrewVSutherland** [comment]
Actually for changing ainvs you could do something simpler which is rather than introduc

**Comment by JohnCremona** [comment]
@AndrewVSutherland OK -- I do I know what to do and how!  I am currently about to insert several new data fields into every elliptic curve record to avoid computations on the fly and will follow a similar cautious strategy.

**Comment by edgarcosta** [comment]
An possible easy solution for this, is to do it whenever you decide to change from MMAPv1 to wiredtiger.
There are two options, using the replica set, or doing it with dumps and restores.
The first doesn't require any human effort, and I think I'm happy paying the 1TB of traffic for not dealing with the dump and restore.
I have already done it in the cloud. Feel free to read more about it here:
https://docs.mongodb.com/v3.0/release-notes/3.0-upgrade/#change-replica-set-storage-engine-to-wiredtiger

Sarunas compared the performance of both engines, wiredtiger performed much better:
https://github.com/edgarcosta/lmfdb-gce/blob/master/ab/results/benchmark_mmap-wt.png

**Comment by AndrewVSutherland** [comment]
@edgarcosta I like the no human effort approach.  How long does it take?  Could we do it this weekend?

**Comment by edgarcosta** [comment]
I would expect it to take around 8h + how much time it takes to transfer 1.3TB from the google cloud servers to warwick.
During this time no one will be able to connect to warwick, and I have the feeling that many people are still adding and editing data.

**Comment by AndrewVSutherland** [comment]
They are indeed, this may need to wait until next weekend.

**Comment by JohnCremona** [comment]
Also please can you give warning before adding terabytes to lmfdb.warwick?
The /data partition is 91% full though it shows 2.5T free.  We have more
physical disks (3 more @ 3.6T each)  we can bring on line but that requires
doing some btrfs balancing which takes a while (and last time we did that
problems were revealed which brought lmfdb.warwick down for 2 weeks).

**Comment by edgarcosta** [comment]
@JohnCremona I won't do anything before running it by everyone. I was just in the middle of the email that would address this.

**Comment by AndrewVSutherland** [comment]
@edgarcosta My understanding is that this has now been done on the cloud mongo db, it only remains to do this on lmfdb.warwick, but I don't see this as urgent.

**Comment by edgarcosta** [comment]
Yes, only warwick is missing.

**Comment by JohnCremona** [comment]
Can someone say exactly what it is which has not been done at Warwick which needs doing?  Is someone then volunteering to do what that is?

Warwick's data partition is 95% full.  I have 3 more disks which can be brought online but will not do that until we have a time when it will not matter if things go slow (or worse).

**Comment by AndrewVSutherland** [comment]
@JohnCremona The objective is to (at some point) get all the collections in the Warwick LMFDB reindexed.  Ideally this would be done by actually rebuilding all the databases, which we would do only **after** all unnecessary collections have been deleted (especially those in modularforms2), which would free up a lot of space (we gained about 400GB by doing this on ms.lmfdb.xyz).

For comparison here are the current sizes of the 5 larges databases on lmfdb.warwick compared to ms.lmfdb.xyz

|collection|warwick|cloud|
|---|---|---|
|Lfunctions | 260GB|122GB|
|elliptic_curves|26GB|2GB|
|genus2_curves|52GB|3.5GB|
|hmfs|176GB|20GB|
|modularforms2|518GB|69GB|
|numberfields|62GB|3.5GB|

In addition to the databases above, the database "local" uses over 50GB for no obvious reason that I can currently see -- I suspect we would get most of this back.

The thing to keep in mind is that mongo db never frees up space, and this works on a per database basis, so every time a particular database hits a new high water mark, mongo db expands the amount of disk space it is using and will never voluntarily give it back (for example, you might wonder why on earth the genus2_curves collection is so big on lmfdb.warwick -- this has to do with Lfunction data that was once stored there but is now stored in lfunctions (and with much less precision so it take less space than it used to in any case)).

I think @edgarcosta's preferred mechanism for achieving this is to simply delete the current mongo db on lmfdb.warwick entirely, create a new mongo db using our preferred storage engine (zlib?) and then make it part of the replica set and let it recover from all the data from the replicas in the cloud.  This approach would have the advantage of not requiring any additional space, and when it finished there should be a lot more available free space.

While this process is underway, the mongo db on lmfdb.warwick would be unavailable (we could redirect the lmfdb server to use the mongo db on one of the replicas to keep beta.lmfdb.org up if we felt that was necessary).

But the key first step is to wrap up (and close) #1431, i.e. trim the mongo db on lmfdb.warwick down to just the collections that need to be there (of course we will have backups we can always fall back to if needed).  I think this is mostly done, except for the modularforms2 database, where we are still waiting for @sehlen and @fredstro to clean things up.

**Comment by AndrewVSutherland** [comment]
One quick follow-up -- the space in the local database is almost all taken up by the collection oplog.rs which is using about 50GB, see https://docs.mongodb.com/manual/reference/local-database/#collections-on-replica-set-members for details.

**Comment by JohnCremona** [comment]
Thanks a lot for the excellent and detailed explanation.  I had no idea there was so much wasted space!

**Comment by edgarcosta** [comment]
1- local is all for the oplog, and we shouldn't try to get that back :)
2- 

> The thing to keep in mind is that mongo db never frees up space, and this works on a per database basis, so every time a particular database hits a new high water mark, mongo db expands the amount of disk space it is using and will never voluntarily give it back (for example, you might wonder why on earth the genus2_curves collection is so big on lmfdb.warwick -- this has to do with Lfunction data that was once stored there but is now stored in lfunctions (and with much less precision so it take less space than it used to in any case)).

As far as I understand, this only happens with mmapv1, as from my experience with wiredTiger I never observed this behaviour.

> I think @edgarcosta's preferred mechanism for achieving this is to simply delete the current mongo db on lmfdb.warwick entirely, create a new mongo db using our preferred storage engine (zlib?) and then make it part of the replica set and let it recover from all the data from the replicas in the cloud. 

Yes that is accurate. I would switch the engine to wiredTiger with zlib.
The DB in the cloud that replicates warwick only 658GB, while warwick uses 1.2+ TB.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Thanks for the clarification -- the wiredTiger behavior is a pleasant suprise (I just noticed this too).

Regarding 1, my only question was whether we really needed 50GB (which I believe is the maximum), you can set it as low as 1GB.  But I suppose it is safer to keep it at 50GB just in case one of the replicas gets behind for some reason (although with our current write concern setting this seems very unlikely).

**Comment by edgarcosta** [comment]
Yes, it is very unlikely, but possible.
I would leave it at 50GB. I don't see what we gain by saving 49GB on the grand scheme of things.

**Comment by AndrewVSutherland** [comment]
Agreed.

On June 11, 2016 2:58:48 PM EDT, edgarcosta <notifications@github.com> wrote:
>Yes, it is very unlikely, but possible.
>I would leave it at 50GB. I don't see what we gain by saving 49GB on
>the grand scheme of things.
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LMFDB/lmfdb/issues/1294#issuecomment-225386416

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edgarcosta** [comment]
This must happen some day.
with or without changing the storage engine.

**Comment by AndrewVSutherland** [comment]
I think we know enough to say that we should leave Warwick on Mmap for the moment (the WiredTiger performance issues we saw in the cloud can be managed in a controlled environment, but Warwick is much less controlled).  The only reason to delay rebuilding the database at Warwick is to get people to delete collections that do not need to be there; see http://beta.lmfdb.org/api/stats for a list of collections that are larger than 1 gigibabyte.  Of the 19 collections listed, only 8 exist on www.lmfdb.org (the 7 listed at http://www.lmfdb.org/api/stats/ plus elliptic_curves/padic_db which takes up less than 1GB on the cloud).

The following 11 collections do not exist in the cloud and are not documented in https://github.com/LMFDB/lmfdb-inventory/blob/master/README.md.

- modularforms2/ap.chunks (295GB)
- modularforms2/vector_on_basis.chunks (136GB)
- modularforms2/Newform_factors.chunks (17GB)
- numberfields	/old3 (11GB)
- numberfields/oldfields2 (10GB)
- numberfields/oldfields (9GB)
- modularforms2/Modular_symbols.chunks (7GB)
- numberfields	/newfields (6GB)
- elliptic_curves/old_curves (6GB)
- numberfields	/new1 (6GB)
- modularforms2/WebNewforms.chunks (1GB)

Perhaps @jwj61 and @JohnCremona can help clean up the extra collections in numberfields and elliptic_curves (note: there is an issue #1697 with numberfields/fields, which may mean we want to revert to one of the old* collections in numberfields).

Regading the large unused collections in modularforms2, I think we should just remove them unless @fredstro or @sehlen want to chime in and explain why they need to be there.  If it turns out they are needed, we can always restore them from backup.

By my estimation, we could save over a half a terabyte of diskspace (more in fact, because the numbers above do not include file overhead) by deleting the 11 collections above.  Then it would make sense to do a dump/restore on the whole database.

**Comment by edgarcosta** [comment]
sounds good to me

**Comment by JohnCremona** [comment]
On 12 July 2016 at 10:52, Andrew Sutherland <notifications@github.com>
wrote:

> I think we know enough to say that we should leave Warwick on Mmap for the
> moment (the WiredTiger performance issues we saw in the cloud can be
> managed in a controlled environment, but Warwick is much less controlled).
> The only reason to delay rebuilding the database at Warwick is to get
> people to delete collections that do not need to be there; see
> http://beta.lmfdb.org/api/stats for a list of collections that are larger
> than 1 gigibabyte. Of the 19 collections listed, only 8 exist on
> www.lmfdb.org (the 7 listed at http://www.lmfdb.org/api/stats/ plus
> elliptic_curves/padic_db which takes up less than 1GB on the cloud).
>
> The following 11 collections do not exist in the cloud and are not
> documented in
> https://github.com/LMFDB/lmfdb-inventory/blob/master/README.md.
>
>    - modularforms2/ap.chunks (295GB)
>    - modularforms2/vector_on_basis.chunks (136GB)
>    - modularforms2/Newform_factors.chunks (17GB)
>    - numberfields /old3 (11GB)
>    - numberfields/oldfields2 (10GB)
>    - numberfields/oldfields (9GB)
>    - modularforms2/Modular_symbols.chunks (7GB)
>    - numberfields /newfields (6GB)
>    - elliptic_curves/old_curves (6GB)
>
>
I deleted that today.

**Comment by jwj61** [comment]
Collections under number fields, like newfields, old* should not be copied to the cloud.  Generally newfields is used for improvements in progress, and old* are backups.  I deleted some, but it is probably good to leave some backups in case more bugs are discovered in the newest version.  In any case, there is no reason to reindex the backup copies.

**Comment by AndrewVSutherland** [comment]
@jwj61 Thanks!  The only collections that will ever get copied to the cloud are those listed in LMFDB/inventory (and associated .rand collections), so you don't need to worry about old* collections getting copied.  The main motivation for removing those that are not needed is that we want to do a dump/restore on all the mongo databases on lmfdb.warwick.ac.uk for two reasons: (1) it is the quickest/easiest way to reindex everything, and (2) it will recover a lot of space.

The current plan is to keep warwick using the MMAPv1 storage engine, which is less CPU intensive and seems to perform better than WiredTiger in certain situations (especially when there is plenty of memory available, which is true on lmfdb.warwick.ac.uk).  The main downside of MMAPv1 is that it is a bit of a storage hog, and once it allocates space from the file system for a particular database, it will never give it back (short of doing the dump/restore we are planning to do), so the total space used is effectively the sum of the "high water marks" for each database (which might be quite a bit larger than the sum of the space used by all the collections and indexes that existed at any one point in time).  Doing a dump/restore will reset all these high water marks.

The numberfields database is not that big compared to some of the others, so it is not a huge deal, but ideally one would like to be running with just 2 versions of the fields collection (a current and an "old").  But I agree that while we are in the process of cleaning up and verifying the fix to #1697 it may be worth keeping others around.

**Comment by edgarcosta** [comment]
I would propose doing this AFTER the weekly backup at Warwick.

Here are the steps:
1- Insert  the line ` engine: 'mmapv1' ` after line 7 in https://github.com/LMFDB/warwick-nt-cluster/blob/master/config/mongod.conf, this assures that we will keep using mmapv1. Also, update the repo locally.
2- stop mongodb
3- `mv  /home/lmfdb/db /home/lmfdb/db-backup`
4- `mkdir /home/lmfdb/db`
5-  in case you would like to keep the logs: `cp /home/lmfdb/db/*log* /home/lmfdb/db/`
6- start mongodb and wait
7- decide what you want to do with `/home/lmfdb/db-backup`

To speed up the replication, we could do a mongorestore between line 5 and 6.

**Comment by JohnCremona** [comment]
I propose that we delay this by a week since (1) Edgar will be travelling from Australia to the US over the weekend which must put him out of touch, (2) I will also be unable to do anything from Saturday for 7 days.  (I will be staying with family and could reposond to some emergency but definitely do not want to be on call.)  I will be back by Saturday July 30.

**Comment by JohnCremona** [comment]
PS Currently /data/db uses 1.2T and /data shows 4.6T free but with btrfs that is double what is really available.

**Comment by edgarcosta** [comment]
could we possibly remove some of the old snapshots in /data/db-snapshots?

We don't need to move /home/lmfdb/db, we can just take a snapshot of it.
(but in the end it will be equivalent)

**Comment by AndrewVSutherland** [comment]
With #1431 now closed, we can go ahead with this whenever it is convenient (sometime after July 30).
