### ISSUE TITLE
Add knowls to Search headings that give search instructions/tips

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#1300]
All of the "Search" headings above search forms should be knowls which describe how to
enter search parameters (ranges, etc), that all fields are optional, etc.

**Comment by AndrewVSutherland** [comment]
I don't think this is a backend issue, it's just a matter of changing the html pages for all the browse/search pages to put in a knowl link (and then creating the knowl).  Maybe we need a label for user interface or application issues that are not specific to a particular area and may require changes everywhere?

**Comment by AndrewVSutherland** [comment]
Related to #3721

**Comment by AndrewVSutherland** [comment]
There are really two components of this.  One is to give a generic description about things like how to enter ranges, lists, etc.., but there are also places where the details depend on the particular search page.  We probably want one generic knowl plus an optional page specific knowl.

This also highlights the fact that we are not entirely consistent about how things like range searches are done (some inputs accept not only ranges but also lists of ranges, and some do not).

I think this is an important issue and worth thinking through carefully.  Rather than trying to shoe horn this into 1.1.2, we are going to move this to 1.2.

**Comment by roed314** [comment]
Here's a proposal.

* Use the `ui.` prefix for knowls that are about generic user interaction.  This would include knowls about how to enter integer ranges, knowls about selecting columns, etc, but not knowls attached to a specific search input such as the degree of a number field.
* Write a knowl for each `search_parser` in [search_parsing.py](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/utils/search_parsing.py) describing valid input for that search parser (I'm not sure how to deal with keyword arguments that change the behavior; maybe we should work on uniformizing these so that these no longer vary).
* Add the parser type to the init method of [SearchBox](https://github.com/LMFDB/lmfdb/blob/master/lmfdb/utils/search_boxes.py#L86), and then programmatically add the corresponding knowl to the beginning/end of the mathematical knowl describing that column (either with an include or as a knowl link).  This way we don't need to create a new knowl for every column.
* Do a census of the search knowls in use and make sure they're actually describing the appropriate object in that context.  For example, "Base field" in hilbert modular forms should describe what the base field of a hilbert modular form is, not what a field is.

**Comment by roed314** [comment]
We've decided that this issue is superseded by the [search input knowl](https://beta.lmfdb.org/knowledge/show/intro.search), together with a followup at #4962.
