### ISSUE TITLE
Some ECNF pages produce 502 Server Error messages

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1358]
The page

 http://www.lmfdb.org/EllipticCurve/6.6.371293.1/79.1/c/4

(and several others) produces a 502 server error message.

**Comment by edgarcosta** [comment]
```
Exception on /EllipticCurve/6.6.371293.1/79.1/c/4 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/main.py", line 313, in show_ecnf
    ec = ECNF.by_label(label)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 125, in by_label
    return ECNF(data)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 116, in __init__
    self.make_E()
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 138, in make_E
    N = E.conductor()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_number_field.py", line 1600, in conductor
    for d in self.local_data()],\
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_number_field.py", line 1049, in local_data
    return [self._get_local_data(pr, proof) for pr in primes]
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_number_field.py", line 1115, in _get_local_data
    self._local_data[P, proof, algorithm, globally] = EllipticCurveLocalData(self, P, proof, algorithm, globally)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_local_data.py", line 280, in __init__
    self._Emin, ch, self._val_disc, self._fp, self._KS, self._cp, self._split = self._tate(proof, globally)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_local_data.py", line 721, in _tate
    t = verbose("Running Tate's algorithm with P = %s"%P, level=1)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1823, in __repr__
    return "Fractional ideal %s"%self._repr_short()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 545, in _repr_short
    return '(%s)'%(', '.join(map(str, self._gens_repr())))
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 570, in _gens_repr
    return self.gens_reduced()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 849, in gens_reduced
    self._cache_bnfisprincipal(proof=proof, gens_needed=True)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1119, in _cache_bnfisprincipal
    bnf = self.number_field().pari_bnf(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3620, in pari_bnf
    self._pari_bnf = f.bnfinit(1)
  File "sage/libs/pari/auto_gen.pxi", line 3061, in sage.libs.pari.gen.gen_auto.bnfinit (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:19784)
    pari_catch_sig_on()
  File "src/cysignals/signals.pyx", line 102, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1158)
RuntimeError: Aborted
```

**Comment by AndrewVSutherland** [comment]
Looks like a problem in Sage?  I notice that when I run it locally (on an older version of Sage) it works, its just very slow.

**Comment by JohnCremona** [comment]
Perhaps I should remove degree 6 field curves?  There are not many anyway
only one field or so.

**Comment by JohnCremona** [comment]
But also this code does stuff on the fly such as factoring ideals.  Once I
give it the same treatment as I did over Q these problems will go away.

**Comment by AndrewVSutherland** [comment]
That's one solution, another solution (which I see you just commented on) is not to use sage on the fly at all.  It removes a significant opportunity for things to break when sage changes.

**Comment by JohnCremona** [comment]
See my second comment

**Comment by AndrewVSutherland** [comment]
@edgarcosta, @JohnCremona If I execute the Sage command that appears to cause the crash interactively in Sage 7.1 on Atkin, it works fine:

 K.<a> = NumberField(x^6 - x^5 - 5*x^4 + 4*x^3 + 6*x^2 - 3*x - 1)
E = EllipticCurve([a^5 - 4*a^3 + 3*a + 1, a^5 + a^4 - 4*a^3 - 3*a^2 + a - 1, a^3 + a^2 - 3*a - 1, -12*a^5 + 3*a^4 + 61*a^3 - 66*a - 15, 37*a^5 - 7*a^4 - 188*a^3 + a^2 + 217*a + 50])
E.conductor()

Why should it crash when executing line 174 of WebEllipticCurve.py?

I'm going to run some more tests...

**Comment by edgarcosta** [comment]
I think it just takes too long...

```
lmfdb@lmfdb:~$ ./sage-beta/sage 
┌────────────────────────────────────────────────────────────────────┐
│ SageMath Version 7.1, Release Date: 2016-03-20                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
sage: K.<a> = NumberField(x^6 - x^5 - 5*x^4 + 4*x^3 + 6*x^2 - 3*x - 1)
sage: E = EllipticCurve([a^5 - 4*a^3 + 3*a + 1, a^5 + a^4 - 4*a^3 - 3*a^2 + a - 1, a^3 + a^2 - 3*a - 1, -12*a^5 + 3*a^4 + 61*a^3 - 66*a - 15, 37*a^5 - 7*a^4 - 188*a^3 + a^2 + 217*a + 50])
sage: time E.conductor()
CPU times: user 1min 35s, sys: 58.4 ms, total: 1min 35s
Wall time: 1min 35s
Fractional ideal (a^3 - a^2 - 2*a + 3)
```

**Comment by JohnCremona** [comment]
You don't want excuses but I will anyway.  When I wrote the ecnf code in 2014 we only had data for 6 quadratic fields all of class number 1 and one cubic field.  Now we have vastly more in degrees 2, 3, 4 and some in degrees 5 and 6 but the latter case ground to a halt because (1) finding the curves was taking ages and (2) even thr precomutations we were doing (such as finding complete isogeny classes) was also taking infinitely long.  But I left i the ones I did find.  Please be aware that this is the first time in human history that large-scale, extensive, computations have been done with elliptic curves over number fields defined over fields of degree>2, and that many algorithms had to be developed and implemented from scratch for this purpose.  I know that this is no excuse for still having our code *re*compute conductors just to get the factorizations and obviously we'll do here what I am in the process of doing over Q.  The simplest fix would be for me to simply delete all elliptic curves over fields of degree >4 from the database until I can add the extra data.

Despite all that the fact that Sage's code to compute conductors in this case does seem slower than it should be.  One day I will investigate why.  It probably factors the discriminant, as it certainly computes all local data at all bad primes along the way, while some special cases could be simpler (for example if c4 and Delta are coprime then the curve is semistable and globally minimal and so the conductor is the product of the primes dividing the dirscriminant.  But that's a discussion for Sage not here.)

**Comment by AndrewVSutherland** [comment]
@JohnCremona no need for excuses!  It's amazing we have these curves in the LMFDB at all, and this is why I would like to be able to show them!  And with @nmascot's new plotting code, their pictures look beautiful.

@edgarcosta @JohnCremona I ran a bunch of tests on Atkin and here is what I found (you can repeat these by running lmfdb/ecnf/ecnf_test_pages.py), The first attempt to compute a conductor of one of the degree 6 curve takes about 60 seconds, but the rest only take a few seconds (or less).  My guess is that there is some internal Sage computation that is triggered inside the conductor computation (of some but maybe not all curves?, maybe only specific to the field, e.g. computing a basis for the ring of integers?) and this is what is slow.  Once this has been done, the rest are quick.  But of course on www.lmfdb.org or beta.lmfdb this slow computation is repeated in every worker thread and takes so long that the page times out.

In any case the fix is obviously to avoid the computation of conductors on the fly; more generally, I think we should try to avoid calling Sage on the fly whenever we can avoid it.  There are tons of places in Sage where the first attempt to do something is slow but subsequent calls are fast; but for us every time is like the first time (and this is not a love song :)).

@JohnCremona I know you actually already store a representation of the conductor ideal in the database, as well as its norm.  Is there a quick fix that would involve just converting the conductor ideal stored in mongo db into the form that is currently displayed on the screen?  This might be faster than computing the conductor from scratch.

**Comment by JohnCremona** [comment]
It's not hard to construct the conductor ideal from what is stored, and I don't think that factorization itself would take long, nor getting the local info at the bad primes.
What is also done on the fly (from line 192 in ecnf/WebEllipticCurve.py) is to check if the stored model is a global minimal model and if not, at which prime(s) it is non-minimal.  The models I store are always minimal either at all primes (if that is possible) or at all but one prime (if not), but the db does not store which case holds or what the additional prime is in the second case; so this is recomputed.  All this is very embarrassing to write down.
It is a nasty job to write code which either reads information from the database if it is there or recomputes it if not -- I know since I did that for elliptic curves over Q.  What I would like to do here is *first* precompute all the additoinal data and store it in the db, and *then* change the code to use it.  The only risky thing about this is that the revised code will only work on a copy of the database which has the additional data, but I hope that at the appropriate time it would be possible to copy the nfcurves collection to the cloud quickly.

**Comment by JohnCremona** [comment]
By the way, for elliptic curvesover Q there have been many occasions since the collection was first formed when we have added to the stored data in there -- that collection has been in there for many years.  It sounds as if performance would improve if all we did were to copy it!

**Comment by JohnCremona** [comment]
I think this will be closed at the same time as #1318 which I am working on.

**Comment by AndrewVSutherland** [comment]
This appears to now be fixed, closing.

**Comment by JohnCremona** [comment]
This is mysterious since I have not yet done all the precomputations which were intended to speed up this sort of example!  I agree that right now this one displays fine.  I am reassured, since it came as a big surprise to me that such examples were taking a nontrivial time, as I had never noticed that running locally.

**Comment by AndrewVSutherland** [comment]
@JohnCremona This is indeed mysterious, because it looks like the code does still compute the conductor on the fly, and this is still slow.  On Atkin:

sage: sage: K.<a> = NumberField(x^6 - x^5 - 5*x^4 + 4*x^3 + 6*x^2 - 3*x - 1)
sage: sage: E = EllipticCurve([a^5 - 4*a^3 + 3*a + 1, a^5 + a^4 - 4*a^3 - 3*a^2 + a - 1, a^3 + a^2 - 3*a - 1, -12*a^5 + 3*a^4 + 61*a^3 - 66*a - 15, 37*a^5 - 7*a^4 - 188*a^3 + a^2 + 217*a + 50])
sage: sage: time E.conductor()
CPU times: user 1min 19s, sys: 4.16 ms, total: 1min 19s
Wall time: 1min 19s
Fractional ideal (a^3 - a^2 - 2*a + 3)

And on beta.lmfdb.org the page will still timeout if you hit refresh enough times.  But I can't make this happen on www.lmfdb.org.  I tried this page because I was testing a lot of performance issues after the rebuild of the mongo db on ms.lmfdb.xyz which @edgarcosta did this morning (now down to a slim-trim 222 GB from 600+GB and all indexes rebuilt).  So now I am very puzzled as to why this page actually now seems to work on www.lmfdb.org.  This deserves some further investigation...

For the moment I think I will reopen the issue but take off the production problem tage.

**Comment by AndrewVSutherland** [comment]
I am very puzzled.  I just computed the conductor in sage on both www-central0.lmfdb.xyz and www-central1.lmfdb.xyz and it took more than a minute in both cases.  But I just submitted 100 simultaneous requests to fetch this page (presumably being handled by different workers) and they all completed in less than 30 seconds (most in less than 5 seconds).

**Comment by JohnCremona** [comment]
Well, we know that conductors are still computed on the fly since the work involved in precomputing them and storing them has not been done yet since it has got mixed up with the simplifying ond re-sorting of models.  But that is on another ticket, and it will get done, so there is no point in keeping this issue open unless someone cares enough to work out why the times vary such a lot.

**Comment by JohnCremona** [comment]
Pending #1267 (which I am working on, I promise) it is possible that this can be improved simply by allowing Sage to call Pari with its default setting of allowing it to assume GRH (this is the default in Pari but not in Sage, and can have a drastic effect on speed).  I will try that.

**Comment by jwj61** [comment]
If you assume GRH for the number fields involved, you could then verify off line with bnfcertify in pari that you have not hit a field which contradicts GRH.  (If you find a violation, fame and fortune awaits.)  Then you won't feel any obligation to add a GRH disclaimer to the pages.

**Comment by AndrewVSutherland** [comment]
See my comment on https://github.com/LMFDB/lmfdb/pull/1879#issuecomment-234738569.  You can reproduce this issue by restarting Sage and typing

sage:  NumberField(QQ[x]([-1,-3,6,4,-5,-1,1]),'a').ideal([1,1])

Doing proof.number_field(False) before hand does not help.  And if you ctrl-C and then do it again it works fine.  I think this is a bug (presumably in Pari, based on the traceback you get on ctrl-C, which shows it stuck in bnfinit).  It occurs in both Sage 7.1 and Sage 7.2.

**Comment by AndrewVSutherland** [comment]
I don't think the problem is in Pari, this works fine in gp.
