### ISSUE TITLE
Missing non-rational coefficients for spin L-functions

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#142]
No coefficients are given for the spin L-function of a Siegel modular form
on Sp(4,Z), except in the case where the Hecke eigenvalues are rational integers.

For example:
http://beta.lmfdb.org/L/ModularForm/GSp/Q/Sp4Z/specimen/30/Ups/3/

**Comment by AndrewVSutherland** [comment]
The link above is no longer vaild (and has not been since 2016, but if I look at http://beta.lmfdb.org/ModularForm/GSp/Q/Sp4Z.30_Ups/ there is no L-function link, and there should not be L-function links for any of the SMF's (which are now only available on beta).

There is a lot of work to be done on SMFs (and we are a long way from being able to compute L-functions for them), but I don't think this issue is relevant at this point.
