### ISSUE TITLE
Simplified Weierstrass model?

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1522]
In many circumstances, it would be nice to have not just the minimal model for an elliptic curve or a hyperelliptic curve, but you'd prefer the equation
  y^2 = f(x)
which amounts to completing the square.  Maybe we could list this as well?  

[UPDATE] This feature is now available for genus 2 curves.

**Comment by JohnCremona** [comment]
At the moment I am concentrating on getting models for elliptic curves) which are minimal (or almost) and reduced, and do not care much about completing the square, which would of course be trivial to show.  So I won't stand in anyone's way but don't myself give it a high priority.

**Comment by AndrewVSutherland** [comment]
I actually thought about doing this at one point but decided against it for the following reasons:

- Screen real estate -- displaying two equations would inevitably push something that you can currently see without scrolling further down the screen where you have to scroll to see it.  One could instead have two modes (e.g. as with G2/Igusa/Igusa-Clebsch invariants), but this would make my next concern worse.
- Model dependent data -- some information (e.g. coordinates of rational points) depends on the model, which could be confusing, especially if there are two modes. In the modes sceneario you would really want to switch everything to match the model on the screen, but recomputing this data on the fly might get expensive (and in some cases it might not even apply).
- Not necessary -- it is easy to get this whenever you need it (in Magma use SimplifiedModel for genus 2 curves and WeierstrassModel for elliptic curves, and there are similar commands in Sage).

Having said all that, I could be convinced to throw this into to the code snippets if you think that would be useful.

**Comment by jvoight** [comment]
This is definitely not high priority, but it has shown up for me in at least two ways: first, in wanting to understand the Galois representation on the 2-torsion, and second, in talking to students/postdocs who don't understand why we don't show the simpler equation (to their mind).  

We can ignore me, I am just in the habit of passing on all ideas above a certain threshold.

Drew: in terms of "not necessary", I don't think that's the mode we want to be in.  There are many things you can dump into Magma or Sage and compute, but the point is the browser shouldn't have to do this.  In terms of "screen real estate", I don't know if we're really so successful with that right now anyway (we seem to show a ton of things requiring scrolling down).

Here's a modified suggestion: put the 2-torsion polynomial = minimal polynomial for Weierstrass points on the page and put it in a different variable.  We can make a comment that this gives a minimal Weierstrass model, and I think it meets all of the above constraints.

**Comment by edgarcosta** [comment]
This could also be done with a hide/show button.

**Comment by davidfarmer** [comment]
I think of the y^2 = f(x) version as aimed at the naive user, such as myself.  So having to click
to see it would defeat that purpose for including it.  Showing it would also tell people the
Magma or Sage commands to get it, which the naive user would not know how to do it.

There was some discussion about saying yes/no for when curves are hyperelliptic
(we have genus 2 curves which are not hyperelliptic, right?), so this could be integrated
with that information.

Us naive people would be happy to see such a model for the curve.  But I agree with the
"feature request" label, which means that there is no reason to give this high priority.

**Comment by AndrewVSutherland** [comment]
@jvoight, @davidfarmer I agree with both of you that trying to help out the naive user is a worthy goal; the trick is to find a way to do it while being mathematically correct and unambiguous.  My comments above were merely meant to pass on the issues that came up when I actually thought seriously about doing this (i.e. I agree completely that it could be helpful, and the fact that it is "not necessary" is not a reason not to do it).

I'm not quite sold on the 2-torsion polynomial idea, which really depends on the model and isn't really a "minimal polynomial" unless we want to define this notion for etale Q-algebras (which we should(!), but that's another debate).  An alternative idea would be to use y^2=f(x) to describe the hyperelliptic function field Q[x,y]/(y^2-f(x)), which does not depend on the model and is arguably a better way to characterize the "models" we are giving, since for they don't even define a smooth curve in P^2 for g>1, something that confuses the hell out of naive users (i.e. students) used to working with elliptic curves.

Regarding the screen real estate, I'm not suggesting we should be afraid of scrolling -- of course most home pages will require scrolling -- rather that we should regard what does fit on the top of the home page of an object as "prime real estate".  One of my pet peeves at the moment is that every page with a "show code" option turns the top line of the home page into dead space -- I'd like to fix this by moving it into a box on the right side-bar below the properties box (as is currently the case with the "download code" links).

But I'm also keenly aware that we currently have 121 open issues that are not feature requests and I should probably get back to working on them.

**Comment by JohnCremona** [comment]
@davidfarmer The pedant in me must point out: genus 2 curves are all hyperelliptic since the anticanonical class has degree 2g-2=2 which means that there is a degree 2 map to P^1.  When we get to genus 3 curves there will be two very different cases, the hyperelliptic ones and smooth plane quartics.
On the wider issues, I am a fan of model-independent data, so any equation at all will be to some extent arbitrary.  I am currently working hard (when time allows) to improve the models we already have so please do not assume that any models for curve over fields of degree 3 and above are fixed -- they are not and will change and become a lot simpler in may cases.  But I still intend to store and display global minimal models whet they exist.
The 2-division field (and the n-division field for any n) is of course an invariant, but displaying the y^2=cubic for an elliptic curve is not a very efficient way of telling the viewer what the 2-division field is.  At some point we'll have pages for 2-dimensional mod-2 Galois representations and can piont to that.  I know that this does not address @jvoight 's concern about explaining models to students though.

**Comment by AndrewVSutherland** [comment]
@JohnCremona The uber-pedant in me is compelled to point out that there are actually **three** different types of  genus 3 curves :), namely: (1) smooth plan quartics, (2) hyperelliptic curves (with a degree-2 map to P^1 defined over the ground field), and (3) degree-2 covers of pointless conics (these become hyperelliptic in the usual sense only over a quadratic extension).  In case (3) there is no model of the form y^2=f(x); these curves have models of the form g(X,Y,Z)=0, w^2=f(X,Y,Z) in P^3 (see http://arxiv.org/abs/1605.04708 for an average polynomial-time algorithm to compute the L-series of such curves).

Regarding 2-division fields, @jvoight, @jwj61 and I discussed this in the context of (Jacobians of) genus 2 curves  during the Bristol workshop, where the situation is even worse; for curves like y^2=f(x)g(x) with f and g irreducible cubics, for example, there is really no good way to specify the 2-division field using the curve model (e.g. the lowest degree field whose Galois closure is the 2-division field might have degree 9 -- its defining polynomial is not going to be especially illuminating.

Regarding pages for mod-ell Galois representations, this is something I actually started working on a while back, I just didn't have to finish them before the May 10 launch.  I have a bunch of data ready to load into the LMFDB and partially implemented pages to display them -- I plan to finish these just as soon as I can take a break from addressing higher priority bugs/issues.  With any luck I should be able to get these done this month (or next).

**Comment by JohnCremona** [comment]
I think this goes to show that I should not dare to speak on any subject except genus one curves!

**Comment by jvoight** [comment]
OK, sorry for the can of worms everyone!  I know we have more pressing issues.

One more mathematical comment on the 2-division polynomial.  The ramification points of the hyperelliptic map are a well-defined subset of PP^1 up to a linear fractional transformation, corresponding to Weierstrass points on the curve.  A polynomial that has these values as roots is a meaningful thing to write down.  I realize that the *field* obtained by adjoining these roots has some potential issues, but I don't see how these concerns nullify the clarity or usefulness of this polynomial.

**Comment by JohnCremona** [comment]
If we were going to show the 2-division polynomial on the home page of every elliptic curve, the standard scaling for it has leading coefficient 4: it is 

4*x^3 + (a1^2 + 4*a2)*x^2 + (2*a1*a3 + 4*a4)*x + a3^2 + 4*a6) 

so that would be (to me) the natural one to display, though of course it is not what one gets by completing the square, which is 

y^2 = x^3 + (a1^2+4*a2)*x^2 + (8*a1*a3+16*a4)*x + (16*a3^2+64*a6)

To go from one to the other, replace x by x/4 and multiply through by 16.

**Comment by AndrewVSutherland** [comment]
Removed the genus 2 label since this was implemented for genus 2 curves a while ago.

**Comment by JohnCremona** [comment]
This has been implemented.
