### ISSUE TITLE
Remove number_fields_galois_groups

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1649]
None of the links on http://www.lmfdb.org/NFGG/ work and it appears that this code has been made complete superseded by http://www.lmfdb.org/GaloisGroup/.  There have been essentially no changes to the code in the last 4 years other than for general system-wide code maintenance issues (like the one I am working on now).

If this is indeed the case the line "import number_field_galois_groups" in website.py should be removed and the files in number_fields_galois_groups should be deleted (of course they will still be available in the github history if anyone needs to refer to them).

**Comment by jwj61** [comment]
This was part of the original artin representation package.  The data was incorporated into the pages of individual artin rep'ns (explicit action on roots as permutations).

I _think_ this can be removed because the infrastructure which is needed is in mathclasses.py, but I am not 100% sure since I didn't write it.  So, if you start removing it, the key places to check are artin rep pages and pages of number fields which have artin reps.

**Comment by AndrewVSutherland** [comment]
@jwj61 There were two unused imports of number_fields_galois_groups in artin_representations/main.py that I removed in #1654 (I also cleaned up the import *'s, per #122 and removed other unused imports identified by pyflakes), which comments out the import of number_fields_galois_groups in website.py.  Everything seems to work (all tests pass except for one problem in classical modular forms that has been there for a while and has nothing to do with this).

If you are happy with this change, please go ahead and merge.  Once it has been pushed to beta and everything looks good I will submit a second PR to delete the number_fields_galois_groups files.

**Comment by jwj61** [comment]
I will be happy to look at it, but it will be probably be next week.

**Comment by AndrewVSutherland** [comment]
Closed via #1654
