### ISSUE TITLE
Fields cut out by Dirichlet characters

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1712]
As indicated in the knowl http://www.lmfdb.org/knowledge/show/character.dirichlet.related_fields that appears on the page of every Dirichlet character (of modulus up to 10^5), there are two fields associated to any Dirichlet character, it's field of values and the field cut out by its kernel (see http://www.lmfdb.org/knowledge/show/character.dirichlet.field_cut_out for the definition of the latter).

Currently we never display the kernel field; the attribute is defined in WebCharacter.py but not computed.  I don't think it makes sense to try and compute these on the fly, but it would be reasonable to precompute them for characters of order < 24 whose kernel fields are in the LMFDB and then store this information in the database.

**Comment by AndrewVSutherland** [comment]
@jwj61 Would it be easy to do this from the number field side?  Perhaps this is something you have already thought about (I notice you are the author of the knowls I referenced above).

**Comment by jwj61** [comment]
There is a corresponding number field issue: take an abelian field and find the group of Dirichlet characters which go with it, and we have this (computed on the fly).

The current thing is doable, but it starts with a Dirichlet character.  I can think of two ways to code it offhand (use the characteristic polynomial of an appropriately constructed algebraic element, or compute the polynomial from floating point approximations to roots).  The second one probably works faster in some cases, but you have to be concerned a bit with precision.

Either way, if you want to precompute it, the natural place to store the results is in the Dirichlet character database (rather than in the number field database).  Last time I checked, that doesn't exist, but this would be a reason to create one.  You could then decide how much to compute on the fly vs precomputation.

**Comment by pascalmolin** [comment]
I have taken this issue.

We could do it on the fly, pari/gp has this functionality already and it is fast (btw it uses newton sums to recontruct the polynomial from the appropriate sums of roots or unity), except that we do not want to polredabs on the fly.

So I have launched the computation, for all orbits of characters of order <= 24, and modulus <= 10^5.
This makes a big list [character, polynomial], so I guess the next step is to understand how the database works for Dirichlet characters and make a table galoisorbit -> numberfield label.

**Comment by AndrewVSutherland** [comment]
This has been resolved by #4130 and subsequent cleanup.
