### ISSUE TITLE
Deprecated app.routes?

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1717]
Should we remove:
* /a/int
* /form
* /example
* /calc
* /form
* /example_plot
* /example/blah

?

Yes: 
* /hg/blah 

No: 
* /checklist 
* /checklist-list 

?

All these app.routes are in `base.py`, many do not work.

**Comment by JohnCremona** [comment]
I still use /checklist from time to time -- it is perhaps superceded by the testing we do using test.sh but it still has some uses, e.g. for a demo.  But perhaps its existence ought to be advertised as I am not sure if all reletively recent joiners know about it  ( @AndrewVSutherland ?)

**Comment by edgarcosta** [comment]
@JohnCremona Thank you. Let's keep it then. The goal is to get rid of deprecated  and/or unused code, and nothing else.

**Comment by AndrewVSutherland** [comment]
So I took a look through these (BTW they are in website.py not base.py).  Here is a list of routes that I think can and should definitely be removed:

- /hg (as noted above, we don't use mercurial)
- /a/\<int a\> (all this does is return a latex string representing a/(1+a)
- /form (this is a *very* rudimentary UI for looking up elliptic curves by conductor)
- /example and /example/\<blah\> (this tries to render the template example.html which no longer exists)
- /calc?ep=blah (displays blah, fails if ep is not specified)
- /modular/, /ModularForm, /AutomorphicForm/ -- these attempt to redirect to modular forms but they use the wrong redirect; the last two work because /ModularForm/ and /AutomorphicForm/ are also registered in modular_forms/__init__.py

Probably should be removed:

- /example_plot?k=n uses plot_example.py to display a plot of sin(n*x).  This works, but I see no reason for it to exist.  If we remove it we should also remove plot_example.py.

Should stay:

- /checklist, /checklist-list @JohnCremona I didn't know about this but I like the concept (test.sh can easily miss things that are obvious to human eyes).  Might be worth updating.

I will create a PR to remove the things that definitely should be removed.  Anyone who thinks example_plot should stay should chime in.

**Comment by AndrewVSutherland** [comment]
Closed via #1737 (if anyone else thinks example_plot should be removed, please say so and I will remove it, but at least it does work).

**Comment by JohnCremona** [comment]
I think example_plot should be removed too.  If it useful as an example of how to do something then leave the code there but commented out.

**Comment by AndrewVSutherland** [comment]
I don't think it is very useful I will submit at PR to remove it.

In the longer term, what might be useful to new developers is a minimal example application that has a simple mongo db collection of objects, a browse page, a search-results page, and an object page that illustrates "best practices" for implementing new LMFDB components and could serve as a reference (and also a standard for the UI).  This could also be used as a basis for a tutorial in a developer's guide.
