### ISSUE TITLE
Number field pages no longer work in --debug mode

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1770]
If you run the lmfdb in debug mode (e.g. via "sage start-lmfdb.py --debug") and then go to the home page of any number field other than Q, (e.g. 127.0.0.1:37777/NumberField/2.0.3.1) you will get

PariError: expression nested too deeply

occurring at line 323 of number_field.py in render_field_webpage where rootsofunity is set.

Works fine if --debug is not set, so not a production issue, but would be nice to fix.

**Comment by jwj61** [comment]
I assume you mean "sage -python start-lmfdb.py --debug"?  With that, I don't see the error running off of lehner (which has an additional flag to set the port).

**Comment by AndrewVSutherland** [comment]
Actually I don't get the problem on atkin (whether I use -python or not), so it must be something specific to my sage/pari set up (I have newer versions of both sage and the pari library installed that I was using for some unrelated work and it's possible I did not install everything correctly).  I'll close this now.  Something to double check if/when we switch to sage 7.2.

**Comment by JohnCremona** [comment]
I see no problem on lehner, which is running Sage 7.2.  atkin is still running 7.1, partly so that I can easily test on either one.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Thanks, must be something screwy with my pari install.

**Comment by jwj61** [comment]
pari has changed the syntax of extra arguments to nfinit and friends.  I would not surprise me if we had to adjust when we upgrade sage and it has an upgraded pari in it.  The bug with Q as a number field is (in my opinion) a shortcoming of the current syntax.  In the format [poly, [list]] the list can be either a basis, or primes where you want the order to be maximal.  When list=1, it treats it as a prime and throws an error even though it was a reasonable basis.  I think @AndrewVSutherland's fix of using the empty list worked because it was interpreted as "don't be maximal at any primes", which is ok when initializing Q since you can't contain 1 and fail to have a maximal order.

**Comment by JohnCremona** [comment]
@AndrewVSutherland which version of Sage were you using to get the problem?  Sage uses its own pari, not any other you may have on your machine, so if you use either Sage-7.1 or Sage-7.2 it should be OK.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I am in the process of reinstalling Sage 7.1 so that I will be consistent with Atkin.  I was running both Sage 6.5 and Sage 7.2, and I have pari 2.7.5 installed (but from what you say, that should not matter).  I think the problem probably occurred because I inadvertently ran Sage 6.5 -- sorry for the confusion, I usually test on Atkin but did not in this case.

**Comment by JohnCremona** [comment]
Any reason to install 7.1 rather than 7.2 (released 2 months ago)?  And 7.3 is into beta8 but I have not yet tried running lmfdb with it

**Comment by AndrewVSutherland2** [comment]
I want to do all my LMFDB development and testing on the same version of
sage that we are running in production.

**Comment by JohnCremona** [comment]
We had better start to do some testing with newer versions as well, otherwise we'll never be able to upgrade the production Sage.  In fact I have 7.2 waiting in the wings on lmfdb.warwick, and it passes all tests.  I am tempted to start the warwick version of prod  with that, but before that it would make sense to ensure that we always test on machines running 7.2 such as lehner (as of now).   BTW, on atkin & lehner I always have the previous system-wide Sage available as well as the default so it would be very easy right now for us to test on both versions on each machine.

**Comment by AndrewVSutherland** [comment]
For the purpose of diagnosing problems showing up on the production system (which is what I have been focusing on), it makes sense to be running the same version of sage as we are running in the cloud (7.1), and certainly for release managers who are pushing code to prod, we want to be running test.sh using  7.1.

Currently the switch to Sage 7.2 is scheduled for LMFDB Release 1.2, which I think makes sense; until we complete Release 1.1 (which is really just about fixing bugs), I don't think we want to slow ourselves down by testing everything on both Sage 7.1 and 7.2.  Once Release 1.1 is out the door, then we can focus on the switch to Sage 7.2 (or even skip directly to 7.3 if you think that makes sense).

**Comment by JohnCremona** [comment]
OK

**Comment by JohnCremona** [comment]
I'll quietly continue to monitor any issues which new Sage versions might cause.  All is well at the moment -- with 7.3.beta8 all tests pass.  Also atkin has Sage-7.2 available as /usr/local/sage/sage-2/sage and I would like to make that the system-wide default, with /usr/local/sage/sage-1/sage still on 7.1 as it is now.  Anyone who wants to have that older version as what typing "sage" runs could put their own alias or link in place.  Any objection?
Normally I would already have 7.2 as the default (as it is on the other machines I manage) and as soon as 7.3 is relased (not just betas and rcs) I would upgrade the older 7.1 to 7.3 and make that the new default; this way the current and previous releases are always available but nothing earlier than that.
For LMFDB itself it might already be an idea to test whether the running Sage version is at least 7.1 and output a warning if not.  That might have prevented this issue being opened!

**Comment by AndrewVSutherland** [comment]
I agree, see #1787.
