### ISSUE TITLE
Knowl on self duality for gl3 Maass forms discrepancy

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1913]
From the feedback page:

See

http://www.lmfdb.org/L/ModularForm/GL3/Q/Maass/4/1/12.45226_3.663403/-1.0061924/

The given Maass form in gl3 is stated to be self dual, and the knowl for self duality says that it means that the L function fourier coefficients are real. The given L function does not have real Dirichlet coefficients.  I think that for gl3 the definition of self duality does not match with that in the knowl.

Please reply to ekiral@tamu.edu with feedback and when this is resolved.

**Comment by davidfarmer** [comment]
The Gaga box incorrectly states that the L-function is self-dual.

It looks like the database entry is incorrect, because I also see that
the plot is wrong (half of it is correct, but the other half is a
reflection, while it should be calculated separately.

I suspect all of the level 4 examples on GL(3) with sign +1 are
mistakenly labeled as self-dual.  Those are the blue dots at the
bottom of

http://www.lmfdb.org/L/degree3/MaassForm/

Correcting those database entries should fix everything.  (Or do a hack
to intercept the wrong information, since I don't know how that data
was uploaded.)

David

**Comment by AndrewVSutherland** [comment]
There are 20 primitive degree 3 conductor 4 non-algebraic L-functions that were incorrectly marked self-dual.  The self-dual flag has now been changed to false, but the conjugate L-functions are missing, so they cannot be displayed correctly (the display code uses the conjugate for half the plot and to get the zeros below the real axis).  We are going to temporarily disable the Conductor 4 browse plot on http://www.lmfdb.org/L/degree3/r0r0r0/ so that these L-function are not accessible to the user.

Once the conjugates of these L-functions have been computed and the data uploaded we can re-enable this plot.

**Comment by davidfarmer** [comment]
Also, the now hidden plot indicates some other issues with the data:
presumably the number of red and green dots should be approximately equal,
but they are not.

There also is Issue  #2580, which (will be) closed because now there
is not link to that L-function.  But if we again show the plot, then
that linked L-function is wrong.

In other words, the underlying data for that plot needs attention, even
if we fix the upload problem that omitted the conjugate forms.
