### ISSUE TITLE
Font in Riemann zeta Dirichlet series

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1918]
From the feedback page and support-group e-mail list:

On http://www.lmfdb.org/L/Riemann/

the first equation on the page shows lower case s on the left, but the series on the right has UPPER case S
Dirichlet series
ζ(s)  = 1         + 2-s + 3-s + 4-s + 5-s + 6-s + 7-s + 8-s + 9-s +

Note in the screenshot (I sent you via feeback for the google group), the left lowercase s has curvature and different serif than the uppercase s on the right which has straight line serifs

Reply to nyc10003@nyc.rr.com regarding this report.

**Comment by JohnCremona** [comment]
Looking at the page source shows what is happening: on the left we have $\zeta(s)$ in math mode, but all the negative s exponents are plain html: <sup>-s</sup>.

**Comment by davidfarmer** [comment]
On line 1050 of style.css the following is commented out:
font-size: 75%;

You can experiment with activating that line, which will make the "s" in the exponent smaller.
(That can be done in Inspector: no need to edit the code.)
That may make it look less "upper case", because it will be smaller.
But it will still be a different font, because the s on the left side is from MathJax.

I don't have a strong opinion either way.  Git blame says I wrote that line 4 years ago.

Maybe I will experiment with using HTML instead of mathjax on the left.
