### ISSUE TITLE
Question on Euler factor of classical modular form

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1923]
From the feedback page regarding http://www.lmfdb.org/L/degree2/CuspForm/

"Why isn't the factor of the L function at p not dividing N equal to 

(1-a_p p^{-s} + p^{1-2s})^{-1}?

 Compare e.g. p.97 of Modular Forms and Fermat's Last Theorem, ed. Cornell et al.

You have the quadratic term p^{-2s}.  What you have is the same as what appears on the corresponding page for Maass forms of weight 0.  Are they supposed to be the same?

Am I missing some kind of normalization?

Thanks,
Avner"

Please respond to Avner at ashav@bc.edu

**Comment by JohnCremona** [comment]
It's the analytic / algebraic normalization.  So perhaps this page ought to mention that, and someone should email Ash.

**Comment by davidfarmer** [comment]
Dear Avner,

The L-function on that page is shown in the analytic normalization,
meaning that the functional equation relates $s$ to $1-s$.

Switching to the arithmetic normalization requires a change
of variables that shifts $s$ by $\frac{k-1}{2}$.  In the arithmetic
normalization the local factor in the Euler product has a term
$$
     p^{k - 1 - 2s}
$$
which equals
$$
     p^{1 - 2s}
$$
when $k=2$, which is the case of concern for FLT.

At some point we should let that page give you the option of
viewing in either the arithmetic or arithmetic normalization.
We have started to make such changes in the LMFDB, such as on
the home page of L-functions associated to elliptic curves:

http://www.lmfdb.org/L/EllipticCurve/Q/57.a/

Regards,

David

**Comment by davidfarmer** [comment]
Dear David,

For the Maass form, if I want the arithmetic normalization, do I just set k
= 0 in what you wrote?

Thanks,
Avner

**Comment by davidfarmer** [comment]
Dear Avner,

You can think of the Maass forms as having k=0, but the concept
of "arithmetic normalization" does not apply to them.

Suppose L(s) = \sum a_n n^{-s} is an L-function in the analytic
normalization.  If that L-function has an arithmetic normalization,
then there is a number field $F$ and an integer $w$ (called the
motivic weight) such that
$$
n^{w/2} a_n \in \calO_F
$$
for all $n$, where $\calO_F$ is the integers of $F$.  For GL(2)
holomorphic modular forms, the motivic weight $w$ is one less
than the classical weight $k$.  Maass forms don't have a motivic
weight because their coefficients are (conjecturally) transcendental.

Regards,

David


then the motivic weight of the L-function is the smallest integer $w$

**Comment by davidfarmer** [comment]
Closing because this is correct as is, and will cease to be confusing when we have modular
form L-functions served from a database and available in both normalizations.
