### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1931]
Hello,

The footer isn't really a footer for the main page, i.e., the div is flushed to the bottom:

<img width="1600" alt="screen shot 2016-09-13 at 14 23 57" src="https://cloud.githubusercontent.com/assets/322822/18486141/f38b69fc-79bd-11e6-9d20-c1d8f9859b03.png">

Here is a possible fix on the CSS:

```
    position:absolute;
    bottom:0;
    width:100%;
```

<img width="1600" alt="screen shot 2016-09-13 at 14 24 20" src="https://cloud.githubusercontent.com/assets/322822/18486140/f38b3fcc-79bd-11e6-8565-bf71817c2376.png">

**Comment by AndrewVSutherland** [comment]
I don't think we want to do this -- at least not with the css you suggest.  At screen resolutions where the side bar runs into the footer (and on beta) the footer will hide part of the side bar that would otherwise be visible and the scrolling behavior is not ideal (depending on the browser the "footer" may scroll, keeping part of the sidebar hidden).

**Comment by edgarcosta** [comment]
I agree.
That is why I only suggested it, as I didn't spend much time thinking about it, and I was afraid I would break something trying to fix a low priority issue.

**Comment by JohnCremona** [comment]
Can we close this then?

**Comment by davidfarmer** [comment]
Will leave as-is, and check later if a different solution might be appropriate.

**Comment by edgarcosta** [comment]
I agree, I tried again to find an alternative solution and I wasn't able.
