### ISSUE TITLE
Root number mismatch?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1950]
From the feedback page:

Dear LMFDB, I am confused about your entry http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/1/18/1/a/0/. It concerns the L-function of a holomorphic Hecke cusp form f of weight k=18 and level 1. You state that the root number is 1 and the central value L(1/2,f) is positive. However, as the level is 1, the root number should be i^k=-1, and so L(1/2,f) should vanish. Am I missing something? Please let me know by email: coolissues@freemail.hu Thank you in advance!

**Comment by JohnCremona** [comment]
Is this the same as #1941?

**Comment by davidfarmer** [comment]
It is the same as #1914

**Comment by JohnCremona** [comment]
That's what I meant to type.  Then I suggest that we can close this one, provided that we add a note to #1914 including the email address of the person reporting this one.

**Comment by davidfarmer** [comment]
I think this problem just comes from line 477 of lmfdb/lfunctions/Lfunction.py
which should say
     self.sign = (-1)**(self.weight/2)
instead of always equaling 1.

**Comment by JohnCremona** [comment]
I agree and will approve a code change to that effect!  I think it should also work to remove the spacial case for level 1 since the general code a few lines below should handle this case, though that relies on self.AL[self.level] returning 1 which it might not do (I guess self.AL would be an empty list for level 1). 

I actually think that the WebNewForm class should have, and set, a sign field in its constructor.  But for now fixing this in Lfunction.py is simplest.

**Comment by davidfarmer** [comment]
Has been fixed, and I replied to the person who brought it to our attention.
