### ISSUE TITLE
Explicit formulas question

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#1967]
From the feedback page:

On http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/1/12/1/a/ are two explicit formulas. However, the first is missing its left-hand side? Moreover, I have not worked out what E_4 and E_6 are, and the equation does not link to their definition. Are these the Sato-Tate groups E4 and E6?

Also, the TeX and MathML provide no clues. It would be useful if the MathML provided useful <annotation> encoding (e.g. as functions.wolfram.com does).

Please respond to paul.c.abbott@gmail.com

**Comment by davidfarmer** [comment]
I agree that both or neither should have a left-hand side.

I suggest neither, because it is problematic to name the
modular form -- that particular page uses \Delta(q) at the top,
and \Delta(z) in the explicit formula.  We don't want to be
giving a name in other cases, such as:
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/11/2/1/a/

What I think could be reasonable is a a knowl about Modular
Forms with Names.  That knowl would be accessed from the
Explicit Formulas header on 1.12.1.a, and from the
eta-product header on 11.2.1.a

Examples of modular forms with names are Delta, eta,
E_4 and E_6 (maybe E_k in general).

And maybe someone can come up with a better title than
"Modular forms with names".

I will write to the person and explain that E_4 and E_6 are
level 1 Eisenstein series.

**Comment by davidfarmer** [comment]
It was suggested to also include a formula for Delta in terms of theta functions:

 (1/2 EllipticTheta[2, 0, Sqrt[q]] EllipticTheta[3, 0, Sqrt[q]] EllipticTheta[4,
      0, Sqrt[q]])^8

**Comment by davidfarmer** [comment]
Fixed by pr #2067
