### ISSUE TITLE
Labeling of primes for HMFs

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#1968]
Yay, labels!

Reported by Mark Watkins: on
  http://www.lmfdb.org/ModularForm/GL2/TotallyReal/2.2.104.1/holomorphic/2.2.104.1-5.2-c
the label for the Atkin-Lehner prime is different than the label as a Hecke eigenvalue.  There is no mathematical contradiction here, just possible confusion.  

@JohnCremona and @AurelPage, y'all had a new system that will eventually replace all of these?  If so, we could probably ignore this issue.

**Comment by AurelPage** [comment]
Yes, jointly with @AndrewVSutherland we have a labelling system for ideals that depends only on the choice of a defining polynomial for the number field.

**Comment by JohnCremona** [comment]
That's right -- we have independently coded the agreed scheme in Sage, Magma and gp and have run automated tests to check that all three agree.  I am beginning to apply these to elliptic curves over number fields, but doing this to all the HMFs will be a long job.

**Comment by jvoight** [comment]
Y'all rock my world!  Thank you!

I'm leaving this issue open, but with the understanding that it need not be individually address and will be addressed by this more comprehensive fix.

**Comment by JohnCremona** [comment]
See https://github.com/JohnCremona/sorting for the code and a document explaining the system in excruciating detail.

**Comment by jvoight** [comment]
Before this is implemented, we should discuss a similar standard for the *ideal definition*, which is not covered by the label and may contribute to a source of this issue.

**Comment by AurelPage** [comment]
What do you mean by the "ideal definition"?

**Comment by davidlowryduda** [comment]
For instance, in the page that John displayed there was an ideal generated by -i-2, which is a bit atypical. I think that most people would think of this as the ideal generated by i+2. At least, I believe this is what we're chatting about.

**Comment by JohnCremona** [comment]
On 15 June 2017 at 16:29, David Lowry-Duda <notifications@github.com> wrote:

> For instance, in the page that John displayed there was an ideal generated
> by -i-2, which is a bit atypical. I think that most people would think of
> this as the ideal generated by i+2. At least, I believe this is what we're
> chatting about.
>
The code here is a bit of a stop-gap: I don't store any primes and when
preparing the data for that web page I generate them on the fly (in the
right order!) and used sage's  p.gens_reduced()[0] to get the generator.
If we implement a nice function to give us good generators for a Sage ideal
we can add that so that everyone can use it.  Of course it would be better
if these were precomputed.

**Comment by jvoight** [comment]
The terminology "ideal definition" is what I thought I heard @JohnCremona use, am I wrong about that?  

I mean a way of writing down the ideals themselves in bits in a deterministic way, as opposed a computable bijection from the set of ideals to the natural numbers.  Look, we have to display generators, which means we have to decide how to display generators.  

One possible answer is "it doesn't matter what we choose", so for example (2+i) can't be distinguished from (-2-i)--with similar questions coming up when the ideal isn't principal.  But then then after all that you've done to understand ordering (and representations) of ideals, I'll be a bit disappointed!  

I'd prefer us to say something like: "it doesn't really matter, but we can similarly apply 'polredabs' to the ideal lattice itself and similar tie-breaking to get as close as we can to a nice small set of generators".  I don't think this is terribly difficult, but the time to do it--if we ever do it--is now.

**Comment by AndrewVSutherland** [comment]
I agree with @jvoight that it would be useful to standardize the representation of an ideal in terms of generators.  We have already implemented deterministic code in magma/sage/pari-gp that transforms an ideal label into an ideal (specified by generators), it's just a matter of agreeing on a canonical form for the generators -- @JohnCremona @AurelPage, let's talk about this.

**Comment by pascalmolin** [comment]
Sorry, I add some noise to the discussion: this has nothing to do with
ideals generators but it's related to the next steps with ideal labels.

Thanks to your new ordering on ideals we can also define a set of
"standard" generators for class and ray class groups. With @AurelPage
<https://github.com/aurelpage> we agreed that it would be sensible to
greedily take the smallest ideal which generates the biggest cyclic
component left.

This in turn allows to have a numbering scheme for Hecke characters (at
last).

I have just written some gp code which does the job for ray class groups
(stupid hnf behind, this could be improved). The generators obtained are of
course much smaller than those given by Pari/GP.

As an example, for this ray class group Z/4 x Z/2 x Z/2 x 2/2
bnf = bnfinit(x^5-x^3+3*x-2);
bnr = bnrinit(bnf, 12,1);

the "minimal" generators are

[[5, 1], [19, 1], [25, 1], [35, 1]]

instead of Pari [ ideal2label(bnf,i)|i<-bnr.gen]

[[7529, 4], [33239, 1], [122359, 3], [253087, 2]]

2017-06-15 23:19 GMT+01:00 Andrew Sutherland <notifications@github.com>:

**Comment by AurelPage** [comment]
OK for standard ideal definitions. Question: when the ideal is principal, do we want to impose that we define it by a single generator? This could seriously affect the complexity of computing this ideal definition.

**Comment by danyasaki** [comment]
I agree it would be useful to standardize the representation of an ideal in terms of generators.  I prefer that even when the ideal is principal, the standard ideal definition looks the same.  When scraping the database, it is nice when the syntax for a key:object pair is known beforehand.

**Comment by JohnCremona** [comment]
Brief comment: I did use the phrase "ideal definition", and  by that I mean any representation of the ideal from which one can reconstruct the ideal, without being prescriptive at all about what that representation is.  This is by contrast with "ideal label" which in some of our situations at present (HMFs) does not tell you exactly which ideal you mean, only the norm.
You could say that the distinction goes away when we use the standard labelling scheme, but it is probably still good to store ideal definitions for display for efficiency.

**Comment by jvoight** [comment]
It will be painful to change labels of primes from what we're doing now to the created standard.  Since there is nothing wrong, I'm closing the issue.  If there is an HMF 2.0, we'll revisit to ensure we compute using the standard label for ideals.

**Comment by JohnCremona** [comment]
OK with me.
