### ISSUE TITLE
MathJax CDN shutting down on April 30, 2017

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2007]
Hello,

the server cdn.mathjax will be shut down by the end of the month, see:
https://www.mathjax.org/cdn-shutting-down/

At the moment we load MathJax from there
```
<script type="text/javascript" 
 src="http://cdn.mathjax.org/mathjax/latest/MathJax.js">
</script>
```
we can either have it locally installed or use ```cdnjs.cloudflare.com``` with

```
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?...">
</script>
```
(there is no ```latest``` option available)

either case, we will need to follow MathJax release schedule.

Best,
Edgar

**Comment by haraldschilly** [comment]
I suggest to go with cloudflare's cdnjs.

**Comment by AndrewVSutherland** [comment]
Agreed, I think cdnjs is a good choice.  And I actually like having the version number fixed -- we will want to stay more or less current, but at least this gives us a chance to check for problems before switching rather than have a version change break something on one of our pages without any warning.

**Comment by edgarcosta** [comment]
Thanks for your feedback.
I took care of it. See #2008
