### ISSUE TITLE
Display some objects in their main page

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2047]
Hi,

When one accesses the Riemann Zeta function we display the first zeros by default.
I would like to see the same behaviour where appropriate.
For example, for Elliptic curves, Genus 2 curves and Hilbert Modular forms (and perhaps many other classes) it seems natural to me to show the first few results of the default search.
What do you think?

Cheers,
Edgar

**Comment by davidfarmer** [comment]
In some previous discussion, it was decided to show a few Euler
factors on the home page of isogeny class of a genus 2 curve,
but not in the pages of the individual curves.  The first few zeros of the
L-function are shown on the home page of the L-function, but not
on the page of the object itself.

I am pretty sure there will not be consensus to show zeros of an
L-function on a page that is not about L-functions.

But note that elliptic curves and genus 2 curves are inconsistent about
where they show Euler factors.

**Comment by edgarcosta** [comment]
I'm sorry for not being clear.
What I had in mind is for "http://www.lmfdb.org/EllipticCurve/Q/" displaying some of the first results that you would have obtained if you only clicked enter in the search box.



In a picture:

<img width="1270" alt="screen shot 2017-05-14 at 15 23 13" src="https://cloud.githubusercontent.com/assets/322822/26037070/b54310bc-38b9-11e7-8db9-1167dadae0e2.png">

Obviously, we have bigger fish to fry. I'm just trying to gather some input, if indeed we think this is a good idea.

Cheers,
Edgar

**Comment by AndrewVSutherland** [comment]
I think your example screen shot indicates why this is probably not a good idea: there just isn't enough screen real estate.  We will surely be adding more search options in the future, and there is no point in showing an initial list of objects if it won't fit on the first page (which might already be true at lower screen resolutions).

I think the numerous browsing options already provided on this screen (e,g, conductor range, random curve, or just pressing enter) give several one-click/one-keystroke ways for someone who just wants to see what is there to do so.

**Comment by edgarcosta** [comment]
Makes sense

**Comment by JohnCremona** [comment]
I agree with the previous comments, especially about there not being enough room.  But it's healthy to keep on having ideas on what might improve things.
Another idea I had is to have a variant on the random object link which gives a random object satisfying some search criteria.  Of course we can always just look at the search results and pick an object from the list returned by hand.  But I don't see an efficient way of implementing this any better than a version of the random object selection which happens when there is no .rand collection, and it is certainly not a priority.

**Comment by davidfarmer** [comment]
Also, the space at the bottom of the current page is "free",
in the sense that putting a lit there does not impair any
of the current functionality.

Having such a list could enable quicker navigation to popular
curves.

Maybe we should reopen this issue?

**Comment by JohnCremona** [comment]
I reopened it since if nothing else it makes it easier to add comments.

On http://beta.lmfdb.org/EllipticCurve/ I put a short list of "Curves with interesting properties" with links -- not the curves themseves.  It would certainly be possible to add something similar to http://beta.lmfdb.org/EllipticCurve/Q/ i the browse/search section, though it is rather arbitrary what to include.

**Comment by edgarcosta** [comment]
That might be nice, even though its arbitrary.

My idea was just displaying the first results of the default search at the end of the page, just as a sample of what that search will display.

**Comment by roed314** [comment]
@edgarcosta, do you still think this is a good idea, or can this issue be closed again?
