### ISSUE TITLE
Maass form missing coefficients

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2075]
This Maass forms has no coefficients:
     /ModularForm/GL2/Q/Maass/5411a477acf7560ce8a6f594
but its L-function friend does.

**Comment by davidfarmer** [comment]
Not sure if this is related to issue #1812

**Comment by davidlowryduda** [comment]
I believe this is a different problem. I notice that the list of coefficients (as obtained through the download link on the page) is nonempty, and agrees with the coefficients of the associated L-function. This is a different behavior than in #1812, where the database has no coefficients.

It appears that there were several different ways in which people found these coefficients in the past, and these have manifested in a few redundancies in the code. I'm tracing this through now, and I think I see where the problem lies.

**Comment by davidfarmer** [comment]
Closed by  #2084
