### ISSUE TITLE
Tiny coefficients should be zero

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2076]
There are imaginary parts of size 10^-16 which should be 0,
and the same for some real parts (except that they are shown as 10^-11).

/ModularForm/GL2/Q/Maass/4f62407288aece3d9f000010

**Comment by fredstro** [comment]
How do you suggest to determine which coefficients should be displayed as zero or not? 
For instance the coefficient nr. 498 is listed as -1.09198e-05-9.0e-12i   
and this should probably be zero but is only computed to precision 1e-5.

One alternative would be to re-compute all coefficients and try to get them all to the same precision

**Comment by davidfarmer** [comment]
This is somewhat related to my question yesterday, about how to
keep track of the precision of the numbers in the database.

Temporarily, I suggest some hard-coded threshold, such as
1e-9

I realize that this will not catch that 498th coefficient, but
my immediate concern was for visual browsing.  People usually look at
the first few coefficients, which have higher precision.

**Comment by davidlowryduda** [comment]
I'm a bit confused about the precision. In the `properties` bar of the example form, there is a line saying that the precision is 3e-12. Does this refer to the 20 coefficients displayed by default? @fredstro indicated that the precision for coefficient 498 is known only with precision 1e-5 --- can we say this because -1.09198e-5 is almost certainly actually zero, and so this indicates the error amount? Or perhaps there is another place where I should be looking to see the precision of each coefficient?

**Comment by davidfarmer** [comment]
With these types of calculations, there is more precision with the first few
coefficients, and the precision (in terms of number of correct digits) tends
to drop linearly.  So, to the people who work in that area, it is understood that
the precision refers to the initial coefficients.  Equivalently, you can evaluate
the function to that precision, because the importance of successive coefficients
drops off exponentially.

Because of that, and the fact that it will be a while until we have precision information
in the database, I think we just want a simple solution that generally make things
more reader-friendly.  That is why I suggest a cutoff like 1e-9, preferably done in a way that
can easily be changed later.

**Comment by davidlowryduda** [comment]
Ok, that makes sense. In that case, I plan to start thinking about this issue.
