### ISSUE TITLE
On some pages, the properties/Gaga box will not collapse

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#2103]
On pages with a Properties box, there is an up-arrow in a circle that one can click to collapse the Properties box.  On most pages, this works in the obvious way (as in, for example, /ModularForm/GL2/Q/holomorphic/7/6/1/a/).

But on some pages, this minimize functionality isn't there. See for example http://www.lmfdb.org/EllipticCurve/Q/11/a/2

**Comment by JohnCremona** [comment]
I see the up-arrow in a circle on that page, but it does nothing.

**Comment by SallyKoutsoliotas** [comment]
Alina, David, and Sally will work on this.

**Comment by alinabucur** [comment]
Sally, David and Alina figured out that the issue seemed to be caused by the fact that the Elliptic Curve homepage template (elliptic_curves/templates/ec-curve.html) read jquery-latest again in addition to the thing being read by the homepage.html template. The issue was resolved when we deleted the top script that did this:
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"></script>
<script type="text/javascript"
src="http://code.jquery.com/jquery-latest.min.js"></script>

See Sally's pull request.

**Comment by christellevincent** [comment]
This should be closed
