### ISSUE TITLE
Links to ECNF broken by label change

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2136]
On the production site the genus 2 curve page http://www.lmfdb.org/Genus2Curve/Q/2916/a/ contains a link to the elliptic curve isogeny class http://www.lmfdb.org/EllipticCurve/2.0.3.1/324.0.18/a/.

The elliptic curve link on the corresponding page http://beta.lmfdb.org/Genus2Curve/Q/2916/a/ on beta is broken because the label changed; it should link to http://beta.lmfdb.org/EllipticCurve/2.0.3.1/324.1/a/.

There are no doubt many more instances of this.  No code change is required, but the genus 2 data will need to change, and the migration of the updated genus 2 data will need to be coordinated with the migration of the updated ecnf data to the production site.

@JohnCremona are the ECNF labels now stable?  Is their any way to provide backward compatibility at the URL level (we should certainly update the genus 2 data regardless, I am thinking of links in published papers that cannot be changed, for example, the link http://beta.lmfdb.org/EllipticCurve/2.0.7.1/[242,136,1]/a/1 that appears as the third link on page 72 of https://doi.org/10.1017/fms.2015.33 is now broken (the curve equation is listed in the paper, so this is not the end of the world).

**Comment by JohnCremona** [comment]
no no no no no
For imaginary quadratic fields:  currently in rapid flux (aka chaos).  I am trying to get the curves collection to match the bianchi newforms collection and it will be a while before that is done.  The fact that there really are newforms which have no curves ("fake curves") and CM curves with no cuspidal newforms does not help.  However the only *labelling* changes have been to use our new standard ideal labels for conductors.
For t.r. fields nothing should have changed except for some more curves being found (very few now missing).

I'm sorry.  I just discovered that in the range 20k-30k over 2.0.8.1 where I had found all (or almost all) the curves before the workshop, I had deleted some files by mistake and will have to re-find them;  and there are some other ranges where I do now have the newforms but not yet the curves.

Until about 2 weeks ago we only had conductor norm up to 10k for each field, so that is what you care about most.  For both URLs and labels all that changed is the conductor label which went from [N,c,d] to N.c.d to N.i where in all cases N is the norm, the first two encode the HNF of the ideal and the last one uses the new standard index.

**Comment by JohnCremona** [comment]
PS You asked for backwards compatibility.  I have functions which convert these conductor labels since I have been using such function all over the place.  It would certainly be possible to add code in ecnf which looks at a label and does 3 different things depending on whether it looks like [N,c,d] or N.c.d or N.i (doing nothing in the latter case).  With consequent redirects.   I guess I owe that to the world.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Thanks! Backward compatibility of URLs would be a wonderful thing.

In terms of the labels stored in the genus 2 collection, I'll wait until the dust settles -- there is absolutely no rush.  With backward compatibility on the links there will be no need to coordinate the migration of the updated collections to the cloud (the ECNF code/data updates should go to prod before the updated genus 2 data, but they don't need to happen at the same time).

**Comment by JohnCremona** [comment]
OK so here is my plan:  converting [N,c,d] to N.c.d is trivial and can be done on the fly.  The second step, from N.c.d to N.i means knowing the field, constructing the ideal, and computing its label.  That certainly could be done on the fly but instead I propose to make a little collection IQF_labels in the database which would have 13100 entries, one for each level/conductor label with norm<=10000 for the 5 fields for which this is relevant.  A one-off computation will populate that and then the conversion only needs to look things up there.
[13100 is the total number of distinct conductor labels for norms under 10000].

**Comment by JohnCremona** [comment]
Step 1 is done (creating of the IQF_labels collection for looking up).  It has 46358 entries since I put in all ideals of norm <= 10000 over the five fields and not only the ones which are conductors.

**Comment by JohnCremona** [comment]
See PR #2137

**Comment by AndrewVSutherland** [comment]
I am going to close this issue and open a new one to update the genus 2 links to use the new labels (which is no longer urgent, thanks to PR #2137, I will wait to do it until you are done with all your ecnf updates)

**Comment by edgarcosta** [comment]
@JohnCremona also, let us know when the tables are in a stable stage, for me to tackle the L-functions over CM fields.
