### ISSUE TITLE
Display of the hecke eigenvalue field 

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2170]
The Hecke eigenvalue field is not displayed as a simple math formula, but one formula per monomial.

For example:
```
<div>\(x^{6} \) \(\mathstrut -\mathstrut  2x^{5} \) \(\mathstrut -\mathstrut  17x^{4} \) \(\mathstrut +\mathstrut  32x^{3} \) \(\mathstrut +\mathstrut  39x^{2} \) \(\mathstrut -\mathstrut  86x \) \(\mathstrut +\mathstrut  25\)</div>
```

**Comment by edgarcosta** [comment]
The issue should be around here:
https://github.com/LMFDB/lmfdb/blob/master/lmfdb/hilbert_modular_forms/hilbert_modular_form.py#L364

**Comment by AndrewVSutherland** [comment]
I'm guessing the reason for this is to allow large polynomials such as the one on  http://www.lmfdb.org/ModularForm/GL2/TotallyReal/6.6.1397493.1/holomorphic/6.6.1397493.1-109.1-a
to wrap rather than forcing a horizontal scroll (which is what will happen if you put it in one math formula).

Why do you consider this an issue?  I think wrapping is definitely preferable, and there is no way to achieve this otherwise (like LaTex, MathJax will not break lines inside a formula).  The function web_latex_split_on_pm that is called in the line you highlighted was implemented precisely for this kind of situation and its use here seems entirely appropriate to me.

**Comment by JohnCremona** [comment]
@AndrewVSutherland is right.  In fact there may be some outstanding issues to make the same change in other similar places.  You can see it in action here: http://beta.lmfdb.org/EllipticCurve/6.6.485125.1/
but not here: http://beta.lmfdb.org/EllipticCurve/6.6.485125.1/1.1/a/4
where both the j-invariant and the Weierstrass equation cause horizontal scrolling, while wrapping might well look better.

**Comment by davidfarmer** [comment]
Closing, because this is a feature that enables all formulas to be displayed/wrapped.

Open a new issue if there is a better way to handle this.

**Comment by edgarcosta** [comment]
This came up because as we were trying copy and paste the polynomials, discussing this with John Jones we created a new issue

See #2171
