### ISSUE TITLE
missing L-functions instances

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2182]
I have noticed that there is only one instance for the L-function  http://www.lmfdb.org/L/EllipticCurve/Q/27/a/ (see http://www.lmfdb.org/api/Lfunctions/instances/?Lhash=903291523394155081) and that the L-function http://www.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/42/2/1/a/0/
is computed on the fly.

Should we add the missing instances?
```
{'Lhash': u'903291523394155081', 'type': ??? , 'url': u'ModularForm/GL2/Q/holomorphic/42/2/1/a/0/'}
```
Should we at some point loop over all isogeny classes of elliptic curves over Q and had the instance associated to the modular form?

Further, regarding elliptic curves over quadratic number fields, when uploading the data for the L-function associated to an elliptic curve for which we have the modular form in the database, should I add the instance for the associated modular form?

Thanks!

**Comment by davidfarmer** [comment]
We need to do all the modular forms L-functions, and do it properly.
There is limited value in just doing some of them.

A possible exception (mentioned by Andy) is to only add those which
are needed for the non-primitive L-functions associated to a degree 4
object which is being put into the database.

I think it is a mistake to add the modular forms L-function which are not
needed for a specific purpose.

I guess the ones with integer coefficients and weight 2 could be done
relatively easily, because we know the identifier of the modular
form.  But if someone has the time to do that, I suggest it would be
better for them to do something else.  (Those will not be used
on home pages, so there is not actually any benefit.  Once all the modular
forms L-functions are in the database, then we will change how the home 
pages are displayed.)

**Comment by edgarcosta** [comment]
Let me practical then, should I add an entry to instances for the Hilbert modular form/Bianchi modular form, if such form exists in the database, when adding the L-function data for an elliptic curve over a quadratic number field?

Later on, I will also add the Hilbert/bianchi modular forms L-functions, however, in many cases we do not have enough Dirichlet coefficients to say something rigorous about the L-function.
(The same will happen for classical modular forms)

**Comment by AndrewVSutherland** [comment]
This issue as been addressed for CMFs and L-functions of elliptic curves and genus 2 curves over Q by #2717, and there is a seperate issue for HMFs/BMFs and Artin reps #2768.
