### ISSUE TITLE
Bianchi modular form n/a

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2247]
A small thing. 

The curve:
http://beta.lmfdb.org/EllipticCurve/2.0.643.1/1.0.1/a/1
points to:
http://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.643.1/1.0.1/a/
which does not exist.

In my recent PR #2246, I have some code to deal with that:
https://github.com/LMFDB/lmfdb/pull/2246/files#diff-d1a9e3a6c6dc6a2981acb082731e0cf5R27

Cheers,
Edgar

**Comment by JohnCremona** [comment]
Sorry about this.  the vast majority of elliptic curves over imaginary quadratic fields which we have are over the five fields for which we have Bianchi data, but there are  a few exceptions (precisely 8 in fact, see http://www.lmfdb.org/EllipticCurve/browse/2/0/) since a few curves with everywhere good reduction were added too.

I'll fix this by only putting the link in when the Bianchi for is there.   We already think about this in the code so that a curve such as http://www.lmfdb.org/EllipticCurve/2.0.11.1/9.1/CMa/1 which has no associated Bianchi __cusp__ form is shown correctly.

**Comment by JohnCremona** [comment]
Sorry @edgarcosta I saw too late that your other PR had a nice function for testing for the existence of a BMF with a given label.  I don't use that here to avoid making this dependent on that.

**Comment by edgarcosta** [comment]
No problem.

**Comment by JohnCremona** [comment]
It would be better to leave this open until #2249 is merged....

**Comment by edgarcosta** [comment]
okidoki
