### ISSUE TITLE
Fix bread crumb for L-functions associated to Elliptic curves over number fields

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2273]
At the moment the `Elliptic Curve` in the bread crumb 
```
 ⌂ → L-functions → Degree 4 → Elliptic curve → 2.2.5.1.31.1.a
```
points to http://beta.lmfdb.org/L/degree2/EllipticCurve/.
Which is clearly wrong :)

There is no http://beta.lmfdb.org/L/degree4/EllipticCurve/, but I am also not sure if we really want to have a page per degree....

**Comment by JohnCremona** [comment]
One suggestion:  instead of having any degree-specific pages /L/degree<d>/EllipticCurve, just have one /L/EllipticCurve.  That could have a general opening paragraph, a more detailed section for degree 2 as now, and possibly more to be added later (if the curves over sextic fields get L-functions one day they will have degree 12).

This would however go against the other scheme we have whereby /L/degree<d> is a page linking to all known sources of degree d L-functions.  So maybe we do need a page per degree (of e.c. L-fns) after all.

**Comment by edgarcosta** [comment]
Alternatively, one could entirely skip that crumb, as it is done in the genus 2 curves:
http://beta.lmfdb.org/L/Genus2Curve/Q/791597/a/

**Comment by JohnCremona** [comment]
This is simply a matter of commenting out line 573 in lfunctions/main.py (which is already tagged FIXME) so I am doing that, hoping that it will not conflict with PR#2369
