### ISSUE TITLE
Plot problem

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#2339]
The plot of this curve  http://www.lmfdb.org/EllipticCurve/Q/24/a/1
is not correct: the 2-torsion point listed in the page is (-11,0) and the plot is crossing the x-axis after 20.
I think it may be a bug in sage (it is not plotting the short Weierstrass equation nor another curve in the isogeny class).

**Comment by davidfarmer** [comment]
The real roots of x^3 - x^2 - 384 x - 2772 are

-11 (exactly)
-10.9706
22.9706

So there is a tiny little (but not empty) "round" component to the
real points on the curve, near the rational point (-11,0).
That is missing from the plot,
but that is the only thing I see wrong with it.

**Comment by nmascot** [comment]
This is exactly the same phenomenon as in  #1547. Sadly, I don't think we can do anything against it.

**Comment by sanni85** [comment]
You are right. I was preparing a talk and I wanted a plot of the curve, the missing component was the thing that I could not understand, it is just a problem of scaling then...

**Comment by edgarcosta** [comment]
@sanni85  Can we close this issue?

The component is there: 
<img width="173" alt="screen shot 2018-01-17 at 11 37 19" src="https://user-images.githubusercontent.com/322822/35054594-e85fe63a-fb7a-11e7-9c7c-0a841e3ec129.png">

**Comment by JohnCremona** [comment]
I agree with @edgarcosta since if you zoom in you can see some blue.  There is little point in adapting Sage's plotting routine since there will be curves for which 2 of the crossing points are even closer together and enlarging the plot to make the compact component visible would just make the other component off the picture.   

For a variation of the problem try http://www.lmfdb.org/EllipticCurve/Q/916/e/1 which had a walk-on part in my book (page 80): the real roots are 
```
sage: EllipticCurve('916b1').division_polynomial(2).roots(RR)
[(-1162.57874285286, 1), (581.289368938371, 1), (581.289373914487, 1)]
```
so two are equal to 5 d.p. and the graph looks singular.  For another where Edgar's microscope comes in handy:  http://www.lmfdb.org/EllipticCurve/Q/1342/b/1
```
sage: EllipticCurve('1342c3').division_polynomial(2).roots(RR)
[(-6252.27639054941, 1), (-6252.27639052338, 1), (12503.3027810728, 1)]
```
This last one was pionted out to me by Elkies (see the footnote, op.cit.).  It is related to the curve having a very skewed period lattice.  (Perhaps we should plot the period lattice?!!)
