### ISSUE TITLE
Missing elliptic curve L-function?

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2346]
From the feedback page:

In reference to http://www.lmfdb.org/L/EllipticCurve/3.3.148.1/61.1/a/ , paweleckrzysztof1@gmail.com says:

Unable to render L-function page due to the following problem(s):
No L-function instance data for "EllipticCurve/3.3.148.1/61.1/a" was found in the database.

==== End of quote

I can see that that url produces the error as described, but if I remove the "L", I get an elliptic curve, and the link to the L-function takes it to a different, and functioning, page.  Probably the first step is to contact the person and ask how they got to that url.

**Comment by jvoight** [comment]
I can get to this link by going to the elliptic curve
  http://www.lmfdb.org/EllipticCurve/3.3.148.1/61.1/a/1
and then clicking "L-function".

Something is not right in handling L-functions here.

Starting at the isogeny class
  http://www.lmfdb.org/EllipticCurve/3.3.148.1/61.1/a/
when I click "L-function" it sends me to the HMF L-function
  http://www.lmfdb.org/L/ModularForm/GL2/TotallyReal/3.3.148.1/holomorphic/3.3.148.1-61.1-a/0/0/
The conductor here is 1336144, so we shouldn't trust much on this page (e.g., it looks like the Riemann hypothesis is false).  Indeed, from the HMF page
  http://www.lmfdb.org/ModularForm/GL2/TotallyReal/3.3.148.1/holomorphic/3.3.148.1-61.1-a
we have the L-function turned off because we did not want to display wrong information.

This L-function is not precomputed, if I understand correctly.  

One possible fix is to decide when we display the non-precomputed L-function, based on the conductor and number of L-coefficients available.  It would be helpful to have mathematical input here.  

Perhaps a better fix would be to always go to the L-function page, but only display data when it is correct, under the same criterion.  (Things like the conductor and the friends links are OK, for example.)

JV

**Comment by edgarcosta** [comment]
I was the one that introduced this bug in #2246.

In short, we need to add a clause to for real field of degree >2
https://github.com/edgarcosta/lmfdb/blob/master/lmfdb/ecnf/WebEllipticCurve.py#L510
In those cases, we should have:
```
self.urls['Lfunction'] = url_for("l_functions.l_function_hmf_page", field=self.field_label, label=self.hmf_label, character='0', number='0')
```
