### ISSUE TITLE
Indicate when underlying code is not available

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2419]
Comment from Steven J Miller,  in response to an article being written by @fredstro 
This comment applies to things like the GL(3) Maass forms:

One of the difficulties in describing what is available is that not all
material is equally documented. For some code is available, for some it is
not. There are a few ways we can handle this, and wanted to see your
preference.

Would you be willing to do the following, which I believe would be valuable
for other readers. It would be making sure that code is available whenever
possible, and when not clearly stating that this is a cutting edge
application and the code is not yet ready for public release.

**Comment by JohnCremona** [comment]
Is the code being referred to the code which was used to compute the data
stored in the database?  I assume so.

This is a good aim.  For some pages the data presented was computed by many
different people and this should always be documented (in the "source"
pages).   But that acknowledgement is not at all the same as providing that
code for others to run.   For example, the code used to compute elliptic
curves over Q is on github but some of the additional data was computed by
other people  (other meaning not me) who sup plied data not code.

John


On 11 Apr 2018 10:09 am, "David W. Farmer" <notifications@github.com> wrote:

Comment from Steven J Miller, in response to an article being written by
@fredstro <https://github.com/fredstro>
This comment applies to things like the GL(3) Maass forms:

One of the difficulties in describing what is available is that not all
material is equally documented. For some code is available, for some it is
not. There are a few ways we can handle this, and wanted to see your
preference.

Would you be willing to do the following, which I believe would be valuable
for other readers. It would be making sure that code is available whenever
possible, and when not clearly stating that this is a cutting edge
application and the code is not yet ready for public release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMFDB/lmfdb/issues/2419>, or mute the thread

**Comment by AndrewVSutherland** [comment]
We have now implemented reliability and source knowls (rcs.rigor.* and rcs.source.*) throughout the LMFDB that provide a mechanism to uniformly address this issue.  If there are concerns with a particular page or set of pages those should be addressed by updating or commenting on the relevant knowls.

Many of the rigor and source knowls are still awaiting review, and some may need further revisions, but we now have an editorial a process in place to ensure that this happens, so I am closing this issue.
