### ISSUE TITLE
Search Galois groups by order

### ISSUE THREAD

**Issue by kedlaya** [LMFDB/lmfdb#2447]
The search results for Galois groups include order as one of the fields. So why not the option to search for Galois groups by order rather than (or in addition to) degree?

**Comment by jwj61** [comment]
Putting it as an addition definitely makes sense.

I thought it would take 5 minutes, but it is a little more complicated because we store the group orders as strings (23! is pretty big).  So, we will need to use an alternate strategy so searching for ranges works.  After switching to postgres, then we can probably safely store the order as an integer, even if we expand the range in terms of degree.

**Comment by kedlaya** [comment]
If waiting until after the postgres conversion would make this easier, then I propose to wait.

**Comment by AndrewVSutherland** [comment]
This was addressed by PR #2473 and is now live on beta.
