### ISSUE TITLE
Beta status in description of knowls

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2495]
Knowls which have beta status have (beta status) added to their descriptions.  If you change the status of the knowl, the (beta status) has to be removed manually.  If you edit such a knowl and leave it as beta, then you can end up with "(beta status) (beta status)" in the description.

It should definitely only add (beta status) at most once, and if it is added automatically, it should probably be removed automatically.

**Comment by JohnCremona** [comment]
That is not what I thought I had implemented!  If so, I'm sorry.  What I thought I had done was only to add the string " (beta status)" to the title displayed, and absolutely not to change the title as stored.

Looking  at the collection knowledge.knowls I find 12 with "beta status" in their title now:
`[u'Birch and Swinnerton-Dyer invariants of an elliptic curve/$\\mathbb{Q}$ (beta status)',
 u'Discriminant of an elliptic curve over $\\Q$ (beta status)',
 u'Geometric isomorphism class of a curve (beta status)',
 u'Modular curve $X_0(50)$ (beta status)',
 u'Discriminant of a Weierstrass equation (beta status) (beta status) (beta status)',
 u'Borel case (beta status)',
 u'Endomorphism ring (beta status)',
 u'Modular curve $X_1(13)$ (beta status)',
 u'C277 (beta status) (beta status)',
 u'Modular curve $X_0(37)$ (beta status)',
 u'L-function of an abelian variety over $\\mathbb{Q}$ (beta status)',
 u'Birch and Swinnerton-Dyer conjecture (beta status)']
`
and of course we can correct these but it is also urgent to stop it happening any more.  I am mystified by there not being more since I thought that the knowl reviewing I did 2-3 weeks ago was with this "beta status" code.

Here is my diagnosis: in lmfdb/knowledge/knowl.py there are two function called "title".  One (from line 300) is a "property" and returns the title string, with " (beta status)" appended depending on some condition.  This one is certainly not supposed to change anything which is stored.  BUT there is a second function title() from line 314 which stores into the db the current strong returned by the first function.  It is the interplay between these two which is having the unforeseen side-effects.

The simplest fix would be to undo my changes, i.e. delete lines 310-311, and then manually correct the dozen knowls above.  I am going to do this right away.

**Comment by JohnCremona** [comment]
Fixed (effective though temporary)  in #2496 already pushed to beta and prod (so live in 6 minutes).

**Comment by JohnCremona** [comment]
Fix is now live.  I also manually removed the extra title stuff from all those which had it, as you can from 
http://beta.lmfdb.org/knowledge/?search=beta
which has 5 hits but in all cases it's for a valid reason.

**Comment by jwj61** [comment]
Thanks.  For future reference, it seemed to happened whenever one edited a knowl with beta status, and then saved it without changing the status.
