### ISSUE TITLE
Number fields should show number of roots of unity

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#2527]
Number field pages give the unit rank and a torsion generator but do not say what the order of that generator is.  That would be helpful.  The simplest way would be to insert "(order 6)" or similar after the torsion generator.
It is not clear to me whether or not the units of finite order are stored.  I think not. So the fact that their number is not stored wither is not an issue!

**Comment by jwj61** [comment]
Addressed in pull request #2528.  

It is computed on the fly.  For the time being, it does not slow things down since the same gp command which computes the root of unity also returns its order.

Yes, it could be stored in the database.  For the moment, it does not seem urgent.  As a test, I ran all of the degree 18 fields in gp through this command, and the root of unity command takes basically no time (3-20 ms).  This comes after the number field has been initialized, and that is a little longer (around 40ms), but is always this fast since we supply the integral basis to nfinit.
