### ISSUE TITLE
Evaluate whether to switch to katex from mathjax

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2561]
From William Stein:
```
Katex covers about 99.9% of functionality now. 
(When we switched cocalc, one person pointed
out some spacing changes, and it turned out katex
was right and mathjax was wrong.)

Katex is usually about 25x - 100x faster to render
than mathjax, and it's done synchronously.
Switching would make LMDB feel massively more
responsive, completely getting rid of the
mangled-for-a-moment look you get with mathjax...
```
See https://github.com/Khan/KaTeX.

**Comment by davidfarmer** [comment]
What is the expected speedup when MathJax 3 comes out?

**Comment by AndrewVSutherland** [comment]
I believe this comparison is with MathJax 2.7.2, we should do a comparison with the MathJax v3 beta, which is available at

https://github.com/mathjax/mathjax-v3/tree/beta

We should do a comparison using some of our own page between katex and mathjax v3.

We should look at this soon.  I can't think of any other change that has the potential to dramatically improve the performance of every section of the LMFDB.  With the switch to postgres mathjax rendering is now the bottleneck on most pages, and in many cases it takes several seconds.  Our goal should be to have every LMFDB page load in under 400ms.

**Comment by haraldschilly** [comment]
@AndrewVSutherland I think the only real question here is if all formula processing is done on the server (and not in the web browser). KaTeX should be able to do this quickly, and on top of that there are certainly possibilities for server side caching. Maybe an interesting for step could just be a little bit of hacking how the templating system works in order to render the formulas. If that looks ok, work out how to do this performantly.

**Comment by alexjbest** [comment]
I guess this should be closed now as we switched to katex!
