### ISSUE TITLE
Knowls inherit styles

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#260]
Knowls inherit styles from surrounding divs.  So if the div has a margin or text-align right, then the content of the knowl is shown that way.  Can we stop this?

**Comment by haraldschilly** [comment]
No, there is no general way. Either the surrounding CSS definitions need to be more precise (depends on what is really going on) or those inherited definitions need to be overwritten by some additional CSS definitions for knowls.

So, it depends a bit on a specific case, because if it is caused by some bad CSS code in the surrounding page, I would argue to fix this because it could lead to other problems as well. If it is something "stupidly simple", then overruling this in the general knowl definitions might be best.
