### ISSUE TITLE
Missing integral points

### ISSUE THREAD

**Issue by jbalakrishnan** [LMFDB/lmfdb#2600]
There's a Sage bug for integral points on elliptic curves that's exposed for the elliptic curve [2082.a1](http://www.lmfdb.org/EllipticCurve/Q/2082/a/1): in addition to the points listed already, there is also the point P = (507525709, 11433453531221) (and -P).

**Comment by JohnCremona** [comment]
On 25 Aug 2018 11:20 am, "Jennifer Balakrishnan" <notifications@github.com>
wrote:

There's a Sage bug for integral points on elliptic curves that's exposed
for the elliptic curve 2082.a1
<http://www.lmfdb.org/EllipticCurve/Q/2082/a/1>: in addition to the points
listed already, there are also the points (507525709, \pm 11433453531221).

Yes and unfortunately there are many such examples. On one hand we need to
admit this known problem on every curve's home page. Also,I have long had
on my to-d0 list to finish the sage ticket which aims to fix the problem
with the implementation.

iving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMFDB/lmfdb/issues/2600>, or mute the thread

**Comment by JohnCremona** [comment]
I have done this before, when my database was smaller, so have code to do the computation in both Sage and Magma and compare.  It would be easy to run that again.  It used to be the case that Magma did not use the stored information it had (since it has the whole database installed as standard) about the generators, which made comparison of timings hard, but that is no longer the case (and not the issue here).

Here is what would be most useful: run such a script on all the curves.  Record those for which Magma finds more points (for later debugging).  If there are any the other way round, record those too of course and file a bug report with Magma.  Either way, update the files at https://github.com/JohnCremona/ecdata/tree/master/intpts  and upload the new data to the LMFDB.

I have a Sage branch which fixes the known bugs but it has been lying around for ages since it uses a certain bound I am sure about but cannot prove.

**Comment by JohnCremona** [comment]
I have written a script to recompute all the integral points data using Magma and have started to run it.  It will take quite a long time.

**Comment by JohnCremona** [comment]
Progress report: after some experimentation it seems that the fastest way to do this is as follows.  Magma's IntegralPoints function can be given a MordellWeil basis as optional parameter and then works a lot faster.  Even if the curve is constructed from its label, the MW basis is not preloaded.  (If there is a way to ensure that the curve is constructed from the database in such a way that the MW basis is preloaded, I do not know how to do it).  Now Sage + optional curve database will preload the generators when a curve is constructed from its label.  So the script I have written runs through the curves in Sage, sends the a-invariants and generators to Magma to do the work and recovers the integral points (x-coordinates), outputting to a new file in the same format as the old intpts.* files.

This is fast and will finish in reasonable time.  For conductors to 10000 there are 4 curves with missing integral points (one each).

**Comment by JohnCremona** [comment]
Altogether there were only 207 curves for which Magma found more integral points -- I ran them all.  It did not take so long (40 threads of about an hour each running 10000 conductors each.)  I have updated the raw data files in my ecdata repository, and uploaded the new sets of points as you can see at http://beta.lmfdb.org/EllipticCurve/Q/2082/a/1

I also updated the knowl http://beta.lmfdb.org/knowledge/show/dq.ec.source to acknowledge that Magma was also used.

Hence I claim that this Issue can be closed!
