### ISSUE TITLE
L-functions of symmetric squares don't have negative zero data

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2643]
Contrary to other L-functions where imaginary parts of both positive and negative zeroes appear on the L-function page, the pages for L-functions of symmetric squares only display positive zeroes <http://www.lmfdb.xyz/L/SymmetricPower/2/EllipticCurve/Q/11/a/>, nothing major, just a little weird.

**Comment by davidfarmer** [comment]
That data is computed on the fly, so it is not worth making changes to
the page because it will be thrown away once the data is precomputed
and stored in the database.  (At which time it will follow the same
template as elliptic curves and genus 2 curves.)

I also don't recall if we reached consensus about showing both
the positive and negative zeros when the function was even.
Maybe we decided to show both because of possible confusion
when there are zeros at the central point?  This is irrelevant
for the L-function computed on the fly because it will completely
miss an order 2 zero.

Whenever you see an L-function page with
     (not yet available) 
written under the "arithmetic" button at the top, then it is hardly
worth making an issue because that page will be completely redone
once the L-functions are properly precomputed  (unless it is really
bad and we absolutely need to fix or hide it).
