### ISSUE TITLE
Maass eigenvalues shifted 

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2647]
Some forms display the eigenvalues shifted, e.g.:
http://www.lmfdb.org/ModularForm/GL2/Q/Maass/54104e8dacf756699fe0830c
vs
http://www.lmfdb.org/L/ModularForm/GL2/Q/Maass/54104e8dacf756699fe0830c/

**Comment by davidfarmer** [comment]
If the form has weight 0 and is even, then the Gamma factors are
Gamma_R(s \pm i R), and if it is odd then Gamma_R(s + 1 \pm i R).

If the weight is 1, then the concept of even/odd does not apply,
you get
     Gamma_R(s \pm i R) Gamma_R(s + 1 \mp i R) ,
but we don't have any of those in the LMFDB yet.

If that is what you refer to, then probably everything is right
(except that these facts need to be explained somewhere).

**Comment by edgarcosta** [comment]
I should have been cleared.

I'm referring to the fact that in the Maass Form page we display,
c_0 = 1
c_1 = 0.7071067
c_2 = 1.1982127
c_3 = 0.5
c_4 = -0.2131064

while, I believe we wanted to display:
c_1 = 1
c_2 = 0.7071067
c_3 = 1.1982127
c_4 = 0.5
c_5 = -0.2131064

**Comment by AndrewVSutherland** [comment]
Looking at the level 2 forms I think the issue arises when the coefficients are stored in the mwf_forms table, see https://www.lmfdb.org/api/mwf_forms/?Level=2,  What's weird is that the data looks consistent with many of the level 1 forms that have coefficients in mwf_forms, see https://www.lmfdb.org/api/mwf_forms/?Level=1, and these forms appear to display correctly.

@rbommel You looked at the relevant code most recently I think, any ideas?

**Comment by rbommel** [comment]
Yes, my code couldn't find these coefficients due to a rounding error. I fixed this now and made a pull request for that. For some reason the coefficients of this particular form seemed to be stored multiple times in the database. As usual, I have no idea why it is like this. If you download the coefficients, you just get the raw data which I retrieve from the database.

**Comment by AndrewVSutherland** [comment]
@rbommel But does explain why the coefficient display on http://www.lmfdb.org/ModularForm/GL2/Q/Maass/54104e8dacf756699fe0830c is shifted by 1?  On your PR they still look shifted.

Also, it looks like your PR has a merge conflict.

**Comment by rbommel** [comment]
Strange, when I run it here, I get 'c(0) = 0' now. The reason why it is shifted, is because the coefficients are stored wrongly in mwf_forms apparently (if we believe @edgarcosta). In mwf_coeffs the first coefficient is a 0.

Yes, it told me about this conflict, but Github told me not to worry about it, so I didn't.

**Comment by AndrewVSutherland** [comment]
@rbommel Never mind, you are right it is fixed in your PR (I must have checkout out the wrong branch).

The merge conflict needs to be resolved before we can merge your PR, and I'd rather not do that by hand.  Given how small and localized the change is, I might suggest getting your master up to date (pull from upstream), creating a new branch, and re implementing your more recent edits (possibly by copy and paste, but you'll want to be careful -- there is a reason github is complaining, possibly because a change you made in your last PR to the same section of code is not reflected in this PR).

**Comment by rbommel** [comment]
Okay, somebody seems to have added some parenthesis around a print statement. I just left them there. Should be fine now.

**Comment by AndrewVSutherland** [comment]
Fixed via #3536, thanks @rbommel !

**Comment by edgarcosta** [comment]
I know very little about mass forms.
But given that c(p) are Dirichlet coefficients, that makes me expect c(0) =
0.

**Comment by davidfarmer** [comment]
Similar to the holomorphic case:  newforms have constant term 0.
Eisenstein series have a nonzero constant term (at at least one
cusp).

We only want cusp forms (in particular, newforms) in the LMFDB.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Did you notice any pages where c(0) != 0?  In most cases (and certainly in the case of http://www.lmfdb.org/ModularForm/GL2/Q/Maass/54104e8dacf756699fe0830c), c(0) is not even stored.  Or are you suggesting c(0) should not be displayed at all?  (if the latter I agree, but I don't think we should be investing any time any energy on improving the current UI, since the plan is to completely replace it, my only goal for 1.1.1 is to fix or hide anything that simply does not work or is mathematically incorrect (#2645, #2576, #2647, #2688, #2950, #3372 all fall into this category).

Having said that, if it is easy to do and someone is motivated to do it, I would be happy to see the c(0)=0 line go away.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, just confirming that c(0) = 0 is what I expect, instead of waht we displayed before http://prod.lmfdb.xyz/ModularForm/GL2/Q/Maass/54104e8dacf756699fe0830c
