### ISSUE TITLE
Duplicated related objects in Genus 2 curves

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2652]
At the moment in related objects, we display the curves and the isogeny classes.
We should pick if we want to list the isogeny class or the curve in related objects.

http://prod.lmfdb.xyz/Genus2Curve/Q/2916/b/11664/1
vs
http://beta.lmfdb.org/Genus2Curve/Q/2916/b/11664/1

<strike>Picking the two to stay is related to #2651</strike>

**Comment by AndrewVSutherland** [comment]
We should continue to show the curves (there are rational maps from the Jacobian to each of these elliptic curves, but this is not true of other elliptic curves in the isogeny class).  I don't think we need to list the isogeny classes in addition.

**Comment by AndrewVSutherland** [comment]
To test, compare:

http://beta.lmfdb.org/Genus2Curve/Q/2916/b/11664/1
http://127.0.0.1:37777/Genus2Curve/Q/2916/b/11664/1

and note that with the update only the elliptic curve friends are listed in related objects (rather than both the elliptic curve and its isogeny class) as was the case pre-postgres:

http://prod.lmfdb.xyz/Genus2Curve/Q/2916/b/11664/1

**Comment by edgarcosta** [comment]
Closed via #2879
