### ISSUE TITLE
Elliptic curve search failed

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#2690]
From the feedback page for http://www.lmfdb.org/EllipticCurve/Q/?rank=2 :  

I clicked on a link to see curves of rank 2, and it failed.

Feedback was left by tobygee@fastmail.com

**Comment by AndrewVSutherland** [comment]
This query works fine on postgres (both web and dev). see

http://web.lmfdb.xyz/EllipticCurve/Q/?rank=2&surj_quantifier=include&count=100

 I'm not sure why it is so slow on lmfdb.org (which is still pointing to the mongo db version), since there is an index on rank.

Given that we will be redirecting lmfdb.org to the postgres version at web.lmfdb.xyz in January, I suggest referring Toby to web.lmfdb.xyz and letting him now that we will be switching over to this server in the near future.  I don't think it is worth spending time trying to diagnose and fix this issue on the mongo db version.

**Comment by JohnCremona** [comment]
The original search worked fine for me -- such a simple and standard thing has surely been tried many times before.
I agree with the plan of action.  Has anyone emailed Toby yet?

**Comment by JohnCremona** [comment]
Ok I will

**Comment by AndrewVSutherland** [comment]
The search http://www.lmfdb.org/EllipticCurve/Q/?rank=2 now works without any problem as a result to switching www.lmfdb.org to the postgres database after #2717.
