### ISSUE TITLE
Use new statistics framework across the LMFDB

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#2755]
Classical modular forms use a new statistics framework, which combines statistics with counts for search results, and makes it easy to create statistics pages.  Statistics pages in other sections of the LMFDB should be rewritten to use the new framework.

The following tables use old statistics methods (grep for `get_oldstat`)

* Higher genus curves with automorphisms
* Hilbert modular forms
* Lattices
* Hecke algebras

The following tables already use the new methods:
* Classical modular forms
* Belyi maps
* Genus 2 curves
* Elliptic curves over Q
* Elliptic curves over number fields
* Number fields

**Comment by roed314** [comment]
The first step is to improve the documentation of the new statistics functionality.  I'll be working on that over the next week.

**Comment by roed314** [comment]
One improvement to the framework that might be good to do with this is to create links to dynamics stats from each entry in the curated stats

**Comment by JohnCremona** [comment]
As far as I can see the new all-purpose stats functionality is not appropriate for some of the uses to which the old auxiliary collections, now names "oldstats", are used for.  In nfcurves and bmfs and hmfs we need to have a record of which base fields exist, per degree and per signature and for each of these subsets (per field, per degree, per signature) have number of curves, number of classes and maximum conductor/level norm.  These are more entries as well, for example in nfcurves we have list of all the torsion structures and that is used to populate the drop-down menu on the search page.  This last one could be done by having a stats entry on torsion which would also count how many times each structure appeared, so that would serve two purposes.

It is very easy to write a function for nfcurves which collects the data needed to be stored in a table just like the oldstats one -- I have such a function -- but as long as oldstats are treated as second-class objects which the new interface does not allow writing to except by raw SQL calls this will be unnecessarily hard to implement.  For that reason the ecnf web pages currently show the wrong number of curves since I recently added 4 but cannot yet update the oldstats table easily.

I look forward to being shown that I am wrong and that the rigid counts/stats system being proposed as one-size-fits-all can handle  such cases too.

**Comment by JohnCremona** [comment]
I am still waiting for some documentation.  It is currently completely opaque how the functions add_stat, add_bucketed_count etc are supposed to be used.  Some of the parameters are not mentioned in the docstring.  Many examples are required.

I also think that for every table whose stats are present and necessary for the correct appearance of the website, there should be a script *in the repository* (and not just on someone's personal computer) which will recompute the relevant stats and counts from scratch.  These would also serve as models.

We also need tools to see what is actually stored in the counts and stats tables: I  tried to use general-purpose tolls for examining mysql databases but that is not very easy.  For example, ec_curves currently has 339 rows in stats and 1949 rows in counts, and I have no idea whether any of those are needed.

Until this system is made usable it will not be used and incorrect counts will remain visible (as at http://beta.lmfdb.org/EllipticCurve/ where the number of curves is wrong -- of course fixing that one display is by counting on the fly).

**Comment by JohnCremona** [comment]
Despite that grumble I did just make a PR #2907 which works for elliptic curves over Q.

**Comment by AndrewVSutherland** [comment]
Just to record some of the discussions on this issue over the past week, there is some additional work that needs to be done to both to document the interface to the statistics framework and to ensure that it meets the needs of all our developers.

One important point is that we should clearly separate features related to maintenance of statistics and displaying statistics.  Using the new framework for maintaining statistics ensures that they can be efficiently kept up to date, and that the statistics on both beta and production (which may differ at times) are maintained correctly.  Using the new display features may make it easier to implement new statistics page, and to allow users to customize statistics queries as they now can on CMFs, but these features are not as essential as the maintenance features and should be regarded as optional.

**Comment by JohnCremona** [comment]
I just updated the top comment box of this issue since 3 of the 7 no longer use any oldstat information.

**Comment by AndrewVSutherland** [comment]
See #4113 for a problem in the BMF stats.

**Comment by AndrewVSutherland** [comment]
I think this is now done except fo BMF and Dirichlet characters where there are dependencies on other issues (for BMF we just need to fix #4413, for Dirichlet characters we really should finish the work Alex Best started in #4110 to address #3983 and #3994 before adding stats).

**Comment by AndrewVSutherland** [comment]
I will close this as soon as the Dirichlet stats are running on beta.
