### ISSUE TITLE
Formatting of central value

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2773]
L(\chi, 1/2) is wrongly formatted
http://www.lmfdb.org/L/Character/Dirichlet/971/870/

**Comment by tomgrubbmath** [comment]
This seems to track back to lmfdb/utils/utilities.py , where the display_complex() function occasionally spits out a number in scientific notation. There is a sloppy way around this by just adding a wrapper function into lmfdb/lfunctions/Lfunctionutilities.py which I have implemented (using string manipulation to replace the letter "e" with the appropriate tex code for "x10^()") but I've held off on a pull request in case there is a cleaner/more systematic way that you'd prefer to fix this. 

(Also, L(\chi, 1 ) is not in dollar signs for math formatting, so that should go in whatever fix is ultimately adapted)

**Comment by davidfarmer** [comment]
I think it is reasonable to do those string manipulations, looking for the "e".

Is the central value unusually small?  The answer involves looking at how many
Dirichlet L-functions have smaller conductor.  If it is unusually small, it might be
worth putting on some list of interesting examples.

**Comment by edgarcosta** [comment]
This L-function is extremely special as its first zero is really close to
zero :)

**Comment by davidfarmer** [comment]
Yes, but my question is whether it is surprisingly close
to zero.  It is a unitary family, so randomly you will
occasionally get zeros close to the critical point.

**Comment by edgarcosta** [comment]
@tomgrubbmath, I think your workaround makes sense
