### ISSUE TITLE
Colors on Dir Char and EC Isogeny Class table

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2883]
There are three colors in the cells of Dirichlet character tables, such as

http://beta.lmfdb.org/Character/Dirichlet/?modbrowse=21-40

The dark color is too dark for the numbers in those cells.  (I realize it is
the same as occurs in the main headings on the sidebar, but in the sidebar
the letters are bold.)

I suggest replacing the dark background by what is currently the light
background, and making the light background white.  The very slight
parity difference indicated by the light and white background is of
minimal value (to me), so just two background colors in that table
should be fine.

Another shortcoming with that table is that if you show all characters
(meaning, both the primitive and imprimitive boxes are checked)
then it is not easy to tell which are which.  When you hover over the
word imprimitive, then that background is a reasonable way to do it.
But that disappears when you stop hovering.  I would be okay with that
background appearing always.  The hovering over Primitive is not
useful, and it can be eliminated if the imprimitive always have a background.

It may seem odd to highlight the imprimitive, because those are less
interesting.  But they are hidden by default and only appear when the
user asks for them, so it makes sense to highlight what the user asked for
 (which is what I just did, which led me to notice these issues).

**Comment by davidfarmer** [comment]
The dark color also occurs on individual character pages:

http://beta.lmfdb.org/Character/Dirichlet/27/4

**Comment by AndrewVSutherland** [comment]
Given that we are changing the color scheme in 1.1, it makes sense to address this now (and it should not be hard to do).  I agree the colors are too dark.  We should use the lighter background color, as on http://beta.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/?search_type=SpaceDimensions, for example.

**Comment by JohnCremona** [comment]
To me all those colours on the character pages look fine.  What definitely *is* too dark is the shading (background colour) of on line in a table such as http://beta.lmfdb.org/EllipticCurve/Q/11/a/ (to "highlight" the optimal curve).  The colour here is 555555 and is much too dark, making the text unreadable. To me.

**Comment by AndrewVSutherland** [comment]
Wow, that is a bad.  Let's include fixing it in this issue (even if there are two PRs, it's really the same issue, with the color scheme change we need to take a close look at all the pages and fix any problems we find).

**Comment by JohnCremona** [comment]
Agreed -- the issue really is "some of the components for this colour scheme needs adjusting".
@roed314 : would it be possible to have a test page which shows all the different elements of a colour scheme?  Something one could have a quick look at when choosing one of the different colour schemes?  There might even be room for it to appear in a frame at the bottom of the users/myself page where the colour choices are, in such a way that clicking on any of the choices changes how that frame appears.

**Comment by roed314** [comment]
I've switched the dark grey to a light grey and modified the character table to just be an alternating grid of white and light blue.  I didn't change the hover behavior, but I did change the imprimitive text color to black, which I think helps enough.

@JohnCremona I thought about trying to do a preview feature when changing colors.  The issue is that there are dozens of colors in play (which are paired in different ways on different pages), so I couldn't think of a reasonable way to do it.  I tried having it rerender the current page when you hovered over a color option, but that was sufficiently slow that the flicker was extremely annoying.  I settled on just changing it, since you can always change back.  I didn't reckon with the delay in the change showing up on beta, which I still don't fully understand (presumably it's some sort of gunicorn caching thing).  In the end, I think the right solution is for us to click through to various pages and see how they look, rather than trying to add a preview.

**Comment by JohnCremona** [comment]
@roed314 OK thanks for trying.  It is all too easy to suggest new features when someone else is going to be doing the work.

You used the past tense but the current master branch still shows the old behaviour, I think.

**Comment by JohnCremona** [comment]
See my comments on #2899: I am happy with the change to the isogeny class display, and the characters look OK to me but @davidfarmer should look too.
