### ISSUE TITLE
dq to rcs

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#2946]
Rename dq knowls according to the convention:
  rcs.rigor.xyz     (where xyz = hmf, ec, ecnf, etc.)
  rcs.cande.xyz
  rcs.source.xyz

**Comment by roed314** [comment]
The following renames don't work since the new knowl already exists.  What should happen for each of these?

[dq.artin.extent](http://beta.lmfdb.org/knowledge/show/dq.artin.extent) -> [rcs.cande.artin](http://beta.lmfdb.org/knowledge/show/rcs.cande.artin)
[dq.character.dirichlet.extent](http://beta.lmfdb.org/knowledge/show/dq.character.dirichlet.extent) -> [rcs.cande.character.dirichlet](http://beta.lmfdb.org/knowledge/show/rcs.cande.character.dirichlet)
[dq.gg.extent](http://beta.lmfdb.org/knowledge/show/dq.gg.extent) -> [rcs.cande.gg](http://beta.lmfdb.org/knowledge/show/rcs.cande.gg)
[dq.lf.extent](http://beta.lmfdb.org/knowledge/show/dq.lf.extent) -> [rcs.cande.lf](http://beta.lmfdb.org/knowledge/show/rcs.cande.lf)
[dq.nf.extent](http://beta.lmfdb.org/knowledge/show/dq.nf.extent) -> [rcs.cande.nf](http://beta.lmfdb.org/knowledge/show/rcs.cande.nf)
[dq.zeros.zeta.extent](http://beta.lmfdb.org/knowledge/show/dq.zeros.zeta.extent) -> [rcs.cande.zeros.zeta](http://beta.lmfdb.org/knowledge/show/rcs.cande.zeros.zeta)

**Comment by jwj61** [comment]
With artin, lf, gg, and nf, the dq knowl is used for one thing, and the cande for something else.  So, don't change them.

It looks like rcs.cande.character.dirichlet  should be rcs.source.character.dirichlet and dq.character.dirichlet.extent should be rcs.cande.character.dirichlet .

**Comment by AndrewVSutherland** [comment]
I think the dq.artin/gg/lf/nf.extent knowls should be renamed to artin/gg/lf/nf.extent (i.e. remove the dq prefix), and I agree that the Dirichlet character knowls should be renamed as @jwj61 suggests.

**Comment by AndrewVSutherland** [comment]
The rcs.cande.character.dirichlet knowl was renamed to rcs.source.character.dirichlet in PR #3042.

**Comment by jwj61** [comment]
Reasonable change for artin/gg/lf/nf

**Comment by jwj61** [comment]
I started the process.  In this pass, I will also rename the knowl for gap numbers of small groups (currently under top level curve).

**Comment by jwj61** [comment]
These have all been renamed.
