### ISSUE TITLE
not-equal sign rendering as equal sign on Safari

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#2953]
As reported by Mike Bennett, using any math mode command for not equal, including "\ne", "\neq", "\not =" will render as "=" on Safari.

To see an example run Safari (on a mac or ipad), go to any elliptic curve page (e.g. http://www.lmfdb.org/EllipticCurve/Q/11/a/2) and click on the discriminant knowl, where you will $\Delta \ne 0$ rendered as $\Delta = 0$.

**Comment by alexjbest** [comment]
@AndrewVSutherland I assume this is #2798 again, see the links there.
It seems this is a recurring issue for them, but I think https://github.com/KaTeX/KaTeX/commit/ff5ebea681c0710805c32f62e7efe96c1b432938 fixes this. Note that this has been added to master since the last official katex release. So we can wait for release 0.10.2 (or whatever) and upgrade when that comes out to fix this.

Alternatively if we want to get these sorts of issues seen to faster we could start building our own KaTeX from master and serve that rather than loading from a CDN?

**Comment by AndrewVSutherland** [comment]
@alexjbest In general I think we can live with minor annoyances (e.g a slash not appearing in the right place on some browsers), but a rendering problem that produces perfectly rendered but false mathematical output is not something we can live with, at least not without warning users about it, which is why I tagged this issue for Release 1.1 (which effectively means May 1).  If we can't fix it I think we will need to add a warning message that appears when the website is accessed via Safari.

**Comment by alexjbest** [comment]
@AndrewVSutherland I completely agree, its hard to think of a worse bug for a math renderer to have (that still renders anything). I am amazed they haven't done a new hotfix release for this.

I have just verified that building the latest KaTeX from source (on my laptop for now). And hosting it from the static folder fixes this bug on Safari.

I have made a PR for this #2954, up to you if/when you want to merge it, but its there if the 1.1 deadline is looming over you.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, could we merge `master` to `dev` and posteriorly, after checking that we are all happy, to `web` so we can close this issue?

**Comment by AndrewVSutherland** [comment]
Done -- let's hold off merging other PRs to master until we get this on web (or decide we don't want to).

**Comment by AndrewVSutherland** [comment]
This is now fixed on www.lmfdb.org, closing.
