### ISSUE TITLE
Some ECNFs not reporting base change correctly

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#2960]
Some elliptic curves over number fields, e.g. http://www.lmfdb.org/EllipticCurve/5.5.14641.1/11.1/a/3 are base changes but are claiming not to be at the bottom of the page.

This seems to be a data issue, but when I try and rerun the relevant import script https://github.com/LMFDB/lmfdb/blob/master/scripts/ecnf/import_ecnf_data.py manually on line 1 of https://github.com/JohnCremona/ecnf-data/blob/master/quintics/curves.5.5.14641.1 it looks like it works fine.

Maybe the data just needs to be reloaded since https://github.com/JohnCremona/ecnf-data/commit/3f34e3b4c98fcd011bf771f0dec3768a2c45d83c ? and this field is the only problem one?

**Comment by JohnCremona** [comment]
I will look into this. The test for bc is done at upload time and I think it is correct (I wrote the sage function for this). What is stored is a list of the labels of the curves over Q of which the curve is a bc, with the empty list for non-bc curves.

**Comment by JohnCremona** [comment]
I have started going through these systematically.  I have already found not-quite-right data for the 4 recently added curves over 2.0.3.1:
Bad base-change data for 2.0.3.1-113556.2-a1: database has {} instead of []
Bad base-change data for 2.0.3.1-116364.1-a1: database has {} instead of []
Bad base-change data for 2.0.3.1-146716.4-a1: database has {} instead of []
Bad base-change data for 2.0.3.1-146716.4-b1: database has {} instead of []

I cannot see from the upload script why it should store an empty list (of strings) in this way, but I'll make sure that the base_change column is stored correctly when I get to the data which we know is wrong (at least for that quintic field).  Currently still working through the quadratics.

**Comment by JohnCremona** [comment]
Update: 

Degree 3: 57 curves over 6 cubic fields are missing base_change data (i.e. they are bc but the database says not).  The fields are 3.3.d.1 for d = 1425, 1620, 1940, 1944, 564 and 756.

Degree 4: 4 curves over 4.4.13068.1 incorrectly not flagged as b.c.

Degree 5: 12 curves over 5.5.14641 incorrect.

Degree 6: 115 curves over 11 fields incorrect.

I will correct the data tomorrow.

Incidentally, it is worth noting how these errors almost certainly came to be, given that the test of base-change is not so hard and has been in Sage for a long time (and was written by me for this very purpose).  The test for Q-curves is harder and is *not* done on the fly during upload; but I originally had that test wrong (roughly, I did not take into account that the isogenies between the Galois conjugates need not be defined over the base field; and other subtleties when the base field is not itself Galois).  The raw data for upload had a True/False field for Q-curve, and *only* tested for base-change when the flag was True.  So if there were curves which were base-change but not correctly labelled as Q-curves, they would end up in the database with no base-changes listed.

**Comment by JohnCremona** [comment]
These have all now been fixed.

**Comment by AndrewVSutherland** [comment]
Great, I will copy the table over to the production database.

**Comment by AndrewVSutherland** [comment]
The new data is now in production and I can confirm that http://www.lmfdb.org/EllipticCurve/5.5.14641.1/11.1/a/3 is now correctly identified as a base change.
