### ISSUE TITLE
List torsion structure instead of torsion order

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#2977]
When displaying search results for elliptic curves over Q we display torsion order.
I believe it would be much more helpful to display the torsion structure instead.
The same holds for the isogeny class pages.

**Comment by JohnCremona** [comment]
Would we show this as a list of invariants (of length 0 1 or 2) ?   Or in latex?

**Comment by davidfarmer** [comment]
I find it tedious to see it written as: trivial, or  Z/10Z or
Z/2 Z \times Z/ 3 Z.

I suggest those should be written as: "1" or "10" or "2 \cdot 3".
(Which could be in LaTeX or with the "middot" html character.

It could still be labeled as "Torsion order", but shown
in factored form.

My suggestion involves not using the notation in the
Torsion subgroup/Torsion structure knowl:
http://beta.lmfdb.org/knowledge/show/ec.torsion_subgroup

If that knowl was expanded to allow the structure to also be
written as a \cdot product, then maybe everyone would be happy?

**Comment by AndrewVSutherland** [comment]
We should use invariants, as we do elsewhere in the LMFDB, e.g. for class groups of number fields and torsion subgroups of Jacobians of genus 2 curves.  We already have parsing functions for these, and we already display them in search results for number fields.

Recall that the invariants of a finite abelian group are the unique list of integers [n_1,...,n_r] with n_i dividing n_{i+1} and r the size of a minimal set of generators.  The trivial group is the empty list [].

**Comment by davidfarmer** [comment]
If you want to show the group instead of the order of the group,
then I think Z/2 Z  is better than [2].  The former is immediately
understood by anyone capable of understanding it (even if they did not
already know that "Torsion" refers to a group).  The latter requires
opening a knowl.

I'm just affirming the choice on the genus 2 curves pages:

http://beta.lmfdb.org/Genus2Curve/Q/295/a/295/2

Perhaps if we are discussing entries in a column of a table,
my previous comment about Z/2 Z looking tedious, would apply.
(And I still prefer my suggestion that what is listed is the
order, and it is shown as a number or the product of two numbers.)

**Comment by AndrewVSutherland** [comment]
@davidfarmer Sorry, perhaps I misunderstood, but I thought this issue was entirely about what to display in the search results column (for displaying on the home page of an object, I completely agree we should display finite abelian groups as products of Z/nZ's).   I was suggesting that we should do what is already done on number field search results, see

http://beta.lmfdb.org/NumberField/?start=0&class_number=4-12

for example,   Mostly I was trying to discourage the idea of inventing a new compact notation, which is what I think you were proposing.

**Comment by JohnCremona** [comment]
I agree: no change on a full home page where we display groups properly as Z/3Z etc, but in a search result table we can use the list notation.

**Comment by JohnCremona** [comment]
Done.

**Comment by JohnCremona** [comment]
Reopening since (for example) https://beta.lmfdb.org/EllipticCurve/Q/?conductor=400000-400100 shows the integers in the torsion structure as strings with quotes and even the unicode u symbol.  It seems that this is the case for conductors > 400000 so is some artifact of the data upload after the mongo-postgresql switch.  Note also that
'''
sage: db.ec_curves.distinct('torsion_structure')
[[],
 [u'12'],
 [u'2'],
 [u'3'],
 [u'4'],
 [u'5'],
 [u'6'],
 [u'7'],
 [u'8'],
 [u'9'],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [12],
 [u'2', u'2'],
 [u'2', u'4'],
 [u'2', u'6'],
 [2, 2],
 [2, 4],
 [2, 6],
 [2, 8]]
'''
A simple rewrite will do the trick.  Can @vishalarul  or someone else do this?

**Comment by jvoight** [comment]
The curve 
  https://www.lmfdb.org/EllipticCurve/Q/453882/w/1
has torsion structure [u'2'], so is an example that needs to be fixed.

**Comment by jwj61** [comment]
This has been fixed.
