### ISSUE TITLE
Renaming a knowl

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2992]
I know there is a way to rename knowls, but I was not clear on how to
do it, or whether it also renames them in templates.

The specific case I want to do it replace
  mf.maass.mwf.fricke
by
  cmf.fricke
everywhere.

According to "Referred to by", it occurs in 2 python files and 1 html template.

**Comment by davidfarmer** [comment]
Also, mf.maass.mwf.atkinlehner should be replaced by cmf.atkin-lehner .

Both of mf.maass.mwf.fricke and mf.maass.mwf.atkinlehner can be deleted once the links to them are replaced.

**Comment by roed314** [comment]
If you start to edit the knowl, there will be a text field at the top called "Rename to" (viewable since you're an admin).  If you fill in the new name and save, it will start renaming.

When there are no references in the code, the renaming will take effect immediately.  If there are code references, it will create a copy with the new name and suggest a `grep/sed` command that you can use to rename the code references.  Once you make the changes to the templates, have the PR merged and eventually pushed to prod, you can go back to the original name, edit it and click on the "Finish renaming" button, which will update all the references in other knowls and move all of the history from the old name to the new.

**Comment by AndrewVSutherland** [comment]
Just to expand a little on what @roed314 said, let me first note that this is relevant only to knowl editors with admin privileges, so most knowl editors can ignore this issue entirely.

The "Rename to" button immediately changes all references in other knowls but does not make any changes to source code/templates, but it does make it easier for you to create a PR that changes the source code/templates.  So there are two scenarios, and you can tell which scenario you are in by looking at the references listed in "Referred to by" at the bottom of the knowl's home page.

**Scenario 1** (all the "Referred to by" items are other knowls): Click "Edit", type the new knowl name in the "Rename to" box and click save.  You will be asked to confirm.  Once you do the knowl will be renamed, all the knowl references will be updated, and you will see the confirmation message "Knowl renamed to ... successfully."

**Scenario 2** (one or more "Refereed to by" items is a source file):  Proceed as in Scenario 1, but now the confirmation message will include a grep/sed line that you can cut/paste into the command line to change all references to the knowl in source code/templates.  You should create a new git branch (but be sure to make your master current by pulling from upstream first), paste the grep/sed line into a shell prompt, commit and push the changes, and submit a PR for the new branch.

In Scenario 2, until the rename is completed (by someone clicking the complete rename button), the knowl can be referenced by either the old or new knowl name.  You should **not** immediately complete the rename, you (or someone else) needs to wait until your PR has been merged and pushed to both dev and web.  But there is now rush to do this, and in fact I think we should automate this last step so that no one needs to remember it (or accidentally do it to soon).

I realize scenario might sound a bit complicated, but it really isn't hard to do and it is certainly quicker and easier than what you would have done before this feature was added.

@roed314, @edgarcosta  I think rather than relying on editors to complete the rename process, we should instead have an automated task that periodically checks for knowls with renames in progress and then checks whether the knowl is still referenced by any source file in any of the master/dev/web branches.  This would make everyone's life easier; they can do everything they need to do in one sitting and then forget about it (this will also reduce the probability that someone will complete the rename too soon by accident, which I have done myself).

**Comment by davidfarmer** [comment]
Thanks, that explanation is clear.

But I just realized that I am in a slightly different situation.

Knowls A and B already exist.

Knowl A contains all the content, and is better, than
knowl B.

Every reference to knowl B should be a reference to knowl A.
Then knowl B should be deleted.

What I will do is copy the content of knowl A into
knowl B.  Then do the rename.  Now, if the renaming over-writes
knowl A, that is okay, because now knowl B contained that content.
(And implicitly, knowl B has been deleted.)

Please tell me not to do this if this use case has to be
done differently!

**Comment by AndrewVSutherland** [comment]
@davidfarmer I think the right thing to do in this situation is to cut/paste the content of A into B and then rename B to A (which will cause all the references to B to refer to A, and when the rename is completed the knowl B will be deleted).  But I suggest waiting for @roed314 to confirm. 

In general if X and Y are existing knowls, you can rename X to Y, and this should result in all references to either X or Y pointing to the new knowl Y, which will have Y's knowl id and X's content (and when the rename is completed, the knowl X will be deleted).

**Comment by AndrewVSutherland** [comment]
@davidfarmer Just to be clear, what I wrote above is exactly what you said!

**Comment by roed314** [comment]
I think that if you try to rename a knowl to an existing knowl, it will raise an error and make no changes.  I think the following will work, though I haven't tested it:
1. Move all content from B to A
2. Delete B.
3. Rename A to B.

There was also one error in Drew's explanation.  The changes to links in other knowls are done when the renaming is finished, not when it's started (see the `start_rename` and `actually_rename` methods on `KnowlBackend` in `lmfdb/knowledge/knowl.py`).

I'm fine with switching to an automated task.  Were you thinking a cron job on legendre?

**Comment by AndrewVSutherland** [comment]
@roed314 thanks for the clarification on timing.  Regarding renaming to a knowl that already exists, I have tested this and it seems to work fine, are you sure it's necessary to delete B?

**Comment by roed314** [comment]
Interesting.  If there are no code references, then `actually_rename` is called directly, which does not check for the existence of the new knowl.  If there are code references, `start_rename` is called, which checks and raises a `ValueError` if the new name already exists.

I think that this inconsistency isn't desirable.  I can see that being able to rename to an existing name is useful, but I think that doing so without any warning is dangerous (the histories are merged in a way that's not easy to undo).  What would we like the behavior to be?

**Comment by edgarcosta** [comment]
Whenever we solve the issue mentioned above we should convert some of this conversation into a "rename knowl procedure"

**Comment by davidfarmer** [comment]
And we need to start calling it "Changing the id of a knowl".
Renaming sounds like changing the title.

**Comment by AndrewVSutherland** [comment]
The specific example that generated this issue is addressed by #3015, but I'll leave this open since there are more general issues.

**Comment by AndrewVSutherland** [comment]
I'm going to create a new issue for automating the rename completion process and close this one, as most of it has now been addressed.
