### ISSUE TITLE
Atkin_Lehner vs Fricke

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#2993]
If the level $N$ is the product of distinct primes, then $\Gamma_0(N)$ has several
Atkin-Lehner involutions.  One of those is distinguished and is (usually?) called
the Fricke involution.

In these knowls
   http://beta.lmfdb.org/knowledge/show/cmf.plus_space
   http://beta.lmfdb.org/knowledge/show/cmf.minus_space
and possibly elsewhere, it says "Atkin-Lehner" but I think it should say "Fricke".

In case there is a difference of opinion on terminology, or I am wrong about how
that knowl is used, I didn't want to change this before asking for clarification.

**Comment by AndrewVSutherland** [comment]
Yes, it should say Fricke involution (which has a knowl here: http://beta.lmfdb.org/knowledge/show/cmf.fricke), and it should not mention \chi, since we are assuming the character is trivial when we refer to the Fricke involution (we only display information about plus and minus spaces when the character is trivial).

I have updated both knowls.
