### ISSUE TITLE
Use Lfunctions zeros knowl

### ISSUE THREAD

**Issue by pascalmolin** [LMFDB/lmfdb#3013]
The knowl
http://beta.lmfdb.org/knowledge/show/lfunction.zeros
is only referenced once, whereas the term zeros appear more often.

I suggest
1- making more references to this knowl
2- rewriting it to state first that a zero is in fact a value s such that L(s)=0, that there are trivial zeros where the gamma factor has poles, finally that non trivial zeros fall are expected to fall under Riemann Hypothesis.

**Comment by AndrewVSutherland** [comment]
This knowl now has five references and has been edited to actually define what a zero is and what the Riemann hypothesis says about them.  I'm not sure it helps to mention trivial zeros (is the likely reader of this knowl going to want to think about poles of gamma factors?)  Sometimes saying less is more.

**Comment by jwj61** [comment]
I think it is worth mentioning trivial zeros since someone who knows something about the topic but not a lot might be confused by the omission.  To avoid clutter, we could follow our usual practice and mention it, but make "non-trivial" a knowl which explains the what trivial zeros are.

**Comment by AndrewVSutherland** [comment]
OK, I added a non-trivial zero knowl http://beta.lmfdb.org/knowledge/show/lfunction.trivial_zero that is linked to from the zeros knowl, which I note now has 8 references.  Can one of you (@pascalmolin or @jwj61) please review the zeros knowl and the trivial zeros knowl?

**Comment by davidfarmer** [comment]
There are a few changes needed.  I'll edit and then @pascalmolin or @jwj61 
can review.

**Comment by davidfarmer** [comment]
The remaining L-function knowls are ready to be reviewed.

I created a "completed L-function" knowl and reference it in the
trivial zeros knowl.  (I made that knowl shorter.  The alternative
would be making it longer and going into more detail about what happens
with nontrivial zeros of non-arithmetic L-functions.)

I also clarified the relationship between "arithmetic"
and "arithmetically normalized" L-function in a couple knowls.
(The issue being that you can have an arithmetic L-function in
the analytic normalization.)

I also eradicated the "special values" knowl and its references,
since it had no useful content and struck me as adding confusion.
We need that knowl, but only when it is done properly.

**Comment by AndrewVSutherland** [comment]
Thanks for the corrections @davidfarmer (I realized shortly after I wrote it that it was specific to arithmetic L-functions but then saw that you had already fixed it). I agree that adding a completed L-function knowl is a good idea (in fact I think there are a few other places it could be referenced).

**Comment by AndrewVSutherland** [comment]
The zeros knowl now has more than ten references to it.  It would be great if someone could review the trivial zeros and completed L-function knowls, but I think this issue is ready to be closed.
