### ISSUE TITLE
Filter after knowls search

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3020]
If I search for all the knowls containing "Maass", and then want to filter the
results to see which are still beta, I can't do that because the filter options are
not available.

A slightly related issue is that I can't see a way to find all the knowls
with label beginning "mf.mwf".

This is in Chrome on a Macbook Pro.

**Comment by AndrewVSutherland** [comment]
Regarding your second point, you should be able to do this using a regex search mf.mwf.* (apparently there are none), for example if you type rcs.source.* into the label box, check the regex option and click search you will see all the source knowls (that have been converted to the rcs naming convention):

http://beta.lmfdb.org/knowledge/?search=rcs.source.*&regex=on

Regarding you first point, I agree that we should support search and filter selections in combination, I'm actually surprised that this doesn't work (even if you specify both on the initial search it appears that the go button ignores the filter and the filter button ignores the search string, but maybe I am missing something @roed314?)

**Comment by davidfarmer** [comment]
I didn't realize I had to click the Regex button!  :(

**Comment by roed314** [comment]
The cause is that there are two forms in the template, so you can't enter both "filter" and "search" conditions simultaneously.  And the reason that the filter options aren't available for search results is that someone explicitly added an if statement to the template to make that happen.  It was there before this spring's revisions, but probably not as noticeable since there were fewer filter options.  Part of the reason may be that the category filtering is done with links and thus ignores the search box.

It sounds like we want to merge the two forms and make them always visible?  This will involve deleting one of the buttons; maybe the Filter one?

**Comment by roed314** [comment]
I just talked to @AndrewVSutherland in person, and I think the plan is to remove the Filter button, merge the two forms and save the search query so that it can be reissued.  The filter options should always appear.

This isn't a top priority for me, so if someone else wants to take it on feel free. :-)

**Comment by davidfarmer** [comment]
I am okay with this taking a while.  The main use case I had, which has
mostly passed, was finding beta knowls on a particular topic.

**Comment by AndrewVSutherland** [comment]
This is now possible: https://beta.lmfdb.org/knowledge/?all=1&category=&search=Maass&beta=on&normal=on
