### ISSUE TITLE
Search on regulator

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3065]
At least from my point of view, the regulator and class number always go together, so it's slightly incongruous that we privilege the latter in our searches.  The regulator is a mysterious quantity, difficult to compute by hand, so seeing how it plays out with our data I think would be useful.  

The technical issue to overcome is how the data is stored in postgres.  JJ says "One table has the searchable part and the other has the rest.  Regulators would have to be moved".

**Comment by JohnCremona** [comment]
It would be very useful to have a utility function to make it easier to move columns between the search and extra tables, for this kind of reason.  It would be easy to do a rewrite adding a regulator column to the main table, copied from the search table, and then later to drop the extra table version.

I predict that we will find the hard-wired split between search and extra to be awkward sooner or later.  There are already exceptions, e.g. ec_padic is a second extra table for ec_curves, created way back when it was deemed normal for the data for a collection to be split across more than one table.

**Comment by jwj61** [comment]
Column created and rewrite in progress

**Comment by edgarcosta** [comment]
>  I predict that we will find the hard-wired split between search and extra to be awkward sooner or later. There are already exceptions, e.g. ec_padic is a second extra table for ec_curves, created way back when it was deemed normal for the data for a collection to be split across more than one table.

I understand that the split makes your life a bit harder, but it speeds up extremely the searches on the data.
Look at CMFs, we have two tables to do searches on `mf_newspaces` and `mf_newforms`, and then tons of other tables where we store all the data that we want to display but not to search on.

**Comment by AndrewVSutherland** [comment]
Just to echo @edgarcosta's point, just as when one writes a mathematical paper the top priority is to make life easier for the reader (not the author), when one publishes a mathematical database the top priority should be the users (not the developers).  There is no point in having a database that is easy to update but so slow that queries time out before results are returned (we split HMF's on mongo well before the postgres migration for precisely this reason).

Having said that, anything we can do to make life easier for the developers without negatively impacting users we should do, and the utility function proposed by @JohnCremona is a good idea.

I might also suggest that we perhaps don't need to be so aggressive about pushing columns to the extras table when there is no obvious need to do so.  The regulator is not large and it would have been fine to keep it in the search table from the beginning.  It's fine to keep small columns in the search table even if we don't currently search on them.

**Comment by JohnCremona** [comment]
I fully understand the benefits of having a small table on which most searches are made.  But the rest could be more flexible than putting everything else into a single extras table.  For example, if I decided to compute some new data for each elliptic curve, right now I have to (though this is not set in stone) add columns to either the main or extras table, but I different design could make it easy for the data to be in  new table (with prefix ec_curves), just as is now the case for ec_padic_data.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I agree 100%, when there is a natural way to split up the data (which there usually is) it is better to explicitly put things in separate tables rather than hiding it under the covers.  As you know, we didn't use any extras tables with CMFs, we designed the schema from the beginning with mathematical, performance, and maintenance issues in mind, and this is why there are 14 mf_* tables rather than one or two -- big things like portraits, hecke eigenvalues, traces, and lpolys all get their own tables.

The extras table functionality exists primarily to provide backward compatibility for schemas that were created with the document object model of Mongo in mind, it let's us split the data across tables without making any code changes.

But it might be well worth the effort to revisit the schemas for elliptic curves and number fields and consider making the code changes that would go along with a schema restructuring (if the schema is well designed, the code changes should be small).  Part of this would be changing modules like web_ec.py to construct an elliptic curve object using data retrieved from several different tables.

**Comment by JohnCremona** [comment]
OK, we really agree.  And if you look at the get_hmf() function in hilbert_modular_forms.py (which I wrote) you'll see that it does exactly that, hiding from users the fact that there are two tables involved.
