### ISSUE TITLE
EC/Q stats broken on beta

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3086]
See http://beta.lmfdb.org/EllipticCurve/Q/stats

But http://www.lmfdb.org/EllipticCurve/Q/stats wortks fine.

**Comment by JohnCremona** [comment]
I will fix this, it is easy:
       max_sqrt_sha = max_sha.sqrt() # exact!
Here max_sha is now an int where it used to be a Sage integer, and python ints have no sqrt() method.

**Comment by AndrewVSutherland** [comment]
@JohnCremona It seems to be working now, but I don't think the code changed, how did you fix it?

**Comment by JohnCremona** [comment]
Fixed -- PR in a minute -- but I am puzzled since the code I changed works OK on www and also there is a test which loads this page so why did the test not fail?  The code extract the maximum value of the 'sha' column of ec_curves, like this:

sage: db.ec_curves.max('sha')
5625
sage: type(_)
<type 'sage.rings.integer.Integer'>

and it appears that sometimes the result delivered is an int (hence crash) and sometimes it is in Integer (no crash).  So while my PR will stop this happening again, it does not really answer the question Why?

**Comment by JohnCremona** [comment]
I didn't fix it!  At least, only with PR #3088 which is not yet no beta.  As I said above, there is a random feature here which is very mysterious:   the max('sha') is sometimes an int and sometimes not.

The type of ec_curves.max('sha') is sometimes int and sometimes Integer, while the type of all the 'sha' column entries is int.

**Comment by JohnCremona** [comment]
Also, if I look at ec_curves.stats there is a row which seems to be saying that the max of the sha column is 49, which it is not.  I have no idea what is going on here.

**Comment by AndrewVSutherland** [comment]
@JohnCremona We're looking into it now.

**Comment by roed314** [comment]
There is a column "threshold" which was set to 1000 on that row.  The threshold is intended for the following situation: if you ask for statistics on a column with a few common values but many uncommon values, you might want to only include values where there are at least N rows.  That was done here, and indeed 49 is the maximum size of sha where there are least 1000.

I don't know why this threshold was getting set though.  I've deleted those rows since I was confused what what the problem was.
