### ISSUE TITLE
L-function knowl link not an option

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3087]
When editing a knowl, the string "L-function" is not recognized 
by Link Suggestions as a term to link to the knowl with its definition:
beta.lmfdb.org/knowledge/show/lfunction

I speculate this is because the definition is given in the top-level knowl.

Maybe that should be renamed to lfunction.definition , and having content
and the top-level knowl should be discouraged?

**Comment by AndrewVSutherland** [comment]
The only reason L-function was not being suggested was because of an extra space in the bold term **L -function** in http://beta.lmfdb.org/knowledge/show/lfunction which I have now corrected to ** L-function **.

If you go to http://beta.lmfdb.org/knowledge/edit/test.suggestions and click the suggestion link you will see that the lfunction knowl is now suggested. 

It is standard for us to use the top level knowl to define an object (see the knowls http://www.lmfdb.org/knowledge/show/ec or http://www.lmfdb.org/knowledge/show/nf, for example) and I don't think we need to change this convention.
