### ISSUE TITLE
Confusion about notation for signatures, and seemingly missing entries for higher genus curves

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3110]
From the feedback page:

> Actually, I'm confused about the signature of the entry I just submitted about.
> 
> It's an automorphism of a genus 3 surface of order 2. 
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&count=200
> 
> Or to see it in a shorter list:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=3&group_order=2&count=200
> 
> The signature says [2;2]. But shouldn't it be [2; -], or some other notation for no branch points? This should be a free action on a genus 3 curve, with quotient a genus 2 curve.
> 
> I feel like this may be an issue throughout the database. For instance here:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=4&group_order=3&count=200
> 
> The [2;2] entry should be [2; -]
> 
> And I was going to say here, next:
> 
> http://www.lmfdb.org/HigherGenus/C/Aut/?start=0&paging=0&genus=7&group_order=3&count=200
> 
> There should be a [3; -] entry. But it doesn't even appear, despite the fact that there are genus 7 curves with an order 3 automorphisms acting freely and with a genus 3 quotient. 
> 
> If I'm mistaken or if some other convention I'm unfamiliar with is being used, please let me know.
> 
> Thanks!
> Justin Lanier
> 

Reply to jlanier8@gatech.edu

**Comment by jenpaulhus** [comment]
I'll write to Justin about all of these issues but the gist of the problem is that the quotient genus >0 data wasn't ready for "prime time" (basically I thought this data had all vanished in the switch from Mongo to Postgres since it didn't show up on searches as Justin points out).  I am aware of the issues (Dave Roberts and Kiran Kedlaya also pointed them out to me recently) and my students and I are just about done fixing all of them.    

Jen

**Comment by AndrewVSutherland** [comment]
Just to clarify, it looks like there are pages with quotient genus > 0 in the database, e.g. http://www.lmfdb.org/HigherGenus/C/Aut/3.2-1.1.2-2-2-2.1.  Should these be removed?

Regarding the issues that Dave Roberts and Kiran Kedlaya pointed out, is there already a github issue for this (in which case perhaps this issue is a duplicate), or should this issue serve that purpose (and if so, does it adequately describe the problem)?

**Comment by jenpaulhus** [comment]
No! Please don't remove them.  We've got fixes for this coming soon.   

The issues Dave and Kiran brought up are encompassed in one of the multiple issues posted yesterday.

**Comment by AndrewVSutherland** [comment]
@jenpaulhus Got it, thanks!
