### ISSUE TITLE
Isogeny matrix of EC

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3155]
I believe that the Isogeny matrix is using the wrong labels, i.e., using the Cremona labels when should use LMFDB label and vice versa.

Compare:
http://beta.lmfdb.org/EllipticCurve/Q/15/a/
vs
http://beta.lmfdb.org/EllipticCurve/Q/15a/

And note that 15.a5 = 15a1 is the unique curve without an isogeny of degree 8.

side note, it also took me a while to figure out what meant search by isogeny degree for a curve in http://beta.lmfdb.org/EllipticCurve/Q/, as the knowl only defines isogeny degree.

**Comment by JohnCremona** [comment]
@edgarcosta I cannot see any inconsistency.  The curve [1,1,1,-10,-10] has no cyclic 8-isogeny.  This is 15a1 = 15.a5.  In the page http://beta.lmfdb.org/EllipticCurve/Q/15/a/ using LMFDB labels a5 is in the middle of the graph and row 5 of the matrix has no 8's.  In the page http://beta.lmfdb.org/EllipticCurve/Q/15a/ using C labels, a1 is in the middle and row 1 has no 8's.

**Comment by edgarcosta** [comment]
I agree with what you read from the matrix, and that is what lead me to this inconsistency, as the page of that curve (http://beta.lmfdb.org/EllipticCurve/Q/15/a/5 or http://beta.lmfdb.org/EllipticCurve/Q/15a1/)
says
```
This curve has non-trivial cyclic isogenies of degree $d$ for $d=$
2, 4, 8 and 16.
```
and that curve also shows here:
http://beta.lmfdb.org/EllipticCurve/Q/?conductor=15&isodeg=8&surj_quantifier=include

**Comment by JohnCremona** [comment]
OK I see -- there is a bug, possibly two, but not on the isogeny graph/matrix page.  On the curve's own home page it gets that list of isogeny degrees directly from the database.  It appears that when I added the list of degrees to the db I messed up:
sage: db.ec_curves.lucky({'label':"15a1"})['isogeny_degrees']
[1, 2, 4, 8, 16]
Best solution is is obviously to fix that column in the database.  Meanwhile, a trick like
sage: db.ec_curves.lucky({'iso':"15a", 'lmfdb_number':1})['isogeny_degrees']
[1, 2, 4]
might succeed in getting the correct number into the home page but will not correct the wrong search result.

Looking at the data upload script I see that even though the isogeny matrix rows/cols in my data files are in the C ordering, they are permuted on upload so that they are stored in the LMFDB ordering.

Thanks (!) for spotting this.  I will fix the first thing now but the second will require data changes and I will put that off.

**Comment by JohnCremona** [comment]
I promise to fix the isogeny_degrees data column.  That will make PR#3156 redundant so I'll close that.

**Comment by JohnCremona** [comment]
The data has been fixed.  If someone could check that the links above now give results which are correct then we can close this.

**Comment by edgarcosta** [comment]
This is fixed on beta, we just need to copy the table to www.lmfdb.org.

**Comment by JohnCremona** [comment]
Good point -- can someone do that?

**Comment by edgarcosta** [comment]
Done
