### ISSUE TITLE
Download button at top of search result

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#3166]
As per conversation in #3130,  I suggest we include download buttons near the top of searches on the site as well as at the bottom.

**Comment by AndrewVSutherland** [comment]
As noted in https://github.com/LMFDB/lmfdb/pull/3442#issuecomment-552515811, we need to think a bit about exactly how we want to address this issue before implementing a solution -- I think we should revisit this after we have finished uniformizing the search results display (this work is in progress).

**Comment by AndrewVSutherland** [comment]
We discussed this today at our editorial meeting and decided to go ahead and include this in 1.1.2.  In order not to lose any vertical space we would like to have the download links in the same line as the next/prev buttons (perhaps floated to the right). If we shorten "Results (displaying matches 1-50 of ...)" to "Results 1-5o of ..." there should be plenty of space.

**Comment by tomgrubbmath** [comment]
I have attached a crude first pass at what this would look like. At this point I would like some feedback before implementing fully. 

- In what order do people prefer the "Results," "Forward/Back," and "Download" bits? 
- Should there be roughly even spacing between the three, or justified some other way? 
- Is there a central list somewhere telling which objects are "downloadable" and which are not? I can do this just by brute force search through each potential page, but it'd be easier if I could just look it up somewhere. 

![Screenshot from 2020-09-08 15-05-59](https://user-images.githubusercontent.com/53013402/92532534-5723f300-f1e5-11ea-84c8-1285e34b4e28.png)

**Comment by roed314** [comment]
What you've done looks pretty good to me.  I think the "Results" and "Forward/Back" are conceptually linked to each other, so I think it makes sense to have them closer together rather all three equally spaced.

I don't think we need to repeat the number of results now that this has been moved up to the top.  But we do need to think about the case of what it looks like when we haven't computed the number of results. I think the current message, "In order to download results, [determine the number of results](url)" works, moved up to the same place.

I think all of the search pages allow for downloading results (except ones like Siegel modular forms that are non-standard). Is that what you're looking for or do you mean something else?  Probably the ideal thing to do would be to update one of the global templates (e.g. `lmfdb/templates/matches.html`).

**Comment by tomgrubbmath** [comment]
@roed314 Thanks! I will continue along these lines. 

The problem with editing matches.html is that currently there are two files: matches.html and download_search_results.html. Some search pages include both, but others, like the Hilbert Modular Forms specific page, call matches but do not have the download option. Is this by design? Or should it also have the download option?

**Comment by JohnCremona** [comment]
I suspect that we will get a lot more people clicking on these Download
buttons when they are at the top.  Some search results pages have a limit
on the amount of data which we allow people to download -- is that handled
well after these changes?  We should not invite the user to download N (a
large number) of results if when they click on the download button they are
told "you cannot, that is too many).

Secondly, it is likely that this will result in requests for better
download options with fuller data in better formats, etc, so we had better
be prepared to handle all that (as we should anyway -- we do have two
different api 's already).

**Comment by roed314** [comment]
@tomgrubbmath I think the goal is that all pages support downloading results.  So if there are pages where that's not currently the case, the ideal solution would be to add them.

@JohnCremona The code in `/lmfdb/templates/download_search_results.html`, which I'm suggesting Tom port to `matches.html`, includes a test to see if there are too many results.  And I agree that there are more improvements to downloading that we can make; in fact this was one of the priorities that @davidpeterroberts suggested last month.

**Comment by jenpaulhus** [comment]
Just stopping by briefly to say this looks good (since I was the person who wrote the original ticket).

**Comment by tomgrubbmath** [comment]
I just incorporated David's new "buttons as links" code, and here is where we are at. I wanted to get one final piece of feedback before committing the changes. Here are photos:

![downloadtop1](https://user-images.githubusercontent.com/53013402/94306433-cb6dce80-ff27-11ea-8d12-27b19792db48.png)
![downloadtop2](https://user-images.githubusercontent.com/53013402/94306436-cdd02880-ff27-11ea-8609-3c5028e3c14d.png)
![downloadbot](https://user-images.githubusercontent.com/53013402/94306440-cf99ec00-ff27-11ea-99eb-ef82d291e9c1.png)

The feedback I am looking for is when you need to compute the number of results before downloading. Because the download_results code is included in a "Header" environment on the top, it isn't visually clear where one should click in order to enumerate the total number of results (compare photos 1 vs 3). Are people ok with this? Or should I do some more fiddling to make it clearer?

**Comment by JohnCremona** [comment]
Why not have it so that clicking on any of the dowload buttons causes the count to be done?  If the number is large we could pop up an "are you sure?" dialogue box (only joking).

**Comment by roed314** [comment]
@JohnCremona We talked about this a bit on Zoom, and agree that it would be a nice feature.  I think the consensus was to hold off until another ticket though.
