### ISSUE TITLE
Degree 30 number field page won't load

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3173]
If you click on any of the first six number fields of degree 30 (and presumably many more) returned by 

http://beta.lmfdb.org/NumberField/?degree=25-39

For example

http://beta.lmfdb.org/NumberField/30.0.17761887753093897979823770061456102763834271.1

the page times out and throws a server error.  None of these fields is yet on beta.

**Comment by jwj61** [comment]
I am aware of the problem with the other high degree fields.  The other pull request #3170  should fix that.  Here is the longer story.

To make it so we can search on regulator, we copied 'reg' from the extras table to 'regulator' in the main table, and ultimately deleted 'reg'.  But, my import script was not updated, so when I uploaded some fields this morning, some went in without regulators.  To trigger the bug, one needed a new field where we had computed the class group.  The old code would see the class group and no regulator and think, aha, I am supposed to compute the regulator on the fly, which takes too long in these cases.

So, fix one is in the other pull request -- never try to compute the regulator on the fly.  Second, there is a data issue which will be fixed in time.  It is being held up by the problem I was having with upsert in issue #3172

**Comment by jwj61** [comment]
On the degrees not having fields, that is also temporary.  To get something in place, I computed all abelian fields of degree <48 and conductor <= 5000.  They are in the "prep" stage of computing auxillary data.  This takes much longer with high degree fields -- most hit my timeout for computing class number (and related items like units).  Once prepped, I will upload them, and then there should be something in all degrees.

Don't worry, we won't have just abelian fields.  After that, I have a collection of small height trinomials (x^n+ax+b) in each degree to import, followed by polynomials from Denis Simon, and I know Dave Roberts has higher degree fields to add, probably fields from Artin representations, etc.

**Comment by jwj61** [comment]
The fields now load by fixing the data.  The code change is still appropriate since it is a case which should never be reached.
