### ISSUE TITLE
Problem rendering latex

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3201]
On the page
  http://beta.lmfdb.org/NumberField/32.0.2294081869728198830572049522437155246734619140625.1

some of the fundamental units appear (for me) as raw latex.  I took one, pasted it into a latex document and the document compiled find by latex.  Maybe katex can get overloaded?

**Comment by davidfarmer** [comment]
I see that error in Chrome and Safari but not in Firefox.
(On my Mac laptop.)

**Comment by alexjbest** [comment]
Yes it definitely seems that for the longest \( \) blocks, Katex refuses to render them, I can't work out the exact mechanism and whether it is a bug or some hard-coded limit we are exceeding.

Rather than us try and fix this maybe we should take it as a sign that some quantities are too large to be displayed to a human like this (even when it does render they fill the page and are a little meaningless (to me)). Its great that the data is there and can be accessed via download or database query for statistics, but I wonder if anyone actually looks at any question related to the fundamental units for such a large field one by one by hand, rather than just via some code to read the data and extract the answer to whatever question they have.

What do you think: should the fundamental units display code return "Not shown, download to access units" whenever the output would be over 500 characters or something?

**Comment by jwj61** [comment]
I agree that number field pages should have a link for downloading data from the page, and will work on that.

On the other hand, I don't think the process should be driven by limitations of an external component.  I think nothing makes it clear how complicated these units are as much as seeing them, so even if no one is going to read individual digits of them, I would prefer to display them.

**Comment by AndrewVSutherland** [comment]
Fixed by #3263
