### ISSUE TITLE
Search elliptic curves over Q by regulator and by number of integer points

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3238]
From Noam Elkies: It would be nice to be able to search the EC/Q database by number of integer points and by regulator (within a specified interval).  The data to support these queries is already present (the number of integer points is the length of the list xcoord_integral_points), so this is simply a matter of adding search options for them (and possibly some indexes to support these searches more efficiently).

**Comment by roed314** [comment]
@JohnCremona Any objections to adding a `num_integral_points` column to `ec_curves`?  Once that's present, it's very easy to populate, and then the front end changes shouldn't be too bad.

**Comment by roed314** [comment]
I don't want to get in the way of your methods for updating the curves by doing something ad hoc.

**Comment by JohnCremona** [comment]
@roed314 No objections but please do not change the ec_curves schema at this point since I am in the middle of uploading data (to be resumed after the weekend which means Tuesday).  I'll add that to a list of minor things to be done in a table rewrite.  We also need to remove the obsolete column galois_images, and add columns relating to optimality and Manin constant.  My plan is to do all that after uploading the new curves.  While we are at it we can also add * number of bad primes (useful to restrick to prime power conductor) * semistable * and more.

**Comment by roed314** [comment]
Sounds good; I won't do anything to the schema for now.

**Comment by JohnCremona** [comment]
I have added new columns 'num_int_pts', 'num_bad_primes', 'semistable' and the last two are already populated with a rewrite but I forgot to do the first.  I'll be doing another rewrite quite soon to add optimality and Manin constant data, so I was not planning to populate the 'num_int_pts' columns until then (but of course I could).  Rewriting takes 1h40m approx.

**Comment by JohnCremona** [comment]
OK, so now all curves have 'num_int_pts' and 'num_bad_primes' and 'semistable' set.  (On dev not www at this point.)

**Comment by SamSchiavone** [comment]
I've started working on adding a search feature for number of integral points. It seems that currently 'num_int_pts' is really recording the number of x-coordinates of integral points, so the number of integral points "up to sign." Is this the desired effect? If I search for num_int_pts = 2, that means I could get curves with 3 (if one of the 2-torsion points is integral) or 4 integral points. Or should I try to change it to give the actual number of integral points? I lean toward the second option, but I'm happy to do either.

**Comment by JohnCremona** [comment]
@SamSchiavone Yes, the column num_int_pts holds the number of integral points up to sign.  P is integral iff -P is iff x(P) is, so the actual number of integral points is approximately double this -- not exactly double since integral points may have  order 2.  I don't know what you mean by "desired effect"; it is what is stored, along with the x-coordinates.  When a curve's home page is displayed the y-coordinates (just one per x) are computed on the fly in lines 374-380 of web_ec.py.  It would be possible to store the y's as well and the total count, but we do not at present.

The simple way to proceed is to make it clear when adding the new search box that this is the relevant count, for example by labelling the box "Number of integral points (up to sign)" or "Number of integral points (\($\pm$\))".

Otherwise new columns need to be added to the database and a one-off table copy to populate the new columns **and (very important)** appropriate changes to the data import script so that if/when new elliptic curve data is added, these new columns get populated.

Perhaps some discussion is needed as to which option we go for.  I would be inclined to go for the easy option, but I will not be implementing this myself.
