### ISSUE TITLE
inventory edits not being saved on beta

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3260]
I can edit inventory entries OK on a local server (with correct user and password set of course) but not on beta, where these things should be done as for knowl editing, by anyone with a login (or some subset).  When I make a change, say to the description of a column, and save, the change is not stored no nothing changes.  It works fine locally though.  Is it a permission problem with the inv* tables on beta?

Where can I see the weberver logs for beta.lmfdb.org?  I have a login on proddb but don't know if that is the right machine, or where to look if it is.   The local log for a successful edit looks something like 

INFO:werkzeug@2019-08-22 07:14:24,335: 127.0.0.1 - - [22/Aug/2019 07:14:24] "POST /inventory/submit/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:24,560: 127.0.0.1 - - [22/Aug/2019 07:14:24] "GET /inventory/success/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:24,716: 127.0.0.1 - - [22/Aug/2019 07:14:24] "GET /style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:24,806: 127.0.0.1 - - [22/Aug/2019 07:14:24] "GET /inventory/style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:27,115: 127.0.0.1 - - [22/Aug/2019 07:14:27] "GET /inventory/ec/ec_curves/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:27,320: 127.0.0.1 - - [22/Aug/2019 07:14:27] "GET /style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:27,429: 127.0.0.1 - - [22/Aug/2019 07:14:27] "GET /inventory/style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:14:27,722: 127.0.0.1 - - [22/Aug/2019 07:14:27] "GET /inventory/ec/ec_curves/data/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:11,243: 127.0.0.1 - - [22/Aug/2019 07:15:11] "GET /inventory/ec/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:11,460: 127.0.0.1 - - [22/Aug/2019 07:15:11] "GET /style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:11,549: 127.0.0.1 - - [22/Aug/2019 07:15:11] "GET /inventory/style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:13,789: 127.0.0.1 - - [22/Aug/2019 07:15:13] "GET /inventory/ec/ec_curves/edit/ HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:14,231: 127.0.0.1 - - [22/Aug/2019 07:15:14] "GET /style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:14,253: 127.0.0.1 - - [22/Aug/2019 07:15:14] "GET /inventory/style.css HTTP/1.1" 200 - 
INFO:werkzeug@2019-08-22 07:15:14,712: 127.0.0.1 - - [22/Aug/2019 07:15:14] "GET /inventory/ec/ec_curves/edit/data/ HTTP/1.1" 200 - 
resorting disabled
resorting disabled
INFO:werkzeug@2019-08-22 07:16:05,992: 127.0.0.1 - - [22/Aug/2019 07:16:05] "POST /inventory/submit/ HTTP/1.1" 200 - 
resorting disabled
INFO:werkzeug@2019-08-22 07:16:27,920: 127.0.0.1 - - [22/Aug/2019 07:16:27] "POST /inventory/submit/ HTTP/1.1" 200 -

**Comment by roed314** [comment]
Yes, it's probably a permissions problem (I just checked, and webserver only has read permissions on `inv_tables`, and probably on other inventory tables as well).  You need to execute something like

```python
sage: db.grant_insert('inv_tables')
```
to give permissions to the appropriate tables.

The relevant log file is on grace.mit.edu, but I'm not sure exactly what the path to it is.  I assume http://beta.lmfdb.org/flasklog doesn't contain what you need.

**Comment by edgarcosta** [comment]
@JohnCremona have you considered running it locally with
```
user = webserver
password = the right password
```
?

**Comment by roed314** [comment]
@edgarcosta suggested the log file `/home/lmfdb/logs/dev/supervisor.log` on grace, which looks right to me.  The `can_read_and_write_knowls` and `can_read_and_write_userdb` are used explicitly in the knowl code and userdb code; I'm not familiar enough with the inventory code to know if there's something similar going on there, but I doubt it since the function doesn't exist in `database.py`.  Once the postgres permissions are granted, I don't know of any obstacles on the backend side that would prevent data being written to those tables.  I'm a bit at a loss for what else might be different when running on beta versus localhost.

It's certainly plausible that the inventory system needs to be checking credentials for some operations, but I don't know how that has been set up.

**Comment by JohnCremona** [comment]
@edgarcosta I said expliticly above that (1) it does work locally and (2) that's not enough, suitably authenicated people need to be able to do this on beta.
@roed314 OK that's the extra information we need to get this added to the inventory code.  @csbrady-warwick

**Comment by edgarcosta** [comment]
@JohnCremona, just making sure you weren't running it with the user `editor`, as by default on a regular table that one has more permissions than the `webserver`.
If it works with `webserver` locally but not on beta, then I'm completely lost what could trigger the different behavior.
There is one more difference between your setup and beta, which is gunicorn, but I honestly don't see how that can affect it.

**Comment by JohnCremona** [comment]
Sorry @edgarcosta I had missed your point. Now I understand. After the long weekend I'll try with webserver as user and see what the logs say.  I expect dr's diagnosis is correct.

**Comment by AndrewVSutherland** [comment]
With the new schema infrastructure I don't think this is relevant any longer (but I do think there is some information in inv_tables that should be added to the table meta data, e.g. nice_name, status, contact, code link,...).  I'm going to expand #4811 to note this and more generally, that all metadata should be editable via knowls so that we don't need a separate infrastructure for this.
