### ISSUE TITLE
Some degree 47 number field pages timeout

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3266]
If you click on any of the last 3 search results for degree 47 number fields:

    http://www.lmfdb.com/NumberField/?degree=47

the request will timeout before the page is displayed.  My understanding is that this is due to time spent computing some invariants on the fly that are trivial to compute for lower degree fields but happen to be more difficult in these cases (all of which have Galois group C_47.   There is one other C_47 page, the fourth from the bottom on the list above that will load but takes a long time).

We should either store the invariants that are hard to compute on the fly, or not display them in cases where we know they are going to be tough to compute (the former is clearly the best solution, but the later might be easier to implement in the short term).

**Comment by jwj61** [comment]
I thought we could get away with precomputing only some of the invariants.  In fact, in some cases initializing the number field takes to long, even if we provide the ramifiying primes or an integral basis.  By the time the next rewrite is done, we should have everything precomputed.

**Comment by AndrewVSutherland** [comment]
This is fixed via #3395 (there is still a katex rendering problem, but this is a separate issue.

**Comment by jwj61** [comment]
I submitted a bug report to katex.  They said that the browser was chopping up long bits of text into shorter nodes, so katex was not seeing the matched start/end for latex expressions.  I have not had a chance to look into this further.  If someone else is inclined to tackle this, here are quotes from the two responses on their issue tracker.

----------------------------------
It seems Chrome optimizes by splitting a long Text node into several Text nodes.

You can call normalize() on the element to merge them before passing to KaTeX. I'm not sure it'll be worth adding it to auto-render, as it may increase processing time, but we should definitely add it to the documentation.
----------------------------------
Instead of normalizing, we could do some work in auto-render.js's renderElem/renderMathInText to detect consecutive text fields where the first one has an open delimiter but no closing delimiter, and treat them as if they were merged... though it definitely would make the code messier. ☹️
----------------------------------

Back to me.  The issue is not specific to chrome, but maybe calling normalize at the right time will fix all browsers.
