### ISSUE TITLE
Add rescrape link to the inventory

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3279]
If a person clicks on the link for the inventory, have a link or button to rescrape a table.  It could be at the top or bottom of the page, or in the properties box.

**Comment by JohnCremona** [comment]
I see a couple of possibilities:
   - In the inventory page for a collection of tables, e.g. ec at http://beta.lmfdb.org/inventory/ec/, then as well as the buttons already there for each table we could add a refresh button for that table, together with a "refresh all tables" button at the top.  These would be invisible or at least inactive unless the user is logged in.
   - At the level above, http://beta.lmfdb.org/inventory/, we could have a Refresh button next to each section (where "collections" needs to be renamed "tables" also).

I seem to be using "refresh" instead of "rescrape", and that is perhaps a better term now that we do not (as we used to with mongodb) go through every record during this process.

**Comment by JohnCremona** [comment]
Another small thing: on pages such as  http://beta.lmfdb.org/inventory/ec/ it is not immediately obvious that the table names are live links to the inventory display -- the table name (e.g. ec_curves) is the same colour as its nice name and the shaded background on mouse-over is not very noticeable.  We could instead have a visible button-type link "Show inventory".

**Comment by JohnCremona** [comment]
Another "hidden" feature (documented at https://github.com/LMFDB/lmfdb/blob/master/Inventory.md, which needs a little updating) is http://beta.lmfdb.org/inventory/controlpanel/.  Are we sure that all the functions there are still needed under postgresql, and still work?
