### ISSUE TITLE
Browsing Features in Isogeny Classes of AbVarFq

### ISSUE THREAD

**Issue by tdupu** [LMFDB/lmfdb#3310]
People requested more browsing features (as in Elliptic Curves over QQ):
    *by p-rank
    *by simple 
    *some with interesting p-rank and delta rank

**Comment by tdupu** [comment]
more search buttons:
*ordinary 
*supersingular
*p-corank

**Comment by roed314** [comment]
Fixed by #6196.  I didn't add additional dropdowns for ordinary or supersingular (since the UI is already very full), but ordinary is available either via `p_corank=0` or `newton_elevation=0`, and supersingular is available either by `angle_rank=0` or `newton_elevation=1,2,4,6,9,12` (if `g` is fixed).
