### ISSUE TITLE
Better description of hecke eigenvalue field

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#3325]
On the home page of a HMF
http://www.lmfdb.org/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-109.1-a
It says
The Hecke eigenvalue field is $\Q(e)$ where $e$ is a root of the defining polynomial: 
$x^{2} -2x-4$.

It would be more informative if it said that the field is Qsqrt5.
Also, "e" is a confusing name for the root.

Maybe
"The Hecke eigenvalue field is Qsqrt5, realized as ..."

**Comment by jvoight** [comment]
"e" was chosen because it stands for eigenvalue.  I do not see another use of "e" on the page.  Is your confusion mathematical--or otherwise?  

Now that CMFs have converged, we've learned much better was of displaying Hecke eigenvalues (using LLL-reduced basis for the coefficient ring, etc.); so in fact I would go much farther than your suggestion, and I would propose that GL_2-modular forms, no matter what the base field, follow the same display convention for this kind of data.  Do you like how this is displayed for CMFs?

If so, and there isn't something wrong, I am reluctant to make a "spot" change like you suggest.  It'll be more work, probably introduce mistakes, and still wouldn't follow the CMF conventions.  

I propose we close this issue, or if you'd prefer we could convert it into an "HMF 2.0" issue--with milestone--that indicates the scope of the desired improvements, including improved UI for Hecke data.

**Comment by davidfarmer** [comment]
The "e" is potentially confusing, but tolerable since it does explain what it means.

My real comment was concerned the words immediately after "The Hecke eigenvalue field is".
Since that does not occur on the CMF pages, and you say that the HMF pages will be changed
to look more like the CMF pages, I will close this issue because it will probably no longer apply.

I'll see if there are other places where my comment about naming fields is relevant.
