### ISSUE TITLE
Hilbert Modular Forms page missing explanation of relationship between Hecke Eigenvalues and q-expansions

### ISSUE THREAD

**Issue by alisonbethmiller** [LMFDB/lmfdb#3330]
On the page for the Hilbert modular form, there's a section for "Hecke eigenvalues ($q$-expansion)", with a list of Hecke eigenvalues.

There should be an explanation of the relationship between the Hecke eigenvalues and $q$-expansion (and also the Euler factors in the L-functions?).  There should also be a knowl for Hecke eigenvalue -- right now the page is not usable unless one is already specifically familar with Hilbert modular forms.

**Comment by AndrewVSutherland** [comment]
Clicking on the term q-expansion brings up a knowl that explains what the q-expansion of a Hilbert modular form is and that for eigenforms the q-expansion coefficients are eigenvalues.

What further change is needed to address this issue?  Would including the word eigenvalue in the knowl link be enough, is there more we could do.  I don't think the explanation being sought should appear on the page itself, it should be in a knowl (that is what knowls are for), I think the issue is that it is perhaps not as obvious as it should be that there is a knowl waiting to be clicked on.

@jvoight You tagged this as a good first issue -- what change did you have in mind?

**Comment by jvoight** [comment]
I think @SamSchiavone was working on this?

**Comment by alisonbethmiller** [comment]
It's been a while since I looked at this, but:  I think it would be helpful to have a knowl for Hecke eigenvalue.  It's good that the q-expansion knowl has an explanation of the connection, but less good that it's in the last sentence after a bunch of other stuff, so easy to miss.

**Comment by SamSchiavone** [comment]
I wrote a script for converting the Hecke eigenvalues a couple years ago (https://github.com/SamSchiavone/lmfdb/tree/convert_hecke_eigenvalues), but I think @BenKBreen was working on knowls for HMFs more recently.
