### ISSUE TITLE
Develop a style for home pages

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3349]
Several comments from the recent workshop could be summed up by saying that we do not have a clear style for object home pages.  Almost every such page has sections, maybe subsections, and then items where an item is usually of the form "description : value".  But there is enough variability in section headings and item typesetting to be, at times, confusing.

Part of the confusion stems from the fact that links are rendered in a special color, but in keeping the color palatte small, the same look appears in other places on the page.

There is no way to fix this without modifying each homepage template.  But, it would probably help if each page consisted of one big div with a class.  Then css can define h1, h2, h3, etc. for that class.

**Comment by jvoight** [comment]
A bunch of folks have worked in getting together the following draft of a "style sheet".

- All titles, captions, column headings should be left-aligned, use sentence case (only first word and proper nouns capitalized). Abbreviated column headings should omit the period.
- Colons should not follow captions on search pages or in property boxes, but should be used on object pages.
- Jump box caption should have the form "Find a specific blah, blah, by blah" should have knowls on the blahs, the input box should be on the line below (no caption in front) and the button should say "Find".
- Search heading on main browse page should be "Search".
- Input boxes should have standard widths (very long boxes, e.g. geometric invariants, may span the entire width)
- Option boxes should use standard captions in lower case (e.g. include/exclude/exactly or yes/no). If an option imposes no restrictions on the search it should be blank, and except where there is a good reason to do otherwise, this should be the default.
- All search pages should have "List of blah" and "Random blah" buttons (and possibly others).
- Default number of results with filled in (confirm) value of 50 should be on main search page.
- Search results table should use alternating colors, headings should all have knowls (or pseudo-knowls).
- Refine search pages should have captions above input boxes, no example to right, gray example inside input box, number of results should not appear.
- Factorizations of negative numbers should include only the sign, not -1.

**Comment by AndrewVSutherland** [comment]
The style sheet is now in the markup file StyleSheet.md in the main directory.

**Comment by AndrewVSutherland** [comment]
I've expanded the style sheet to cover search pages as well as object pages, and also learnmore, properties, related objects, and downloads boxes.  I also made a few css changes (at the content block level which I think is better than creating a new div class, we should take more advantage of the templating system we have, indeed the content h1, h2, h3, etc already have styling that we can further refine if desired).

There is clearly more work to be done, both in terms of refining the style sheet and making sure that all the sections of the LMFDB conform to it, but I think the basic issue raised by this PR has been addressed and suggest that specific issues about style be raised as new issues.
