### ISSUE TITLE
big integers displayed with "L"

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#3366]
Look 20 lines down in the search display in http://www.lmfdb.org/EllipticCurve/Q/?sha=144&surj_quantifier=include

I think the "L"s should be deleted.

**Comment by JohnCremona** [comment]
I am not sure that is is a good *first* issue since when I looked I found that the code for doing the search and displaying the results has changed beyond all recognition (by me).  Unless this can be done in the html template ec-search-results.html it would appear to require messing with search_wrap.

Are there no other places where a column contains a list of integers which may be large, and that column is part of the search_results data?

**Comment by JohnCremona** [comment]
> I am not sure that is is a good _first_ issue since when I looked I found that the code for doing the search and displaying the results has changed beyond all recognition (by me). Unless this can be done in the html template ec-search-results.html it would appear to require messing with search_wrap.
> 
> Are there no other places where a column contains a list of integers which may be large, and that column is part of the search_results data?

Ignore that, I have fixed it (here).
