### ISSUE TITLE
Request for different output in elliptic curve search results

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3388]
From the feedback page:

Dear LMFDB,
I am a PHD student working on elliptic curves and I would like to see the database as a table with the curves and their discriminant. Is it possible ?
Thank you in advance, Severin

Please respond to severin.philip@univ-grenoble-alpes.fr

**Comment by edgarcosta** [comment]
On this topic, I believe that we should do two other improvements:
- LMFDB and Cremona labels should be togglable
- Display the equation instead of the Weierstrass Coefficients

**Comment by JohnCremona** [comment]
On Fri, 27 Sep 2019 at 17:28, Edgar Costa <notifications@github.com> wrote:

> On this topic, I believe that we should do two other improvements:
>
>    - LMFDB and Cremona labels should be togglable
>
> Can you be more precise?



>
>    - Display the equation instead of the Weierstrass Coefficients
>
>
(In the search results list?)  That would be very easy, only
requires changes to lines 116 and 129 in
lmfdb/elliptic_curves/templaes/ec-search-results.html

**Comment by edgarcosta** [comment]
@JohnCremona, having the two labels side by side is a bit confusing sometimes, and if we add more columns to the search results then I think it could be a good feature to have some columns to be togglable (through javascript), and a natural thing that sometimes I want to hide is one of the label systems in ECs.  This was just a showerthought, and quite far from being a priority, as I have not yet worked many of the details. For example, if we would save this preferences or not through cookies.

**Comment by JohnCremona** [comment]
I have no objection to someone else implementing this. Not a priority for me.

**Comment by edgarcosta** [comment]
Anyhow, two of the things we discussed I think are potentially two good first issues are:
- Display the equation instead of the Weierstrass Coefficients
- Display discriminant of the EC

The idea of having togglable columns we can leave it for another day.

**Comment by AndrewVSutherland** [comment]
Two comments:

- If we are going to display the discriminant in the search results we should also make it a search option (not hard and still a good first issue, but he layout of search inputs on the results page may need a bit of tweaking).  I would also suggest using the absolute value of the discriminant (as we do for genus 2 curves) rather than the discriminant.
- This is going to make the output table quite a bit wider, forcing a horizontal scroll on small screens.  To save horizontal space (prior to toggling) I would remove the word "label" in the subheadings "LMFDB label" and "Cremona label" and put it in the superheadings "Curve" and "Isogeny class"

**Comment by JohnCremona** [comment]
> Two comments:
> 
> * If we are going to display the discriminant in the search results we should also make it a search option (not hard and still a good first issue, but he layout of search inputs on the results page may need a bit of tweaking).  I would also suggest using the absolute value of the discriminant (as we do for genus 2 curves) rather than the discriminant.

Personally I find it extremely unlikely that anyone would want to search on discriminant as such.  If they did, using the absolute value makes sense (and the database stores that and the sign separately anyway).  For display, the only sensible thing (surely) is to display the discriminant in factored form.  We do store the list of bad primes and the discriminant valuations, so again that is easy.  Otherwise it wil look like some long string of digits which carries little visual information: it is the exponents which (if anything) people might want to see.  Searching on exponents of bad primes would be rather harder to implement though.

> * This is going to make the output table quite a bit wider, forcing a horizontal scroll on small screens.  To save horizontal space (prior to toggling) I would remove the word "label" in the subheadings "LMFDB label" and "Cremona label" and put it in the superheadings "Curve" and "Isogeny class"

Maybe this is not such an issue if we display that discriminant factored, but it's a reasonable suggestion anyway.

**Comment by AndrewVSutherland** [comment]
@JohnCremona For people thinking about arithmetic statistics type questions, it is not unusual to order elliptic curves by |D| (or more likely by 4|A|^3+27B^2 for a non-necessarily minimal model y^2=x^3+Ax+B) rather than by conductor and such a person might be curious to know, for example, how many elliptic curves over Q are there with |D| < 10^5.  This is a question that the LMFDB can easily answer, but not with the current search interface.

I'm not advocating that such a search be added, just pointing out that there is potentially relevant archimedean information contained in |D| that is unrelated to its prime factorization, and I can imagine that someone wanting |D| in the search results would also want to be able to search on it.

But I think we should first decide whether we it makes sense to add the discriminant to the search results as a one-off change prior to making the search result columns configurable by the user (the union of all things an LMFDB user might want to see in the search results is surely larger than what we want to display by default -- no one is going to be happy if they always have to scroll to the right to see the column they care about).  In my opinion the answer is no, I think we should defer this issue rather than implementing it now just because it is easy to do.

I also think that @edgarcosta engaged a bit of threadjacking when he suggested displaying the curve equation rather than the Weierstrass coefficients and making the LMFDB/Cremona labels toggleable, These are both perfectly reasonable suggestions (which I personally like better than the one we are debating), but they have nothing to do with this feature request.  I would suggest creating separate feature requests for them. I understand that from an implementation perspective it makes sense to consider issues that touch the same source file at the same time, but from the perspective of deciding whether and how to address a feature request, it is better to keep the issues separate.

**Comment by JohnCremona** [comment]
All good points.  One possibility it to have the columns displayed in the search results table depend more on which search fields were filled in.  (At the moment we do this for only a column about Galois images.)

**Comment by AndrewVSutherland** [comment]
@JohnCremona I like this idea a lot.

**Comment by JohnCremona** [comment]
I was wrong in one respect: the database does not store the discriminant at present.  It stores th bad primes and the discriminant exponents and sign, but the file web_ec.py contains the line
`D = self.signD * prod([ld['p']**ld['ord_disc'] for ld in local_data])`
So a prerequisite for searching on discriminant would be to compute and store these.  I suppose we would store the absolute value only, and allow specifying the sign or not in a search.  But the logic required to handle a search with discriminant between (say) -100 and +200 would need a clear head if we did not also store the signed discriminant.

**Comment by JohnCremona** [comment]
It is worse since neither signD nor local_data are in the search table, they are in the extra table, so they cannot be searched for at all, neither can they be displayed in the search results, since (as far as I can tell) only columns in the search table are available to fill that template.

For the same reason the search results table cannot now show the equation since the 'equation' column is in extras,  (Is there a better way to find out which columns are in which table than db.ec_curves.lucky(projection=1).keys()?)

I have removed the "good first issue tag" since anything which requires redesign of the stored tables to be implemented is definitely not appropriate.

**Comment by edgarcosta** [comment]
@JohnCremona, that makes  sense. Also, please try:
```
db.ec_curves._extra_cols
db.ec_curves._search_cols
```

@AndrewVSutherland, I totally hijacked the thread, please ignore all my comments above.

**Comment by JohnCremona** [comment]
> @JohnCremona, that makes sense. Also, please try:
> 
> ```
> db.ec_curves._extra_cols
> db.ec_curves._search_cols
> ```

Thanks, I always forget to look for underscore attributes.  these two should perhaps be more visible.

> 
> @AndrewVSutherland, I totally hijacked the thread, please ignore all my comments above.

**Comment by roed314** [comment]
@JohnCremona I agree.  See https://github.com/LMFDB/lmfdb/pull/3391

**Comment by jwj61** [comment]
Number fields stores the absolute discriminant and the sign separately, so the infrastructure is already there if you wanted to support a search of -100..200 is already there.  Of course, you would need to copy the sign from the extras table to the main table.

**Comment by JohnCremona** [comment]
I have the abs(discriminant) ready to upload for conductors up to 500000, but before I do I want t make sure that the 'numeric' type is OK for these.  So far the largest is 279366.b1 with |D| = 1280883472583452943149920097876822944727009591296 = 2^40 * 3^28 * 101^10 * 461 which is 160 bits.

**Comment by JohnCremona** [comment]
OK, there is a new column in ec_curvedata called absD which (so far) has been filled for conductors up to 500k.  I'll do the rest soon.  I added an index on this.

**Comment by JohnCremona** [comment]
In my branch ECQ-disc-search I added search by discriminant, and also now show the discriminant in the search results table.  I could make a pull request it's not really ready yet: in both the main search page and the refine search page, the layout needs improvement.  Perhaps I should just add search by Faltings height to get back to an even number of search boxes.

**Comment by AndrewVSutherland** [comment]
Column-selection on search results throughout the LMFDB is coming soon and should address this issue.

**Comment by roed314** [comment]
This is now live on beta and I've ported the column requests to #4921, so I'm closing this issue.
