### ISSUE TITLE
Higher genus curve causes test failures

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3396]
The url

  http://beta.lmfdb.org/HigherGenus/C/Aut/3.12-3.0.2-2-3-3.1

does not contain 'Dimension of the corresponding', so if this page comes up in the random test for the test suite, it fails.  There may be other examples, but here's one.

**Comment by jenpaulhus** [comment]
I am thoroughly confused about why this test failure is only showing up now.  Those words "Dimension of the corresponding..."  were removed with a pull request back in summer of 2018:  https://github.com/LMFDB/lmfdb/pull/2543

Why that test did not fail until now, I don't understand.

Regardless, that one test can be removed since I've removed the corresponding data from the pages. I will try to make that change soon, but I'm fighting a start_lmfdb issue right now.  So if that test is causing bigger issues, you have my blessing to just remove it.
