### ISSUE TITLE
Make all code work with python3 

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3426]
The current Sage release 8.9 supports Python3, and the next release 9.0 which will be released soon will have Python3 as standard.

Running pyflakes3 on the lmfdb/ subdirectory shows 31 issues, which will need to be fixed.  It is not hard.

**Comment by JohnCremona** [comment]
Thanks that's very helpful.

I did start on this a while ago and may even have a python3 branch bitrotting somewhere.  I did fix Bober's DirichletConrey package but he has not yet merged the pull request.

**Comment by edgarcosta** [comment]
What if we use something a bit more advanced than pyflakes? for example pylint?
I tried it out but got overwhelmed with the amount of "errors" in either version, see: [pylint3](https://gist.github.com/edgarcosta/fe447b3bd9c2af51c2f087ce6237b978) [pylint](https://gist.github.com/edgarcosta/9d13ada32c0ea7d37a01175c3184e34d)

**Comment by pascalmolin** [comment]
Le mar. 29 oct. 2019 à 18:07, David Lowry-Duda <notifications@github.com> a
écrit :

>
>    1.
>
>    I think one of the first things I touched in the LMFDB depended on
>    old-style class behavior, but I can't seem to remember it --- perhaps I'm
>    imagining it.
>
> There are double inheritances in WebCharacters, is this what you have in
mind? I think the code does not rely on inheritance order, but I did not
look at other differences in python 3 behavior.

Pascal

>

**Comment by fchapoton** [comment]
This is indeed not so easy. Do you have good doctests ?

I would suggest first to fix what can be found using pyflakes and the suggestion below (namely print, xrange and so on). Then switch to relative imports everywhere. Then add "from __future__" imports. And then only run the code to see if it works.

Suggestion : There is another (better ?) way to find python3-incompatible code, using the command line

python3 -m py_compile

on each python file.

Reference : https://wiki.sagemath.org/Python3-compatible%20code

**Comment by fchapoton** [comment]
and one should use the python3-version of pyflakes, which finds more issues

**Comment by fchapoton** [comment]
I have made 6 pull requests that just adapt the behaviour of print.
They also make a few very minor other python3 syntax changes in the modified files.
Please review and merge !

**Comment by AndrewVSutherland** [comment]
@fchapoton Thanks for the PRs!  In answer to your question, no we do not have good doctests, which means we need to be very cautious about making global changes, especially changes to code such as scripts that is rarely used (and may not even be in working state now).

I think your print changes are a.most certainly safe, but I am concerned about changes to scripts, simply because we have no good way to test them -- they are typically run only when new data is being added to the LMFDB.  These events may be separated by years, and it is not uncommon for the scripts to require minor tweaks to make them work correctly again, either due to changes in the LMFDB that have occurred since they were last run, or changes in the format/source of the input data.  For the scripts I think it is better to wait to make them python3 compatible until the need to run them arises (and for some of them it may well never arise -- if they were written to upload a specific data set they might never be used again).

I don't think we should merge code that has not been tested; even though the changes look minor.  As soon as you add "from __future__ import ..." to any python module you have potentially changed its semantics (even if you make no other code changes).  For some of the PRs you have created, there may not be anyone willing to take the time to test them now (which will likely require a lot more effort than your code changes did), in which case we may need to close them -- I don't want to leave open PRs hanging around indefinitely.

But I will wait a few days for volunteers to emerge.

**Comment by JohnCremona** [comment]
If our test suite passes then surely the changes made to the website code are OK to merge (after human review of the changes too of course, but that is easy).  We can divide up this work.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I'm mostly concerned about changes to the scripts and data_mgt (three of the recently submitted PRs) that we don't have an automated way to test.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, one alternative is to stick to only changes in the `lmfdb` folder for now, and leave the changes in the `scripts` folder to the authors when they are forced to run their scripts with python3 (I can revert the PR that I merged.)

**Comment by fchapoton** [comment]
I would like to advocate that:
(1) These changes to print are completely harmless.
(2) I have checked all the modified files with python3  -m py_compile : they do no longer contain any incompatible print and all my changes are syntactically correct.
I understand that you are very cautious. It seems to me that a careful human check of the diff should be sufficient to make sure that there is no risk of breaking anything.

**Comment by roed314** [comment]
I'm happy to check Frédéric's code changes in a few days.  I agree that they should be harmless.

**Comment by fchapoton** [comment]
Looking at the remaining pyflakes warning, I see that you are using "basestring" a lot. But "basestring", which was a common class for "bytes" and "str" in Python2, no longer exists in Python3. The usual suggestion is to replace by "str". Another possibility is to follow 
```
The builtin basestring abstract type was removed in python3,
use str instead, we need to use six.string_types to replace
the basestring for py3 compatibility.
```
This obviously requires input from people who  knows what lmfdb is doing inside.

**Comment by fchapoton** [comment]
does it make sense to replace the two calls to "long(...)" in lines 509 and 510  of ./lmfdb/classical_modular_forms/main.py by ZZ(...) ?

**Comment by AndrewVSutherland** [comment]
For line 509 it makes perfect sense.  For line 510 I think the ZZ will (eventually) be converted to a 64-bit postgres BIGINT, but this seems to work fine

`sage: db.mf_newforms.lucky() == db.mf_newforms.lucky({'trace_hash':ZZ(db.mf_newforms.lucky()['trace_hash'])})

True
`

**Comment by edgarcosta** [comment]
I agree with @AndrewVSutherland regarding lines 509 and 510.
Regarding, `basestring` I think the reason we stuck with it is because of unicode strings:
```
>>> isinstance('maria', str)
True
>>> isinstance(u'maria', str)
False
>>> isinstance(u'maria', basestring)
True
```

**Comment by edgarcosta** [comment]
@fchapoton, I think we can replace base string with six.string_types

**Comment by fchapoton** [comment]
yes, sure. Will you do that ?

Le jeu. 12 déc. 2019 à 14:49, Edgar Costa <notifications@github.com> a
écrit :

**Comment by fchapoton** [comment]
I have made a pull request for six.string_types instead of basestring.

Beware that you are using a lot of file loading and saving, and Python3 is much more strict on what you manipulate. I cannot predict if things will work smoothly or not under python3.

**Comment by fchapoton** [comment]
I think that a reasonable objective would be to switch the current check for pyflakes warnings  to use the python3 version of pyflakes. There remains a single issue in the lmfdb folder, about buffer, that should be fixed by someone knowing the code better than I do. There are also several remaining warnings in the scripts, that should also be fixed, probably, before one can use pyflakes under python3.

**Comment by edgarcosta** [comment]
@fchapoton Thank you for taking care of the strings and all the other things!
I will try to fix the buffer issue ASAP.
Once that is done, feel free to edit .travis.yml accordingly.

**Comment by edgarcosta** [comment]
I have fixed all the remaining pyflakes errors in python3, and I have just
changed travis to use pyflakes under python3.

@fchapoton, I'm also happy to add pylint to Travis once we get things under
control.

**Comment by fchapoton** [comment]
There remains a large-scale issue : conversion to absolute imports.
Maybe 2to3 could help, see https://docs.python.org/2/library/2to3.html#2to3fixer-import

**Comment by edgarcosta** [comment]
I have built Sage-9.0 for Travis.
Whenever we are ready, we can switch
https://github.com/LMFDB/lmfdb/blob/master/.travis.yml#L44
to 9.0

**Comment by davidlowryduda** [comment]
@edgarcosta Generically it's possible for travis to run tests on multiple frameworks, right? But for us, we run rather close to the time limit and so it is perhaps not possible to run both sage-with-python-2 and sage-with-python-3 tests. Is my interpretation correct?

**Comment by edgarcosta** [comment]
Good point. I will do that.
Now I just need to fix that the annoying SSL dependency that sage can't
figure out that pip needs it.

**Comment by JohnCremona** [comment]
For pip you have to install a package for python3 which probably already
have for python2.

I had to do this on Warwick servers.  Travelling now but can say more later
if more hints needed.

**Comment by edgarcosta** [comment]
I got it to work. But all of our tests fail because the test client returns
byte strings.
So all our tests must be modified.

**Comment by edgarcosta** [comment]
FYI, Travis is now ready to [use 9.0](https://github.com/LMFDB/lmfdb/blob/master/.travis.yml) but we are still very far away from making all tests pass on both

**Comment by edgarcosta** [comment]
beta.lmfdb.org is now running 9.1

**Comment by edgarcosta** [comment]
www.lmfdb.org is now running sage 9.1, and therefore we should close this issue
