### ISSUE TITLE
Simplify polynomial and power series display

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#3444]
A lot of objects that are displayed in latex as sums with many terms (e.g. q-expansions, certain polynomials) are currently implemented as a sequence of short tex strings rather than one long one (i.e. $x^3 + x+ 1$ becomes $x^3$ $+ x$ $+ 1$). If I remember correctly this was done to ensure they would overflow onto the next line gracefully when too wide for the screen or container.

This leads to a couple of annoyances, either the spacing around the plus is a bit off (in q-expansions), or we added $\mathstruts$ everywhere, and if someone copies the tex code from a page they get a string with a bunch of mathstruts in.
The most important issue (to me) is that selecting by clicking and dragging and copy-pasting is a bit weird. The user will copy a string with many short latex blocks in as we coded it which they likely do not want, this makes it hard to paste things directly into a tex document or CAS without editing a lot.

I have done some preliminary checking and it seems like KaTeX handles the overflow problem well for inline math, and the above hacks are not really necessary, so I propose to remove them. 

After this change clicking once on a q-expansion say selects the whole thing which can be copied and pasted directly into a latex file.

One potential downside is this may cause some things to hit the katex string too long issue we saw #3201 , but I think that is unlikely to happen anywhere (those fundamental units were BIG) note we have the auto-knowling of large numbers in q-expansions anyway, which does still break apart the string.

**Comment by davidfarmer** [comment]
I see two problems:  how to make the display look good, and how to enable
the user to select LaTeX code that they can paste somewhere.

In the past it was impossible to satisfy both requirements with the same
text string.  We (correctly!) gave priority to the appearance, because
LMFDB is a website and we do offer download options.

I speculate that it is still impossible, it's just that the compromises
will not be as bad.  But maybe we don't have to compromise.  We can have
javascript that causes copying to actually copy some alternate text
hidden in the page.  That way, we can optimize each version separately.

I can elaborate or do a mockup if the above is not clear.

And by "speculate" I mean "am absolutely sure"

**Comment by alexjbest** [comment]
@davidfarmer I have made this change in PR #3445

Can you elaborate what you mean if you do see some issue there, you sound very sure.
We already do have the copy-tex javascript plugin for katex which is what makes this all nice.

There is one issue I'm aware of with the katex copy-tex plugin where it can accidentally copy things in a hidden div https://github.com/KaTeX/KaTeX/issues/1981 but I don't think that this is really relevant here, and this change also mitigates that issue somewhat, the user can now just click the q-expansion to select the whole thing rather than click-dragging.

**Comment by davidfarmer** [comment]
I guess what I meant is that I think it very likely that some place
for one of the many LMFDB objects, someone will want to adjust
the LaTeX to address a particular display issue.

But if we can't find a particular example now, and it is the same
work to fix it later, then I don't have a specific objection.

**Comment by alexjbest** [comment]
My previous implementation had a bug, new PR #3446 .

**Comment by alexjbest** [comment]
PR #3446 was merged.
