### ISSUE TITLE
Citations need to be updated

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#3450]
https://www.lmfdb.org/citation/citations
Hasn't been updated since 2017.
We should update it.

Does anyone have any ideas how to automate this?

**Comment by JohnCremona** [comment]
I set this up a few years ago, and then Nicolas Mascot maintained it until he left in 2017.  Since then I have been looking for someone to take over  updating it, which only takes about 10 minutes every couple of months, with a larger investment neede right now as there are 2 years of citations waiting to be added.

The list is maintained at https://github.com/LMFDB/citations (see the README and Makefile there).

The steps are as follows (in outline):
   - Use Google Scholar alerts to get an email whenever a paper appears anywhere online (including ARxiv) mentioning the LMFDB.  Check manually that it is relevant and use Google Scholar's links to get a bibtex reference.  Paste that into the file citations.bib.
   - The Makefile creates new html files which need to be checked manually and then copied to the main LMFDB repository (there are two such files) and the small file containing the date of update needs updating before a normal PR is made.

Checking my inbox, I have about 100 alerts from Google Scholar needing to be worked on.  This would definitely be less work than starting from scratch.

I was unable to automate the first step.  Google does not (apparently) make it possible to get the bibtex reference for more than one thing at a time.  Then, bibtex2html does not do a perfect job and frequently the html needs manual tweaking.  Also, one has to manually eliminate repeats (when a preprint we already list is published in a journal we replace the citation).

When I was doing this I would also email the authors of any preprints who did not cite the LMFDB properly, and in many cases this led to an updated better version.  Google Scholar will tell of of papers which have LMFDB anywhere in the text, not just on the list of citations.

**Comment by jvoight** [comment]
Another option would be to replace the long citation list with a curated list of our favorite LMFDB applications and just a graph indicating the number of citations over time, scraped from Google scholar.

**Comment by jwj61** [comment]
We replaced the citation page with a link to LMFDB's google scholar profile.
