### ISSUE TITLE
Bug rendering torsion structure for E/Q of conductor >= 400,000

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3770]
From the feedback page:

There seems to bit a bit of an issue on the "Elliptic Curves Search Results" page. For elliptic curves over Q with conductor >= 400,000, the torsion structure renders incorrectly (on my browser, at least). For instance, a curve with torsion subgroup Z/2Z should have torsion structure rendered as [2] here but rather the structure is listed as [u'2']. This bug does not appear for curves with conductor < 400,000, as far as I can tell. Also, there does not appear to be any bug on the curve's specific page, but rather only on the search result page.

Respond to jmayle2@uic.edu

**Comment by JohnCremona** [comment]
This duplicates something in #2977 which I reopened for this specific issue.  It is probably best to re-close that and use this one.  I'll copy my post from there to here.

**Comment by JohnCremona** [comment]
Quoted from #2977:

Reopening since (for example) https://beta.lmfdb.org/EllipticCurve/Q/?conductor=400000-400100 shows the integers in the torsion structure as strings with quotes and even the unicode u symbol. It seems that this is the case for conductors > 400000 so is some artifact of the data upload after the mongo-postgresql switch. Note also that
'''
sage: db.ec_curves.distinct('torsion_structure')
[[],
[u'12'],
[u'2'],
[u'3'],
[u'4'],
[u'5'],
[u'6'],
[u'7'],
[u'8'],
[u'9'],
[2],
[3],
[4],
[5],
[6],
[7],
[8],
[9],
[10],
[12],
[u'2', u'2'],
[u'2', u'4'],
[u'2', u'6'],
[2, 2],
[2, 4],
[2, 6],
[2, 8]]
'''
A simple rewrite will do the trick. Can @vishalarul or someone else do this?

and from @jvoight : 
The curve
https://www.lmfdb.org/EllipticCurve/Q/453882/w/1
has torsion structure [u'2'], so is an example that needs to be fixed.

**Comment by edgarcosta** [comment]
On it.
