### ISSUE TITLE
Link from www.lmfdb.org redirects to beta

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#3849]
From the Bug Report page:  In the frontpage (lmfdb.org), under "A Database", there is a link to "Tables of zeros" and when I click on it, it takes me away from lmfdb.org to beta.lmfdb.org. I am not sure if this is by design, but just wanted to point it out, because after that, I stay in beta as I click around. Thanks!

**Comment by JohnCremona** [comment]
The URL www.lmfdb.org/zeros/zeta works fine but www.lmfdb.org/zeros/first redirects to beta.

**Comment by AndrewVSutherland** [comment]
This is a bug (the link should go to www.lmfdb.org/zeros/zeta).  I also think we should reconsider the list of links in that box, but to address this issue we just need to fix the link -- i can do this today.

**Comment by AndrewVSutherland** [comment]
This is now fixed on master, I'll push it to dev and web later today.

**Comment by JohnCremona** [comment]
@AndrewVSutherland Was this a code problem?  I looked but could not see anything obvious.  Or was it that some files had to be copied to the production server?  (Either way, this could have been an issue for a long time.)

**Comment by AndrewVSutherland** [comment]
The link www.lmfdb.org/zeros/first is actually doing exactly what it should, which is to redirect to beta, because the first zeros functionality is still in beta (and it should stay there until we complete all the L-function work we have planned for version 1.2 / 2.0, pre-computing all the L-functions and rigorously computing the lowest zeros for each of them).

The exact same thing will happen if you try to access

https://www.lmfdb.org/ModularForm/GSp/Q/

for example, because Siegel modular forms are also still in beta.  Recall that we made this change last year to prevent people browsing beta sections of the LMFDB while on the production site.

**Comment by AndrewVSutherland** [comment]
This is now fixed on www.lmfdb.org.
