### ISSUE TITLE
Slider for degree-1 L-function browse page broken on Chrome

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3852]
When using Chrome (or Brave or Chromium) the slider on

https://www.lmfdb.org/L/degree1/

is not working correctly.  Setting it to values above 20 does not change the display, and setting it to values N below 20 truncates the graph in the wrong way (it seems to cut off the L-functions whose conductor is less than 20-N, which is bizarre).

This problem is browser specific, it does not occur on Firefox.

**Comment by AndrewVSutherland** [comment]
Can someone with a Mac check this on Safari?

**Comment by alexjbest** [comment]
Works fine on safari but broken as reported on chrome on mac.

**Comment by alexjbest** [comment]
The problem is that changing the src of an embed (like this svg) does not reload it in chrome. 

https://stackoverflow.com/questions/2493706/javascript-changing-src-attribute-of-a-embed-tag

it seems the recommended fix is to instead remove and reinsert the embed on the slider change.

The graph never changes and the apparant trunction is the slider adjusting the height to match what it expeects the heeight of the reloaded elemeent will be.
