### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3920]
When starting a webserver with 

sage -python start-lmfdb.py --debug 

the debug flag seems to have no effect.  It does not reload when a file is changed, and it does not give the stack track in the browser window when there is an exception from the code.

**Comment by edgarcosta** [comment]
I can't test it right now, but I believe that what is happening is that the
config file is (wrongly) overwriting the command line arguments, thus
setting degub=true in the config file might be a workaround for the moment

**Comment by jenpaulhus** [comment]
This has been happening for me for several weeks. The errors are now displayed in the terminal window so I had assumed it was "working as intended".

**Comment by AndrewVSutherland** [comment]
Removing the debug line from config.ini fixes the problem, this will make the command line --debug parameter work again.

To sum up, there are currently two options:

- Set "debug=True" in your config.ini if you want to always run in debug mode no matter what.
- remove the "debug=..." line from your congi.ini if you want to control this at the command line via --debug

I am going to remove "debug=False" from the config.ini file so that new developer's won't be impacted by this (there is no benefit go setting debug=False in config.ini, this is default behavior).

It should always be clear which mode you using (on the server it sill say "Debug mode: on/off" and on the client you will see beta if and only if you are in debug mode).

I'm not sure what caused this change in behavior (it may well be something in Sage), but I don't think it's worth spending a lot of time trying to figure it you (yes the behavior changed, but whether or not config.ini settings should take precedence over command line parameters is not completely obvious to me, I can imagine scenarios where I would want config.ini to take precedence).

**Comment by jwj61** [comment]
Sounds good

**Comment by AndrewVSutherland** [comment]
I removed the line "debug=False" from all the config.ini files on legendre.
Two developers have debug=True set (jenpaulhus and jvoight), they will always run in debug mode; everyone else will run in non-debug by default but can turn debug mode on using "sage --debug start-lmfdb.py"

**Comment by edgarcosta** [comment]
Thanks, Drew.
> yes the behavior changed, but whether or not config.ini settings should take precedence over command line parameters is not completely obvious to me, I can imagine scenarios where I would want config.ini to take precedence

Originally I wrote the code for the command line arguments to take precedence over the config file.
I happy to look at it if we ever believe that should be the desired behavior.
