### ISSUE TITLE
Include query-info in downloads

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#3971]
Downloaded data does not always contain the query info, e.g. for elliptic curves and number fields; it does so however for classical modular forms.
 
It would be very convenient if it was always mentioned in some way, perhaps as a comment (one that would be easy to parse), a link to the lmfdb query (if it will work permanently), or as an additional variable (e.g. a dict for sage).

**Comment by AndrewVSutherland** [comment]
This should be implemented in conjunction with #4933 @roed314

**Comment by roed314** [comment]
This will mostly be addressed in #5702.  It would be nice to also include a link to the search results page that produced the download, but this is tricky because when we're constructing the download we're not serving the original search results page so we don't have direct access to its url.
* We do have access to a query dictionary, like `{'motivic_weight': 2, 'analytic_conductor': {'$gte': 0.4355, '$lte': 0.4365}}`, but reconstructing the search input that produced that query is nontrivial, though maybe possible with enough work.
* We could modify the download link to also include the current contents of the form, from which a url could be constructed pretty easily.  This would be a lot more feasible, but I think not worth the effort.

**Comment by roed314** [comment]
Never mind, I think I'm going to have to implement the second option in order to resolve #5091.  So this issue should be completely resolved with #5702.
