### ISSUE TITLE
Search on projective image type for Artin representations yields no results

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#4093]
See https://beta.lmfdb.org/ArtinRepresentation/?projective_image_type=Dn&search_type=List

**Comment by jwj61** [comment]
After fixing a small logic error in the code, it is having a database query error.  The issue is that it want to see if a field stored as integer[] is in a list, so it is generating
"Proj_GAP" = ANY(ARRAY[ARRAY[4,2],ARRAY[6,1],ARRAY[8,3],ARRAY[10,1],ARRAY[12,4],ARRAY[14,1],...

This does not seem to be legal SQL for postgres.  Thoughts on how to get it to make the right syntax?

**Comment by roed314** [comment]
I think the right answer might be to use strings rather than arrays of length 2.  But I will try to see if I can get something to work using the current column type.

**Comment by edgarcosta** [comment]
@jwj61, I tried hard and couldn't figure out a workaround.

Logically, I would just write it with a bunch of ORs

**Comment by roed314** [comment]
Fixed by #4097.
