### ISSUE TITLE
Rewrite not updating the stats table

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#4119]
It looks like rewrite is supposed to update the corresponding statistics table by default.  I just did a rewrite on the transitive group database which ended with lots of messages like:

INFO:gps_transitive@2020-10-12 14:29:32,851: Statistics already exist
2020-10-12 14:29:32,852 - Statistics already exist
2020-10-12 14:29:32,852 - Statistics already exist

However, when I look at the statistics page, the relevant values had not changed.  I clicked on an entry, had it do the count, and it confirmed that the count on some item had changed.

On a related note, I know I was told before how to update statistics directly, but still have trouble getting it to work.  Perhaps it should go in the faq.  I would expect db.gps_transitive.stats.refresh_statistics() to do it, but that isn't it.

**Comment by jwj61** [comment]
OK, I just saw that I was giving the wrong command, that it is refresh_stats().  But still, rewrite should do it for me.

**Comment by roed314** [comment]
The rewrite function should be calling `refresh_stats`, but we've seen that it doesn't update for a while after changes are made.  @edgarcosta and I don't really understand why this is happening.

In addition to an update to the FAQ (which I agree is a good idea), I'll have `refresh_stats` print out a message when it runs.  Then at least we can determine whether the problem is something with gunicorn caching or that there's a bug causing the statistics to not get refreshed.

**Comment by roed314** [comment]
See #4120

**Comment by roed314** [comment]
I'm not sure what else we should do now for this issue.  If there's another instance where `rewrite` fails to update stats, there should be some more print statements due to #4120.  Maybe close this issue and reopen if we see it again?

**Comment by jwj61** [comment]
Sure.  The most recent time I did a rewrite, the stats did update.
