### ISSUE TITLE
BMF data - Mismatch between LMFDB and Magma for dimension 2 forms

### ISSUE THREAD

**Issue by BarinderBanwait** [LMFDB/lmfdb#4170]
There appears to be a discrepancy between the BMF eigenvalues for dimension 2 forms in the database, and what Magma computes.

E.g. Consider form [1066.4-a2](https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/1066.4/a2/). The eigenvalues at the two primes above 5 are ostensibly the same, but the following Magma code shows that there are no BMF newforms of this level with the property that its two eigenvalues above 5 are the same:

```
P<x> := PolynomialRing(Rationals());
g := P![1, 0, 1];
F<i> := NumberField(g);
ZF := Integers(F);

NN := ideal<ZF | {-15*i -29}>;

M := BianchiCuspForms(F, NN);
S := NewSubspace(M);
NFD := NewformDecomposition(S);
newforms := [* Eigenform(U) : U in NFD *];

print "Are the Hecke eigenvalues at the two primes above 5 equal, for any newforms of this level?";

P1, P2 := Explode(Decomposition(ZF,5));

for f in newforms do;
 print HeckeEigenvalue(f,P1[1]) eq HeckeEigenvalue(f,P2[1]);
end for;
```

If this discrepancy indeed exists, then it could well be an issue with Magma. Either way, this ought to be investigated.

This was noticed in testing for #4053.

**Comment by JohnCremona** [comment]
The original data for these (few) dim 2 bmfs were computed in magma in the first place. I suggest consulting Ciaran S who provided that data.

**Comment by JohnCremona** [comment]
I ran this level on my C++ code (bianchi-progs on github).  At this level there's a rational newform and dimenesion 2, no oldforms.  The eigenvalues of the dim 2 newforms at the primes above 5 are negative-conjugate to each other, so if you call one 1+z (where z^2=-7) then the other is -1+z.    

So the data displayed for the dim 2 newforms is wrong.  *But*  the magma code listed here does not show that. since newforms[1] is the rational eigenform (who eigenvalues at these two primes are 0 and -2) while newforms[2] is the dim 2 one, and its eigenvalues are listed as $.1 and $.1-2 which is correct if you take $.1 to be a root of x^2+2x-6.

Conclusions:  (1) Magma is not wrong; (2) There was a bug in the code which output the Magma eigenvalues to data files whcih were uploaded to the LMFDB; (3) the test posted here was nt testing what its author thought it was.

**Comment by BarinderBanwait** [comment]
Thanks for looking into this @JohnCremona!

**Comment by JohnCremona** [comment]
I suggest that we delete the dimension 2 BMFs.  There are very few of them (219, all dim 2 over Q(sqrt(-1)) and if we do want to include higher-dimensional BMFs we should try to cover at least all 5 fields for which we have dim 1 forms, and include higher dimensions (none of them will be large, not like classical or HMFs -- that's the way with BMFs).

I don't think much would need changing, though the Dimension search box could obviously be removed from the search and search-again pages.

All it would take is to change a few characters in the last command here:

`sage: db.bmf_forms.distinct('dimension')`
`[1, 2]`
`sage: db.bmf_forms.count({'dimension':1})`
`185581`
`sage: db.bmf_forms.count({'dimension':2})`
`219`

**Comment by JohnCremona** [comment]
I am planning to fix this by simply hiding the small number of dimension 2 forms, by which I mean that I will not delete the tables but will adjust the interface so dim>1 is not on offer.  When fixed, there will be completeness knowls to be changed too.
