### ISSUE TITLE
Galois orbits for Dirichlet characters

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#4172]
We should make pages for Galois orbits of Dirichlet characters!  This is how we think and use them for classical modular forms, and indeed the analogy is good: the first organizational principle is on Galois orbits, then we think about their complex embeddings.  (Anything we currently search on for Dirichlet characters is well-defined on the Galois orbit.)

**Comment by BarinderBanwait** [comment]
I've got a prototype version of Galois orbits live at the pink branch; e.g. [Galois orbit 6500.el](https://pink.lmfdb.xyz/Character/Dirichlet/6500/el).

Before proceeding with a PR, could I ask for some community feedback from an end-user perspective? Is this the information we want to display on this page? Is there anything else we want to show?

It's very much a version 0.1 at the moment; I spent a few minutes clicking on random links between Dirichlet Group/Dirichlet Orbit/Dirichlet Character, and didn't find any breaks; but I can't guarantee that it's free of bugs! So please let me know of them as and when you encounter them!

Some remarks:

1. Dirichlet characters now have three parts to the url; Modulus, Orbit label, and Conrey number. However, the current functionality still works; that is, specifying the orbit label is not necessary. 

2. As discussed during one of the Friday sessions, there are two types of breadcrumbs, one for modulus > 10,000, where the orbit label isn't a crumb, and one for modulus <= 10,000, where it is.

**Comment by davidfarmer** [comment]
This looks like a good start on the home page of a Galois orbit.
Some small comments:

The word "character" should be at the top of the page:
Dirichlet character orbit 6500.el

The link from a character to its orbit is in the page,
but should also be under "Related objects"

I am interested to read about the labeling.  Looking at a few
examples did not enable me to figure out how the orbits are
enumerated.

The two sentences above the table can be said more concisely.
Maybe nothing needs to be written at all?  Maybe that subtitle
should include "in the orbit"?

You said that the Dir char URL includes the orbit,
but I did not see that.  But why is that desirable?
If
Character/Dirichlet/6500/283
and
Character/Dirichlet/6500/el/283
are the same, the first seems better.  And I find the second
to be confusing, even though I understand it.

I did see the orbit in the breadcrumbs, which I thought
was good.

**Comment by BarinderBanwait** [comment]
Great, thanks for your feedback @davidfarmer !

> The word "character" should be at the top of the page:
Dirichlet character orbit 6500.el

Done! Live on pink!

> The link from a character to its orbit is in the page,
but should also be under "Related objects"

Done! Live on pink!

> I am interested to read about the labeling.  Looking at a few
examples did not enable me to figure out how the orbits are
enumerated.

Hmmm, good question. The database `char_dir_orbits` contains the labels for the orbits, both in the form Modulus.Number and Modulus.Letter, where 'Number' and 'Letter' are related via `cremona_letter_code` from John's `sage.databases.cremona`; but indeed on quick glance I also can't see how the galois orbits are labelled. This ought to be put onto the [respective knowl](http://www.lmfdb.org/knowledge/show/character.dirichlet.galois_orbit).

> The two sentences above the table can be said more concisely.
Maybe nothing needs to be written at all?  Maybe that subtitle
should include "in the orbit"?

Done! Live on pink!

> You said that the Dir char URL includes the orbit,
but I did not see that.  But why is that desirable?
If
Character/Dirichlet/6500/283
and
Character/Dirichlet/6500/el/283
are the same, the first seems better.  And I find the second
to be confusing, even though I understand it.

The orbit is an optional component to the URL if modulus and number are specified; so indeed, those two links go to the same page. So, too, does 'Character/Dirichlet/6500/banana/283', but with a warning to the user that the specified Galois orbit was incorrect.

My understanding of the URL behaviour requirements, based on various Friday discussions, are summarised as follows:

1. Character/Dirichlet/10000 --> Dirichlet Group of order 10,000
2. Character/Dirichlet/10000/cw --> Dirichlet Orbit 10000.cw
3. Character/Dirichlet/10000/banana --> Error, go to navigation page
4. Character/Dirichlet/10000/17 --> Dirichlet Character 10000.17 
5. Character/Dirichlet/10000/cw/17 --> Dirichlet Character 10000.17
6. Character/Dirichlet/10000/banana/17 --> Dirichlet Character 10000.17, but with warning to user
7. Character/Dirichlet/10001/17 --> Dirichlet Character 10001.17
8. Character/Dirichlet/10001/anything/17 --> Dirichlet Character 10001.17, but with warning to user
9. Character/Dirichlet/10001/anything/ --> Error that we only have Galois orbits, go to navigation page

However, please do let me know if it should be otherwise.

> I did see the orbit in the breadcrumbs, which I thought
was good.

Thanks!

**Comment by davidfarmer** [comment]
> Hmmm, good question. The database char_dir_orbits contains the labels for the orbits, both in the form Modulus.Number
> and Modulus.Letter, where 'Number' and 'Letter' are related via cremona_letter_code from John's
> sage.databases.cremona; but indeed on quick glance I also can't see how the galois orbits are labelled. This ought to
> be put onto the respective knowl.

The Galois orbit of a Dirichlet character knowl is not the place
to describe the orbit labels.  There should be a separate page for
Dirichlet character orbit labels, analogous to:

https://pink.lmfdb.xyz/Character/Dirichlet/Labels

That would then be part of the "Learn more about" properties box.

I was impressed that Character/Dirichlet/6500/el/113 gives
feedback that the orbit label is wrong, and that ej is the
correct orbit label.

Currently the link to a character does not have the orbit
in the URL.  I think it should be that way, so our preferred
URLs omit the orbit.  I don't think it is necessary to
rewrite the URL with orbit to the URL without orbit.
But at present there does not seem to be a way to click around
the site and have the orbit in the URL of a character.

But, maybe
    Character/Dirichlet/6500/el/113
should get rewritten as
    Character/Dirichlet/6500/ej/113

**Comment by BarinderBanwait** [comment]
> The Galois orbit of a Dirichlet character knowl is not the place
to describe the orbit labels.  There should be a separate page for
Dirichlet character orbit labels, analogous to

Yes ok, I agree - perhaps even the information for orbit labels could also go on that page you link to?

> I was impressed that Character/Dirichlet/6500/el/113 gives
feedback that the orbit label is wrong, and that ej is the
correct orbit label.

Thanks! I might refine the wording of those messages before opening the PR.

>But, maybe
    Character/Dirichlet/6500/el/113
should get rewritten as
    Character/Dirichlet/6500/ej/113

Aah yes that's a good point; I'll ensure that's part of the PR.

**Comment by davidfarmer** [comment]
>       The Galois orbit of a Dirichlet character knowl is not the place
>       to describe the orbit labels. There should be a separate page for
>       Dirichlet character orbit labels, analogous to
> 
> Yes ok, I agree - perhaps even the information for orbit labels could also go on that page you link to?

I suggest a separate page.  The new page can be short, because you can 
refer to the other page.

**Comment by BarinderBanwait** [comment]
> I suggest a separate page.  The new page can be short, because you can
refer to the other page.

OK sure! Will do!

**Comment by AndrewVSutherland** [comment]
This is now live on www.lmfdb.org
