### ISSUE TITLE
Server error on bad j-invariant search input for ECNF

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4234]
When searching for elliptic curves over number fields by j-invariant, entering a field and then an invalid j-invariant (e.g. "banana") results in a server error:

    https://www.lmfdb.org/EllipticCurve/?count=None&hst=List&field=2.2.5.1&jinv=banana&search_type=List

To reproduce go to https://www.lmfdb.org/EllipticCurve/ and enter "2.2.5.1" (or any valid field label) into the base field and "banana" into the j-invariant field.

EC/Q and G2C/Q both pass the banana test so this would appear to be specific to the search parsing/validation that is being done on the ECNF page (where the j-invariant is an algebraic number not just a rational number or list of rational numbers).

**Comment by JohnCremona** [comment]
I have never liked this feature anyway, since we really don't have a good way for users to enter algebraic numbers.

While testing this I noticed that the (random example) page  https://www.lmfdb.org/EllipticCurve/2.2.5.1/2581.2/a/1 has malformed latex equation.  In this case it is because the generator \phi is concatenated with x, and this error is in the database entry so it is not a code problem.  I'll raise an issue and solve it.
