### ISSUE TITLE
Data quality for L-functions

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#426]
Presumably should appear on http://www.lmfdb.org/L/degree1/

**Comment by jvoight** [comment]
This is really a question about all L-functions, how do we describe their RCS knowls?  We can link to the RCS knowls from the provenance of the L-functions, or each L-function page could have a flag which gives several (or two) cases for the display of knowls.

**Comment by edgarcosta** [comment]
We could do both.
We could have a centralized knowl that includes all corresponding knowls per category, how it was computed.
And each  L-function could also point to the right category the corresponding to its Source and Reliability

**Comment by AndrewVSutherland** [comment]
Edgar, David, and I discussed this ealier today the plan is to add reliability and source knowl information to the lfunction database (via an intermediate table to avoid unnecessary duplication) that will be used to populate attributes of lfunction objects when they are created in the lfunction code.  The learnmoreabout box can then use these knowls and a standard dq.lfunc.extent knowl for completeness.

**Comment by jwj61** [comment]
Infrastructure is now in place.  Just need for all of the knowls to be written.

**Comment by AndrewVSutherland** [comment]
@davidfarmer @edgarcosta @arbooker Any help you can lend in filling out the stubs I created for these knowls would be much appreciated!  You can access the knowls directly by going to knowledge and searching for rcs.lfunction.* (using regex), and once #2928  is pushed to dev (within the day or two, I'm just waiting for a few more pending PRs to get merged) you can access them by clicking on links in the learnmoreabout box.

**Comment by AndrewVSutherland** [comment]
Work on this is in progress, I have received a lot of helpful information from @arbooker, @davidfarmer  and @edgarcosta (thank you!) that I will incorporate into the knowls tomorrow.

**Comment by jvoight** [comment]
This looks good!  We should add one paragraph to the top that explains the difference between "precomputed, with something rigorous" versus "computed dynamically, and may be inaccurate".  Then we can be more brief in the bullet points below them.

**Comment by AndrewVSutherland** [comment]
@jvoight This has been done.

There are now source and rigor knowls for all the different types of L-functions.  The completeness knowl is the same on every L-function page, but the source and reliability knowls vary depending on the type of L-function (there are 6 categories, "Dirichlet", "modular" (classical, Hilbert, or Bianchi), "maass form", "elliptic curve over Q", "genus 2 curve", and "dynamic"); this distinction has more to do with how and when they were computed than the mathematics.  You might suppose the elliptic curve L-function computations would be as rigorous and have as high a precision as the modular form L-functions, but except in cases where we actually have the modular form in the database, that is not true simply because the elliptic curve L-functions were computed much earlier, we plan to recompute them this summer). Note that there is not a separate category for elliptic curves over number fields because we only have L-functions for elliptic curves over quadratic fields, and these are all L-functions of Hilbert and/or Bianchi modular forms we have in the database.

Below are a list of pages that will let you see every variation of source/reliability knowl in different contexts.

http://beta.lmfdb.org/L/Character/Dirichlet/2396/343/
http://beta.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/3059/1/e/g/3058/1/
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.17.1/holomorphic/2.2.17.1-288.5-h/0/0/
http://beta.lmfdb.org/L/EllipticCurve/2.2.17.1/288.5/h/
http://beta.lmfdb.org/L/ModularForm/GL2/ImaginaryQuadratic/2.0.4.1/39650.5/d/
http://beta.lmfdb.org/EllipticCurve/2.0.4.1/39650.5/d/
http://beta.lmfdb.org/L/ModularForm/GL3/Q/Maass/1/1/16.40312_0.171121/-0.4216864/
http://beta.lmfdb.org/L/EllipticCurve/Q/377784/j/
http://beta.lmfdb.org/L/Genus2Curve/Q/698627/a/
http://beta.lmfdb.org/L/NumberField/3.1.367.1/
http://beta.lmfdb.org/L/ArtinRepresentation/3.643.4t5.1c1/

**Comment by AndrewVSutherland** [comment]
The knowls are now live on production (you can replace beta with www in any of the links above).  I welcome further comments on the knowls and edits/reviews of their content, but we now have rcs knowls on all L-function pages, so I am going to close this issue.
