### ISSUE TITLE
Add all automorphic friends of genus 2 curves

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#433]
We did this in Dublin, but we didn't have access to all of the classical modular forms we needed.

**Comment by jvoight** [comment]
For example, http://www.lmfdb.org/Genus2Curve/Q/169/a/169/1 splits into elliptic curves over QQ(sqrt(13)) (I think--certainly over the sextic totally real subfield of QQ(zeta_13)), so it should at least link to the HMF and probably also the elliptic curve.

**Comment by jvoight** [comment]
Also, http://www.lmfdb.org/Genus2Curve/Q/676/b/ is the square of an elliptic curve, but is missing the corresponding modular form for that elliptic curve.

**Comment by AndrewVSutherland** [comment]
In addition to missing automorphic friends, there are also some inconsistencies in the current data between what is listed in the curve pages, isogeny class pages, and L-function pages (see the following message from Dan Yasaki, for example).  I am working on fixing all the inconsistencies now and should have a fix ready later today.

> http://www.lmfdb.org/Genus2Curve/Q/1088/a/1088/1
> is a curve that is friends with two elliptic curves over a real
> quadratic field.  The isgoeny class
> http://www.lmfdb.org/Genus2Curve/Q/1088/a/
> is friends with no elliptic curves (or ec isogeny classes).

> Contrast that with
> http://www.lmfdb.org/Genus2Curve/Q/1696/b/434176/1
> which is a curve that is friends with two elliptic curves over an
> imaginary quadratic field.  The isogeny class
> http://www.lmfdb.org/Genus2Curve/Q/1696/b/
> is friends with the corresponding two elliptic curve isogeny classes.

> The curve
> http://www.lmfdb.org/Genus2Curve/Q/12500/a/12500/1
> is not friends with a HMF, but its isogeny class
> http://www.lmfdb.org/Genus2Curve/Q/12500/a/
> is friends with a HMF.

Doing a systematic match on the hashes of all relevant objects currently in the lmfdb (products of classical modular forms, products of elliptic curves over Q, Hilbert modular forms over real quadratic fields, and elliptic curves over real and imaginary quadratic fields) would not be difficult and is something I think should be fixed in Release 1.1.

**Comment by JohnCremona** [comment]
Thanks.  For the ones which link to curves over imaginary quadratic fields, note that I am in the process of trimming the labels so that where you now have "[N,c,d]" you will have "N.c.d".  If there is code (or data) in the genus 2 world which assumes the old labels, I'll take that into account when I finish this switchover (which will affect a lot more then just curves over IQFs).

I don't know what you mean by matching hashes of objects though.  I'm glad you think it will not be difficult!

**Comment by AndrewVSutherland** [comment]
@JohnCremona I'm referring to the L-function hashes (e.g. as stored in the lfunctions.instances collection, see http://lmfdb.org/api/Lfunctions/instances) , which are computed as linear combinations of a_p values in [2^12,2^13] modulo 2^61-1.  @jvoight and Dan Yasaki have already computed these for the Hilbert modular forms over real quadratic fields in the LMFDB, and I have done this for all products of elliptic curves over Q of conductor < 350000 that have isomorphic mod-n representations for some n (hence can be glued together along their n-torsion to get a principally polarized abelian surface that potentially corresponds to the Jacobian of a genus 2 curve).

For the elliptic curves over quadratic fields we are interested in the L-function of the Weil restriction down to Q -- this is a degree 4 L-function that is potentially also the L-function of a genus 2 curve.  Computing the hashes of these L-functions is easy.

**Comment by AndrewVSutherland** [comment]
@JohnCremona I meant to add that yes, I'm aware that these labels are changing and it will be easy for us to switch to the new labels -- just let me know when the switch is going to happen.  There should be no genus2 code that depends on the label format (we call functions in ecnf to do the label parsing), but there are labels in the database that will need to change.

**Comment by AndrewVSutherland** [comment]
@JohnCremona For a precise definition of the hash function we use, see Section 4.3 of http://arxiv.org/abs/1602.03715.  One nice feature is that the hash function linear, so if you know the hashes h1 and h2 of the L-functions of two elliptic curves E1 and E2 over Q, the hash of the L-function of the product E1 x E2 is just h1+h2 (modulo 2^61-1).

**Comment by JohnCremona** [comment]
Great work -- I am impressed!  And very good practice to use the utilities for label parsing (which do not decompose the conductor / level label anyway).

**Comment by davidfarmer** [comment]
I don't know how to tell if *all* friends are listed, but a lot of work has been
done on this, there are a lot of friends shown, and I suggest that someone who actually
works on these areas can close this.

**Comment by jvoight** [comment]
Everything I saw seemed to check out, with one class of exceptions: the two objects
  http://www.lmfdb.org/Genus2Curve/Q/4096/e/
  http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/64/2/e/a/
are friends, and this friendship is currently one-sided: it shows up on the CMF, not on the g2c isogeny class (nor the unique g2c).  Actually, this is a bit confusing if friendship is directed, so I think we should fix it.  This means somehow passing forward the already established friendship.

**Comment by AndrewVSutherland** [comment]
Addressed by #2871
