### ISSUE TITLE
All elliptic curves over Q are semistable

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4366]
Every elliptic curve over Q in the LMFDB is currently identified as semistable (on both beta and production).

Searching for non-semistable elliptic curves yields no results, and every elliptic curve page claims the elliptic curve is semistable.

The data in ec_curves appears to be correct, but the data in ec_curvedata is wrong..

**Comment by AndrewVSutherland** [comment]
I'm fixing this now by simply updating the semistable column in ec_curvedata using ec_curves.

**Comment by AndrewVSutherland** [comment]
This has been fixed on both beta and production (we now again have 818147 semistable and 2278640 non semistable elliptic curves over Q).

@JohnCremona it might be good to figure out how and why this happened just in case there are any other columns of ec_curvedata that did not get correctly copied over from ec_curves.

**Comment by JohnCremona** [comment]
Apologies. I'll check how this happened.

**Comment by JohnCremona** [comment]
The bug was that the upload script omitted entirely the simple operation of setting the 'semistable' flag to be true iff none of the conductor exponents is >1, and some default kicked in which put t for True in the upload file.  My fault entirely, and it will be fixed for future data uploads.  Looking at my scripts I cannot right now see why the upload file did not contain \N for None, which would at least not have been wrong.  This column is one of the very few whose value is not already present as a column in my source data files (in the ecdata repository) since it is such a trivial operation to compute its value from the local data which is stored (which includes all the conductor exponents).   While I clearly remember writing the line which computes the value from the rest of the local data, it seems that I was remembering the similar operation which happens with the ecnf data files.
