### ISSUE TITLE
Speed up slow NF searches on ramified primes by converting include to exact when possible

### ISSUE THREAD

**Issue by a234** [LMFDB/lmfdb#4467]
When searching number fields that ramify only at 17, this search (i.e. one ramified prime including 17) returns an error:
https://www.lmfdb.org/NumberField/?num_ram=1&ram_primes=17&search_type=List
while this search (i.e ramified exactly at 17) gives the correct return.
https://www.lmfdb.org/NumberField/?hst=List&ram_quantifier=exactly&ram_primes=17&search_type=List

Would it be possible to redirect searches of the former kind to that of the later kind?

**Comment by jwj61** [comment]
I ran the search several times with the given link and on beta.  None gave an error.

**Comment by edgarcosta** [comment]
@a234, do you recall what the error message said?

**Comment by edgarcosta** [comment]
I looked into this a bit further and it most likely was a timeout.
There are 5 timeout errors logged for that search query.

Here is a longer list of the latest timeouts on nf_fields for the last days: https://gist.github.com/edgarcosta/71641943b0941adb6dc3eaa3e1c4a624

**Comment by AndrewVSutherland** [comment]
Independent of whether the query times out or not, the key point is that one of these equivalent searches is much faster than the other (on my machine, even after running both queries repeatedly to get as much cache benefit as possible, the first search takes 8.5 seconds while the second on takes 350 ms, so a factor of about 25).

It seems like it would be worth switching include to exact whenever we know it won't change the semantics of the search (e.g. count=1 include=blah is the same as count=1 exact=blah for any non-blank blah).  If you wanted to get fancy you could also change count=n include=blah to count=n exact=blah whenever blah is a list of n primes, but I don't think that's necessary.

**Comment by rbommel** [comment]
I did not like Drew's solution that only works in very specific cases so much, so I went experimenting a bit myself. When I execute the query ``db.nf_fields.search({'num_ram':` {'$lt' : 2}, 'disc_rad' : {'$lt': 17}, 'ramps': {'$containedin': [17]}})``, it is already much faster. This is something we can already do in general right now. A similar query for the primes 2 and 17 then only takes 1.77 seconds instead of 10.8 seconds. Another idea that I had was to add the maximum ramified prime as a column in the table. That should allow us to filter more things out for these kind of queries.

Another possibility could be to limit the number `n` of primes the user can enter and search for each specific subset. This is equivalent to searching for disc_rad to be one of `2^n` possible values. This could be okay for small values of `n`. But in fact, I noted that the search is actually much faster when you put in a lot of primes (I tried with all primes up to 100, and then it was very quick), so it is not clear to me what is going on.

Ideally, you would like to search on disc_rad but with an ordering given by division instead of usual comparison, but I don't know if the database would support that...

**Comment by AndrewVSutherland** [comment]
@raymond I like your first suggestion, this seems worth doing now even if it doesn't solve everything.

**Comment by AndrewVSutherland** [comment]
#4944 solves the problem identified in the OP so I'm going to close this issue. If someone wants to open a new issue highlighting some remaining performance issues, that's fine (but I think #4944 actually addresses the worst and most common cases).
