### ISSUE TITLE
Decomposition of the Jacobian of a genus 2 curve as product of elliptic curves

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4478]
For some genus 2 curves, whose Jacobian factors as a product of elliptic curves we go further than specifying isogeny class, as we specify the curves of the elliptic curve, for example:
https://www.lmfdb.org/Genus2Curve/Q/994009/a/994009/1
but we still say
> Decomposes up to isogeny as the product of the non-isogenous elliptic curves

and we also don't say how we picked each curve from its isogeny class.

**Comment by edgarcosta** [comment]
@JRSijsling do you recall how we picked a curve in each isogeny class?

**Comment by JRSijsling** [comment]
Yeah, it is a bit weird to give specific curves here. In this particular case, where there are two non-isogenous elliptic curves, there are distinguished central idempotents. In other words, the endomorphism algebra is QQ x QQ, and the elements (1, 0) and (0, 1) in that algebra are truly distinguished and uniquely determined. These are applied to the lattice, and the resulting image furnishes the curves that are indicated.

Things are different when the algebra is, for instance, M_2 (QQ): Then there are no central idempotents, uniqueness is lost, and the result counts for less because just "some" idempotent is taken.

So frankly, in general it only makes sense to indicate the isogeny classes.

**Comment by rbommel** [comment]
See also pull suggest #4489.

**Comment by rbommel** [comment]
[![](https://camo.githubusercontent.com/fcaf500cf6cd78ea7e41a56c61c688c9f2e4f2873113bffc8873c9dd4903dfa2/68747470733a2f2f692e696d67666c69702e636f6d2f3539686732312e6a7067)](https://imgflip.com/i/59hg21)
[from Imgflip Meme Generator](https://imgflip.com/memegenerator)
