### ISSUE TITLE
Faltings heights for elliptic curves

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4480]
It would be good to be able to view (and search on) Faltings heights for elliptic curves (over Q or number fields), there seem to be some choices possible (normalization, log/exp, stable or not?), so some discussion about which versions to have seems helpful.

I had a look through the issue tracker and can't find this being mentioned before, or any sign that the data is already there, but it does seem like @JohnCremona has computed this data, is that so?

**Comment by JohnCremona** [comment]
I have computed the curve with minimal Faltings height in each isogeny class, though this is not displayed, as well as what I call the Faltings ratio which is the ratio of the period lattice area to the minimal one, which is always an integer.  Then there is just some factor to scale by; and you can also take the log, as you say.

If someone who actually wants to search by this quantity (not me!) tells me exactly what they want then it can be implemented easily.

**Comment by JohnCremona** [comment]
I did recently add the knowl https://www.lmfdb.org/knowledge/show/ec.q.faltings_height, just for EC/Q, defining it to be -log(A)/2 where A is the area of the (minimal) period lattice.  The quantity A is computed and stored in the table ec_mwbsd in column 'area', and minimal height means largest A.   The data files from which I create the upload files also have the F.height, so it would be a triviality to add the column and update all the rows.   I have not yet done anything similar over number fields.

For conductors up to 500000, it is true that 11a3 [0,-1,1,0,0] has the smallest height -1.112728797...

I have not yet looked up the definition of "stable" height.  Usually this refers to a normalisation with the property that the quantity does not change on base-change, and can be ignored for objects defined over Q.  But perhaps not in this case.

**Comment by alexjbest** [comment]
Oh great, so that is really already everything we would need for the unstable version. I really have no preference as to the normalization, whether to take log, as you say as long as the knowl is clear people can figure out what they want to search for. The only reason I liked the strictly positive version better is that then there is a clear lower bound of 0.

Ah great to know! Hopefully Jared will be relieved to hear that the answer is known to a reasonable degree of confidence.

Unfortunately I don't think the stable definition agrees with the unstable one over Q, instead the "stable height" is forced to be stable by definition by first base changing to a field where E has semi-stable reduction and then taking the unstable height.
So for semistable over Q elliptic curves they agree, but in fact Deligne says if E is not semistable the unstable height is always strictly larger than the stable one.
Then this definition only depends on the j-invariant of the curve, rather than a specific model.

I also just found another quite interesting paper about the extremal values of this function, https://arxiv.org/pdf/1609.00071.pdf?fname=cm&font=TypeI
which has some additional ancillary files with cool numerical explorations.

**Comment by JohnCremona** [comment]
Before doing any computations or adding new data columns someone needs to decide on a normalization.  That should be done in consultation with whoever will use this data.  Then there are various stages:  compute unstable heights for all the curves over number fields, compute stable heights over Q, then stable heights over number fields.  These computations should be done by someone with sufficient motivation, time and knowledge.  Also, since all the data in these tables in the LMFDB is uploaded from data in the repositories ecdata (over Q) and ecnf-data (over other number fields) this all needs to be done by working in those repositories, adding columns to the raw data files there and adapting the scripts which compute the data in those, then changing the scripts which convert those into actual LMFDB upload files, also adding suitable columns to the relevant LMFDB tables.  After that, the LMFDB code can be adapted to display more data, and allow more searches.

We could already display the unstable F height over Q since we store the area A (in table ec_mwbsd) and computing -log(A)/2 on the fly would be acceptable.   Also all searching for the height in a range h1..h2 by applying h -> exp(-2*h) before looking in the ec_mwbsd table.  Or (of course) just add a column for the heights -- which I have in the curvedata files in ecdata already, so I would be prepared to (1) add a new column 'faltings_height' to ec_curvedata, (2) adjust my script which creates upload files from raw files to include that column, (3) fill the column.  Before that, though, we should get an expert to say what normalization to use.  As far as I can see, Deligne divides by 2pi while Faltings divides by 2.

**Comment by JohnCremona** [comment]
I rather agree that it seems more natural to use the term "height" for a nonegative quantity, but if we want to display a version of the Faltings height without the log() then we would need to call it something like "exponential unstable Faltings height" (which is equal to 1/sqrt(A)).  I would like a decision on this before uploading data to a new column.

**Comment by JohnCremona** [comment]
Thanks, I had forgotten about that Sage ticket.   Looking at the Magma function over Q, FaltingsHeight(E) gives exactly -log(A)/2 where A is the area (it is called V for Volume in the Magma source code).  And StableFaltingsHeight(E) just adds log(denom(j)/|D|)/12 where D is the discriminant.  This is independent of the model, since after a [u,r,s,t]-transform, A will be divided by |u| while Delta is multiplied by u^12.  Also, for a semistable curve (and a minimalmodel of it) the denominator of j is exactly |D| since j=c4^3/D and in this case gcd(c4,D)=1.  Finally, if E is not semistable then base-change to a field where E becomes semistable, without changing the model; it follows that the same formula gives the stable height there (since the formula is model-independent).  I think I have convinced myself that this is the correct formula for an elliptic curve over Q!

For the database, displaying either the unstable or stable height is easy (the database stores abs(D) and the exponents of denom(j), and also stores j itself as a string).   For actual searching we should actually store both these heights in new columns.

I'm going to finish off that Sage ticket now.

**Comment by JohnCremona** [comment]
My Sage implementation of faltings_height and stable_faltings_height has been accepted and merged to wil be in release 9.3. That is just for elliptic curves over Q.

I'll be adding theses two columns to ec_curvedata soon.

**Comment by JohnCremona** [comment]
> My Sage implementation of faltings_height and stable_faltings_height has been accepted and merged to wil be in release 9.3. That is just for elliptic curves over Q.
> 
> I'll be adding theses two columns to ec_curvedata soon.

Done.  I am updating my branch which has search by discriminant to include search by Faltings height and display of Faltings height on individual curve pages.   I want to see if I can add a binary switch in the search to go between searching on Faltings height or by stable FH.

**Comment by JohnCremona** [comment]
See #4493

**Comment by JohnCremona** [comment]
Thanks to David Roe's new min function, I find that from the data I uploaded today we have minimum height for '11a3' as stated above, but minimal stable height for '1190700.cc1' with a value of -1.3211... while that for '11a3' is -1.112...

I will look into this further tomorrow.

**Comment by alexjbest** [comment]
Wow that's great, thank you John! And seeing as 1190700.cc1 has j-invariant
zero that does agree with Delignes result indeed. I guess it's just
numerical noise that makes this one appear slightly smaller than others? I
wonder why this twist in particular occured though, it's definitely not the
twist of largest conductor. Perhaps the data could be normalized by picking
one value of the height for each j-invariant so that they are all precisely
the same? I'm not sure that's really necessary though.

**Comment by JohnCremona** [comment]
#4493 (now merged) now does this over Q, with the ec_curvedata table now having columns for faltings_height and stable_faltings_height.  We can leave this issue open until we have something similar over number fields, though I am not currently inclined to sort that out.

**Comment by edgarcosta** [comment]
We should close it then. If someone disagrees, they can reopen it.
