### ISSUE TITLE
Test website display code

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#449]

**Comment by jwbober** [comment]
We already have some tests. What exactly is being suggested here?

**Comment by swisherh** [comment]
This was to indicate that each page type should have some test that it is loading properly (as opposed to tests that the mathematics is correct).  If there are pages that don't yet have a test this should actually be broken down into more specific tickets, but at the time I was just moving everything from the wiki onto github.

**Comment by JohnCremona** [comment]
On 7 November 2015 at 20:30, Holly Swisher <notifications@github.com> wrote:

> This was to indicate that each page type should have some test that it is
> loading properly (as opposed to tests that the mathematics is correct). If
> there are pages that don't yet have a test this should actually be broken
> down into more specific tickets, but at the time I was just moving
> everything from the wiki onto github.
>

Great idea.  At least one test for each template file.  Perhaps each
template file should include as a comment the test file which tests the
template.

John

**Comment by AndrewVSutherland** [comment]
I plan to implement a simple web crawler that will attempt to load any and every page it can (anything with a static URL) starting from a given entry point (this includes pages .../random, so it can reach pages that might otherwise require data entry);  the goal would simply be to detect pages that won't load at all due to timeouts (502s),  "Internal server errors", or other fatal errors.  It will also flag any pages that appear to load but for which the returned html document contains the word "error" in it.

I also plan to collect timing data that can be used to identify performance issues (see #1247).

**Comment by edgarcosta** [comment]
@AndrewVSutherland why not wget -r ? and then use the logs?

**Comment by AndrewVSutherland** [comment]
@edgarcosta Not a bad idea, although I want to also measure load times and look for error messages in the returned data, but it might be worth seeing if I can figure out how to to this with wget first.

**Comment by edgarcosta** [comment]
Hmm, I don't think wget will give you loading times, only download times.

I would try to find some script based on curl and tweak it to your needs, or build your own with libcurl.
https://curl.haxx.se/docs/faq.html#Can_I_do_recursive_fetches_with

**Comment by AndrewVSutherland** [comment]
libcurl is what I was planning to use (probably via pycurl 
http://pycurl.io/), but I might be able to do what I want just using 
urllib2

**Comment by AndrewVSutherland** [comment]
Following up on @edgarcosta's suggestion, just doing:

wget -r -e robots=off 127.0.0.1:37777/StartingPoint

will recursively attempt to load every page that can be reached from /StartingPoint.

I ran this last night on Atkin starting from the LMFDB home page and discovered issues #1492, #1493, #1494, #1495, and #1496. (it took about 5-6 hours).

I am working on extracting timing information as well, which I think may actually be doable.

In any case, as a way to test that pages at least load correctly, this is an easy solution that I think addresses the original issue Holly raised.  I would suggest that this is a standard test one should apply prior to submitting (and when reviewing) a pull request for a specific module, in addition to running /test.sh.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, if you want other pages that break down you could look into the flasklog + accesslog of the webservers, as search engine crawlers also trigger a bunch of other broken pages. 
However, sometimes is hard to figure out how the bot got there...

**Comment by AndrewVSutherland** [comment]
Yeah, I like using a local log because it shows only the pages my wget 
is hitting, in order (so I can see the path to get there), and I know 
exactly what version of the software I am using.

But I agree that it is useful to periodically check the webserver logs.  
Google bot is a good tester!

**Comment by AndrewVSutherland** [comment]
I'm going to go ahead and close this issue, because I think we have a simple solution that works -- we just need to remind people who are submitting or reviewing PRs that it exists and to use it.

I will make a separate post to issue #1247 about problematic page load times once I have gathered this information.
