### ISSUE TITLE
Large primes cause server error

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4539]
If you enter 10000000019 into any of the search fields "cyclic isogeny degree", "p dividing Sha", "bad primes", or "maximal primes" on https://www.lmfdb.org/EllipticCurve/Q/ you get a server error.

I believe the same problem occurs for "bad primes" on the CMF and genus 2 pages.  I note that it does not occur on the "ramified primes" or "unramified primes" search fields for number fields

**Comment by JohnCremona** [comment]
This is about EC/Q, right?

It sounds like a 32-bit issue since 10000000019 has 34 bits.  The types are

bad_primes: integer[]
nonmax_primes: smallint[]
sha_primes:smallint[]
isogeny_degrees: smallint[]

where I chose smallint for the last three on account of their size being bounded, either theoretically or conjecturally or practically.  I don't think that needs changing, but perhaps we need a way of specifying a maximal size for these and massaging the query so that invalid values (or ranges)  are removed.  In your examples, the website would "know" that 10000000019 was out of range and somehow return an empty list -- quickly.

**Comment by AndrewVSutherland** [comment]
I think it would be better to handle this at a lower level, either in db backend (the error is actually raised by psycopg2) or more likely in searchtable.py -- what do you think @roed314 ?

As a quick fix, catching the NumericValueOutOfRange error that is being raised by pscyopg2 and displaying a sensible error saying that one of the inputs is too large would be easy to do and might already be enough.

**Comment by roed314** [comment]
I can see two reasonable approaches:

1. Catch the error in `lmfdb.utils.search_wrapper.Wrapper.make_query`.  At this point, we won't know what column or input caused the error, but we can print a flask warning explaining that there was an overflow and give no results.
2. Modify `lmfdb.backend.searchtable.PostgresSearchTable._parse_special` to check for overflow when constructing the query.  This will involve quite a bit more work, since overflow needs to be handled differently depending on the query: you can't just return no results since asking that the cyclic isogeny degree be `2-10000000019` should return lots of results.  But it has the potential to give correct results without an error.

**Comment by edgarcosta** [comment]
1. seems simpler, and the user can easily decide what triggered the overflow. If you really want to give an error message, one can try various subqueries with limit = 1 to conclude which query is problematic.

**Comment by AndrewVSutherland** [comment]
Addressed by #4541
