### ISSUE TITLE
Sign missing in discriminant norm 

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4566]
On https://www.lmfdb.org/EllipticCurve/2.2.12.1/9.1/a/3 the discriminant norm is -27, but the factorization omits the sign that should be there (the factorization should read $-3^3$)

**Comment by JohnCremona** [comment]
Sorry about that.  I see that it is easy to fix and I'll see to it now.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Thanks!  When you do, it would be good to use web_latex_factored_integer, because it will handle the sign correctly and replace "-1 \cdot" with "-", which is consistent with our new style guide (see the genus 2 pages for example).  I notice that EC/Q pages still show "-1 \cdot" in factorizations of negative integers.

**Comment by JohnCremona** [comment]
> @JohnCremona Thanks! When you do, it would be good to use web_latex_factored_integer, because it will handle the sign correctly and replace "-1 \cdot" with "-", which is consistent with our new style guide (see the genus 2 pages for example). I notice that EC/Q pages still show "-1 \cdot" in factorizations of negative integers.

Sorry, I only just saw this comment.  Would you like me to make a new PR with this extra change?

**Comment by AndrewVSutherland** [comment]
It looks like latex_factorization also does this, so I think ECNF is fine.  If you want to take care of EC/Q as well that would be great (but don't feel any obligation, I can do it this afternoon if you don't get to it).

**Comment by JohnCremona** [comment]
> It looks like latex_factorization also does this, so I think ECNF is fine. If you want to take care of EC/Q as well that would be great (but don't feel any obligation, I can do it this afternoon if you don't get to it).

Thanks, then I'll let you do it.  I wrote the special function for ECNF to handle various factorization displays where we know (e.g. because they are stored) the vectors of bases (primes) as suitable strings, and of exponents.  But in ECNF I use Sage's factorization class instead, whcih does not use our convention.

Probably the best solution is to move my latex_factorization() funtion inso somewhere like utils and use it in both places (and possibly elsewhere).  But I will not do that today.
