### ISSUE TITLE
One curve per isogeny class filter on E/Q search not working in combination with others

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4678]
If I search for E/Q with j-invariant -4096/11 I get 156 results:

 http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=-4096%2F11&search_type=List

which I note all lie in distinct isogeny classes.  But if I set the one curve per isogeny class I get 0 results:

 http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=-4096%2F11&optimal=on&search_type=List

The same thing happens for j=-3375

 http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=-3375&optimal=on&search_type=List

and it also happens if I don't set the j-invariant but instead set the CM discriminant to -7:

  http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=-3375&cm_disc=-7&optimal=on&search_type=List

but I notice that it works as expected for j=0 or 1728:

  http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=0&optimal=on&search_type=List
  http://www.lmfdb.org/EllipticCurve/Q/?hst=List&jinv=1728&optimal=on&search_type=List

**Comment by JohnCremona** [comment]
I'll look into this.  I'm sure it used to be OK...

**Comment by JohnCremona** [comment]
When you select just one curve per class it restricts to curves whose lmfdb_number is 1.  The curves in a non-CM isogeny class all have distinct j-invariants, so if you also specify a j-invariant is's chance whether or not that curve has number 1.  In CM-classes, since the CM is potential, there will be two curves with each j-invariant, but of course only one has number 1.

Because of the above I could say that specifying one curve per class together with specifying some other criterion which is not isogeny-invariant is not something you should ask for (!).  It would be similar to combine a one curve per class search with (say) torsion order, torsion structure, regulator, CM discriminant (not just CM field), cyclic isogeny degree, and more.

Otherwise, we would have to imnplement the one curve per class in a different way:  ignore it for the database query, and then process the search results to pick only one curve with each class label 'lmfdb_iso'.

Is there an efficient way to do that?

Meanwhile we could perhaps divide the search properties into those which are and those which are not isogeny-invariant, and say that the one-curve-per-class option is only enforced when nonne of the latter are specified.

**Comment by roed314** [comment]
There are [ways](https://ubiq.co/database-blog/how-to-get-first-row-per-group-in-postgresql/) to pick one from each group in postgres.  I think it's probably worth it to add this feature, since there are other cases where selecting one from each group could be useful.  Here's a proposed syntax:

```
db.ec_curvedata.search({'jinv': [-4096, 11]}, 'lmfdb_label', oneper=['lmfdb_iso'])
translates to
SELECT lmfdb_label FROM (SELECT lmfdb_label, conductor, iso_nlabel, lmfdb_number, row_number() OVER (PARTITION BY lmfdb_iso ORDER BY conductor, iso_nlabel, lmfdb_number) as row_number FROM ec_curvedata WHERE jinv = '{-4096, 11}') temp WHERE row_number = 1 ORDER BY conductor, iso_nlabel, lmfdb_number
```

If this looks good, I can add the feature to the backend.  I'm not sure what the performance will look like in comparison to just adding `lmfdb_number = 1` to the `WHERE` clause....

**Comment by AndrewVSutherland** [comment]
@roed314 I like the idea of adding this capability generically, it will be useful elsewhere.  My guess is the performance should be fine, but we should test it (@edgarcosta might also want to weigh in on this).

**Comment by JohnCremona** [comment]
Good -- I don't know postgresql well enough to check the syntax but it looks possibly a little too complicated since we only need to pick a unique lmfdb_number from all those matching one lmgfb_iso (the conductors are all the same here).

Of course I may have misunderstood.

**Comment by roed314** [comment]
Yeah, the issue is that picking a unique one is complicated in SQL.  I think this is the best way to do it (though certainly someone should tell me if they find something else!)

I'll go ahead and try to add this.

**Comment by edgarcosta** [comment]
I would strongly suggest something like
```
SELECT DISTINCT ON (lmfdb_iso) lmfdb_label, conductor, iso_nlabel, lmfdb_number FROM ec_curvedata WHERE jinv = '{-4096, 11}') temp WHERE row_number = 1 ORDER BY conductor, iso_nlabel, lmfdb_number
```

**Comment by roed314** [comment]
If we use that construction we can't make the ordering correct, since `SELECT DISTINCT ON (lmfdb_iso)` requires that `lmfdb_iso` be the first term in the ordering.

**Comment by roed314** [comment]
In this case we can work around this by using `SELECT DISTINCT ON (conductor, iso_nlabel)`, which is the initial segment of the ordering that we want, but that won't work in general.

**Comment by roed314** [comment]
I don't see how to get the ordering correct without using a nested query.  It might be better to use the `SELECT DISTINCT ON` construction for the inner query instead of `PARTITION BY`.

**Comment by edgarcosta** [comment]
yes, the nested query might be the way, especially because soon we will want to sort by id

**Comment by roed314** [comment]
See #4690

**Comment by roed314** [comment]
Fixed.
