### ISSUE TITLE
Knowl beta and title?

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#4716]
Hi, two issues, perhaps related.

I wanted to go and review all "Atkin-Lehner" knowls in beta to flag them as reviewed.  When I search I get to
  https://beta.lmfdb.org/knowledge/?all=1&category=&search=atkin-lehner&beta=on&normal=on&top=on&bottom=on
and it lists for example the knowls
  https://beta.lmfdb.org/knowledge/show/g2c.4489.a.4489.1.top
  https://beta.lmfdb.org/knowledge/show/cmf.minus_space
which are in fact reviewed, not in beta.  Is something wrong with the search, or how they are flagged?

Second, title issue.  The knowl
  https://beta.lmfdb.org/knowledge/show/g2c.15625.a.15625.1.top
displays on the search page as "Quotient of X_0(125)".  That should be like the others, but when I go to edit it, the description is already correct, "Modular curve $X_0(125) / \langle w_{125}\rangle = X_0^+(125)$".  Why is there a difference?  I'd like also to make a correction to
  https://beta.lmfdb.org/knowledge/show/ec.q.37.a1.top

Thanks!

**Comment by rbommel** [comment]
I will try to take a look at this now.

**Comment by edgarcosta** [comment]
@roed314 do you recall what status = -1 means? supposedly in progress, but I don't understand what that means.

**Comment by rbommel** [comment]
What happened to John is the following. For example for cmf.minus_space there were three versions of the knowl. The oldest one was not reviewed and had the keyword 'atkin-lehner'. In subsequent versions of the knowls (which are reviewed), this keyword has been removed.

The search function would first filter out the knowls with the keyword and then pick the most recent one, which turned out to be the old unreviewed one. But then when you click on the link, you go to the newest version of course. In pull request #4958, I now changed the search function so it will first of all only consider the most recent versions of each knowl, and then apply the filter.
