### ISSUE TITLE
operations

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#473]
I can't find a single example of `operations' that works. It used to work. Is there a simple fix?

**Comment by jwbober** [comment]
We actually display a link to this on www.lmfdb.org. The link should only be displayed for beta.lmfdb.org.

**Comment by JohnCremona** [comment]
On 31 October 2015 at 20:26, Jonathan Bober <notifications@github.com>
wrote:

> We actually display a link to this on www.lmfdb.org. The link should only
> be displayed for beta.lmfdb.org.
>
That's right -- and the different colour of the menu item on beta should
indicate that.  In sidebar.yaml (lines 59-61) this item is tagged beta, soe
there must be an error in the logic of the code in sidebar.html.  Good luck!

**Comment by JohnCremona** [comment]
OK I know what it is.  It is fixed in beta, as you can see if you run
locally without the --debug flag.

Someone must tell Brian not to go by what is on the www site.  Or perhaps
we should have visible a website running beta code without the beta flag.

Or just push beta to prod again soon -- last done about 3 weeks ago I think
but a lot has been fixed by then.

**Comment by JohnCremona** [comment]
I will close this since Operations no longer appears on www.lmfdb.org.

**Comment by davidfarmer** [comment]
Maybe we need an issue for this, since it is broken, and it can be assigned to Milestone 2.0?

**Comment by JohnCremona** [comment]
OK, fair enough.
