### ISSUE TITLE
Wrong q-expansions in search results 

### ISSUE THREAD

**Issue by alexjbest** [LMFDB/lmfdb#4787]
Looking at 37.2.b.a on http://lmfdb.xyz/ModularForm/GL2/Q/holomorphic/?level=37&weight=2&search_type=List we see q-expansion `q + iq^2 + ...` but when we click through to http://lmfdb.xyz/ModularForm/GL2/Q/holomorphic/37/2/b/a/ instead it says `q+2iq^2 + ... `.

**Comment by edgarcosta** [comment]
This seems to be data issue:
https://beta.lmfdb.org/api/mf_newforms/?label=37.2.b.a&_fields=qexp_display

**Comment by AndrewVSutherland** [comment]
I'll take a look at this on Friday, I'm not sure how this could have happened and want to see if the same issue occurs elsewhere (if anyone notices any other instances of this problem, please post them here).

**Comment by alexjbest** [comment]
Any updates here, just saw this one again in the wild!

**Comment by AndrewVSutherland** [comment]
The qexp display column needs to be recomputed.  I was planning to address this at the same time as when I add the new data from Alex Cowan's computations (which has been slowed down because I first want to make some changes to the Dirichlet character database to switch over to the new char_orbits table which goes out to modulus 100,000).  I'm planning to get this done during the winter break, but it likely won't happen until mid to late January (if it is not done before the LMFDB coding sprint scheduled for Jan 21-22 I will do it then).

Can you tell me the label of the other example you found?

**Comment by alexjbest** [comment]
It was the same example, we just got confused by it again before I
remembered this issue!
Sounds good, thanks 😊

**Comment by edgarcosta** [comment]
Another example from #5092 
> https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?hst=List&level_type=divides&level=64&weight=4&char_order=2&search_type=List
> the q-expansion of 64.4.b.b is wrong, as can be seen when opening its page, i.e. compare
> https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/64/4/b/b/

**Comment by AndrewVSutherland** [comment]
I am very confused by the fact that even though I fixed the data in qexp_display, the wrong q-expansion is now being displayed on the home page (as noted by Maarten Derickx).  The blame history makes me wonder how it was ever correct on the home page in the first place, but in any case I changed the code to use the standard basis (the data in mf_hecke_nf gives the Hecke ring basis as [1,2i], you can't just declare the basis to be [1,i] because you don't like writing it in terms of beta=2i, which is what the code in web_newform.py appears to have been doing, if you want to write it in terms of i you need to recompute the basis, and I'm not sure that even makes sense in general (e.g. if the Hecke ring bases is [1,123+456i] I think I'd rather see beta's).
