### ISSUE TITLE
Some lists of interesting objects are empty

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#4847]
For example on the browse page for p-adic fields there's a link to "some interesting p adic fields" but the user clicking on that link will be disappointed.

Pending someone coming up with any p adic fields interesting enough to be mentioned (by having a top or bottom knowl, I know) perhaps we can only display that option when there are any?

**Comment by roed314** [comment]
These links are added manually to the template, so there's no good way to automatically hide them.

The actual issue here, though, was a typo in the creation of the interesting knowls page for p-adic fields.  Once that typo was fixed, 5 interesting fields appear.  See https://beta.lmfdb.org/knowledge/?all=1&category=lf&search=&reviewed=on&beta=on&top=on&bottom=on for the list.

**Comment by roed314** [comment]
The only other section of the LMFDB without interesting objects listed is degree 3 rational L-functions.

**Comment by JohnCremona** [comment]
@roed314 Thanks for fixing that -- I noticed it when browsing on a phone so did not actually look for any fields which should have neen there.

I still see nothing at https://beta.lmfdb.org/padicField/interesting so does something need merging or restarting?

I'll leave this open hoping that someone knows an interesting degree 3 L-function...my vote might be https://beta.lmfdb.org/L/SymmetricPower/2/EllipticCurve/Q/11/a/.  @davidfarmer ?

**Comment by edgarcosta** [comment]
The typo hasn't gotten yet to {www,beta}.lmfdb.org
Symmetric powers are still computed on the fly.

**Comment by davidfarmer** [comment]
There are interesting degree 3 L-functions

https://beta.lmfdb.org/L/interesting?degree=3&rational=

but currently there are no rational degree 3 L-functions which
are labeled as interesting.

Mostly that is because there are so few examples.  In fact,
if you search for degree 3 rational L-functions, nothing is
found:

https://beta.lmfdb.org/L/rational?degree=3

Until we have such L-functions in the database, I suggest we
omit the number "3" as an option for "Some interesting L-functions"
on top Rational L-functions page, or just tolerate the fact that
we don't have any examples yet.

**Comment by AndrewVSutherland** [comment]
I'm more bothered by the fact that we have no rational degree 3 L-functions at all!  Probably the easiest way to get some would be to (pre)-compute the Artin L-functions we already have (which we are planning to do anyway and I think we actually started  on this two summers ago), which would also let us add a bunch of Dedekind zeta functions of low degree.

@edgarcosta Is there anything other than finding the time to do it that is preventing us from computing Artin L-functions up to some conductor/degree bound?

**Comment by JohnCremona** [comment]
When I made my comment I had forgotten that the symmetric square L-functions (sym squares of degree 2, I mean) which I knew about werenot actually objects in the database.  So another project would be to compute those up to some bound and add them properly.

**Comment by edgarcosta** [comment]
@andrewvsutherland, most of the data is already computed and stored on a Babbage, but I need to rewrite some frontend code, to support the new table.

I will just remove the 3 for now.
