### ISSUE TITLE
Consistency of math mode in property boxes

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#486]
Someone needs to make sure we have consistency with math mode in properties boxes.  This should probably be discussed first.

EDIT: Here is a more precise description of the issue.  If you look carefully at the property box on
the page https://www.lmfdb.org/L/EllipticCurve/Q/11/a/ you will see that the degree, conductor and motivic weight display integers in text mode, but the sign is displayed in math mode, resulting in a slightly different font being used.

For a more obvious example see https://www.lmfdb.org/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-36.1-a where the level and weight are both lists of integers but the weight is displayed in text mode while the level is displayed in math mode.  In this case the level really needs to be in math mode because it typically will not just be a list of integers, see https://www.lmfdb.org/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a for example.

**Comment by AndrewVSutherland** [comment]
@swisherh Can you be more specific?  Math mode is used in property boxes in many places and I don't see any obvious problems.  What are some examples of the inconsistencies you are concerned about?

**Comment by AndrewVSutherland** [comment]
I contacted @swisherh directly and she agreed that we can close this.

**Comment by AndrewVSutherland** [comment]
This issue came up in Kiran's talk at UConn today, where it was pointed out that on the L-function pages one often sees a mixture of math mode and non math mode when displaying integer values in properties boxes.  See http://www.lmfdb.org/L/EllipticCurve/Q/11.a/, for example, where the sign and motivic weight are both equal to 1 but displaced in different fonts.

Elsewhere, the properties boxes for elliptic curves use math mode when displaying integers, but most others (e.g. classical modular forms, number fields, genus 2 curves, Hilbert modular forms, etc...) do not.

On a related note, we are inconsistent about capitalization of yes/no and true/false.

I would propose that numeric attribute values displayed in properties boxes should always be in math mode, and that text strings representing boolean values (yes/no and true/false) be displayed in lower case.

Rather than modifying the code everywhere, I suggest enforcing these conventions in the template that displays the properties box.

**Comment by swisherh** [comment]
Thanks Drew, for reopening this.  I agree that a holistic property box
template solution would be ideal, since even finding where all of the
examples of the issue are can be tricky.

-Holly



On Sun, Aug 14, 2016 at 8:52 AM, Andrew Sutherland <notifications@github.com

**Comment by rbommel** [comment]
Okay, in the case of the L-function linked above, I did some check in the database. The root number seems to be stored as a string, while the motivic weight is stored as an integer. It seems to me that it is sensible that we display integers (or other numeric types) in TeX-mode and that strings are just printed as is. I don't know why this particular choice has been made. It could be that some of the data is missing and that there is a string to indicate that. However, given the current choice, I do think this data is being displayed in the most desirable way.

**Comment by AndrewVSutherland** [comment]
I'm working on this now.

**Comment by AndrewVSutherland** [comment]
Addressed by #4143
