### ISSUE TITLE
Replace header "Point counts" in abelian varieties

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4925]
Being principally polarizable and its realization as Jacobian are clearly related to the Point counts on the abelian variety and the (virtual) curve, but putting the three under the header "Point counts" sounds odd.
I don't have a good suggestion :(

Here is an example:
https://beta.lmfdb.org/Variety/Abelian/Fq/2/191/p_ck

**Comment by rbommel** [comment]
So your suggestion is to make a new header 'Curves' and put that above the 'Point counts'? This should be easy to implement if people agree on this.

**Comment by jvoight** [comment]
Upvote for making a new header/section called "Curves".  Maybe decide between "X" for the curve (in the knowl) and "C" (on the main page).  

Also not sure if we should talk about the "point counts of *the* curve", since there can be many curves in the isogeny class.  Propose "(virtual) curve point counts".  

But probably get @roed314 or someone who knows these pages well to give thumbs up or down?

**Comment by edgarcosta** [comment]
The page says "Point counts of the (virtual) curve" when there is no curve, e.g.,
https://beta.lmfdb.org/Variety/Abelian/Fq/2/2/ab_ab

Perhaps something along the lines of "Polarization" would make more sense?

**Comment by edgarcosta** [comment]
I think this might be done

**Comment by roed314** [comment]
Agreed.
