### ISSUE TITLE
Representations

### ISSUE THREAD

**Issue by brianconrey** [LMFDB/lmfdb#493]
Representations on the left side is not a link. It needs to be and the page it goes t should contain a brief description on what will be found there. Also a historical introduction to Representations maybe beginning with characters (who thought of these? When? what paper?) and then the generalization. Who were the earlier contributors? When was the connection made to number theory and L-functions? Written in a gentle way so as to make Bill Browser feel like he understands!

**Comment by sanni85** [comment]
Do you want to have a page displaying a single knowl, like http://beta.lmfdb.org/intro or do you want an html page, like http://beta.lmfdb.org/ModularForm/?
There are differences: if it is a knowl, you can edit it just logging in, while in the second case you need to edit the template. Let me know, I can create all these pages (#494 too) with no problem.

**Comment by brianconrey** [comment]
I would say there should be both. An html page describing what's
in the section. And on that page a history article within a knowl.

Brian

**Comment by davidfarmer** [comment]
First let's talk about the structure of the page, adding headings,
and breaking into smaller self-contained pieces.

**Comment by jvoight** [comment]
Brian and I discussed this today.  We think the most helpful thing to draw people to the LMFDB and the approach to the Langlands correspondence implicit in our efforts is to find some compelling examples where the Langlands point of view gives insight or new ideas or indicates things that are true that you wouldn't realize otherwise.  For example:
1. the L-function of symmetric cube of an elliptic curve has analytic;
2. the L-function of the base change of an elliptic curve from QQ to a number field is given by a recipe;
3. the Asai L-function and its representation-theoretic interpretation;
4. the complete description of bad Euler factors in Rankin-Selberg convolutions (perhaps the simplest example where you need to know the representation theory);
5. the connection between classical modular curves and Shimura curves (e.g. isogenous Jacobians);
6. properties of central simple algebras from the point of view of Tate's thesis.

The idea would be to explain the things under the "Representations" heading in this context, but motivating the relationship between "representations" and representation theory and the LMFDB.

(We think that Galois representations should probably move to its own heading because of the important role that it plays, which is quite different than the other kinds of representations in the subheading.)

**Comment by jvoight** [comment]
We also need an article on why computations with the Langlands program are important--this is perhaps a different audience.

**Comment by jwj61** [comment]
I am not sure whether this is ready to be closed.  "Representations" is a link with content.  Bundled in the issue is having an article on historical content, which is not done.

**Comment by AndrewVSutherland** [comment]
With the exception of L-functions, none of the headings on the sidebar have a "history of" link.  Maybe they should, but this seems like a broader topic that is not specific to this specific issue (I'll leave it to those motivated to work on it to open a new issue if they wish).
