### ISSUE TITLE
Real numbers displayed with ellipses

### ISSUE THREAD

**Issue by bmatschke** [LMFDB/lmfdb#4943]
The regulator of https://beta.lmfdb.org/EllipticCurve/Q/37a1/ is given as "0.051111408239968840235886099757...". The ellipses "..." are misleading (to me), as this expansion is obtained by rounding, not by truncation. (A longer expansion is "0.05111140823996884023588609975694...".)
@JohnCremona

**Comment by roed314** [comment]
I propose that we rephrase all the rounded quantities on the page as `X \approx x`, where `X` is an appropriately chosen symbol (often there's a standard symbol, but sometimes we may need to choose one), and `x` is a real approximation with no ellipses.

Here's a proposal for the symbols to use, but @JohnCremona please let me know if there are better or more standard choices!

* [Faltings height](https://beta.lmfdb.org/knowledge/show/ec.q.faltings_height): `h_{\mathrm{Faltings}}`
* [Faltings height](https://beta.lmfdb.org/knowledge/show/ec.q.faltings_height): `h_{\mathrm{stable}}`
* [abc quality](https://beta.lmfdb.org/knowledge/show/ec.q.abc_quality): `Q`
* [modified Szpiro ratio](https://beta.lmfdb.org/knowledge/show/ec.q.szpiro_ratio): `\beta`

We can then use all the standard notation for the BSD invariants, including `r` for the analytic rank (so that it's not the only quantity not of the form `X = x` in that section.

Finally, we should also fix the `(rounded)` knowl which is broken.  Since it just points to the same knowl as the row header I propose just removing it (that's the current state for anyone not logged in).

**Comment by JohnCremona** [comment]
This is related to #5308 but this one is easier.  I approve of @roed314 in principle but I do not know a standard notation for either the abc quality or the Szpiro ratio.  If there is none yet, we can be the ones to set the standard, but it would be good to have some input, or look ni the literature, before committing ourselves.

**Comment by roed314** [comment]
I have seen $$q$$ most frequently for the quality of an abc triple, but I think in our context I would use $$Q$$ to avoid the $$q$$ in $$q$$-expansions.  For Szpiro ratio, [Oesterle's paper](http://www.numdam.org/item/SB_1987-1988__30__165_0.pdf) uses $$\beta$$ for the bound in the conjecture (though I don't think it's used for the quantity attached to a specific curve).  [Barrios](https://arxiv.org/pdf/2104.10817) uses $$\sigma_m(E)$$ and [Chan](https://arxiv.org/pdf/2407.13850) uses $$\sigma(E)$$ for the original Szpiro ratio, so perhaps $$\sigma_m(E)$$ is a good choice.

**Comment by JohnCremona** [comment]
I am working on this now

**Comment by JohnCremona** [comment]
...done, I will make a PR and say more there, then I will go on to do the same for ECNF.

**Comment by JohnCremona** [comment]
This has been done and merged for ECQ, I will shortly make a PR for similar for ECNF.
