### ISSUE TITLE
Maass forms browse creates server error

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#496]
Clicking on browse produces a server error

http://beta.lmfdb.org/ModularForm/GL2/Q/Maass/BrowseGraph/1/10/0/10/

**Comment by davidfarmer** [comment]
Seems to have been fixed (by the database upgrade?)

**Comment by haraldschilly** [comment]
no, I did this when I was sitting at your dinner table. I had to comment out the "next/previous" links, because they were sending some "navi" list/tuples to the template, but that name is already used for something else. I'm not sure if those next/previous links were even populated with useful data, though. 

I think it's this fdf4b6765a304c40375 commit.
