### ISSUE TITLE
Announcements/homepage cleanup? 

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#4963]
The current homepage could use an update.  

Three thoughts:

* The "hall of fame" has been subsumed by "interesting" objects, which are now throughout.  On pages these are commingled with the browse functionality, so I propose we include this in the browse/search bubble in some way.  (I wouldn't be sad to see the phrase "hall of fame" go away.)  To create space there, I wonder if we can compress or omit the static text "Search for objects with specific properties, or browse categories."  Is that adding something essential?  How is this distinct from the "Database"?  
* The title "code and open software" is a bit confusing, because Magma is not "open", and anyway we meant "open source".  Do we really want to display this at the same visibility as the content of our website?  I would relegate this to the footnote and our acknowledgements/citation knowls.

If we do at least one of these bubbles, that would create space for:
* An "announcements" bubble.  We could make this a different color, or bold it, to draw the user's attention.  Here, we could add our LuCaNT announcement and put "Citing the LMFDB" in a visible place, as well as an announcement/release notes for 1.3.  (So we should do this last, after the rest of 1.3 is done.)

**Comment by AndrewVSutherland** [comment]
I think we should add a "How to cite the LMFDB" link to the front page (in addition to the tiny "citation" link that appears in the footer of every page).

**Comment by jvoight** [comment]
Whenever we do this, let's make sure that https://www.lmfdb.org/LuCaNT redirects to https://icerm.brown.edu/events/sc-23-lucant/

**Comment by jvoight** [comment]
I think I was tasked with finding an icon for the new citation/attributions square.  I found these (at a tiny cost, they are free for our use without attribution), will one of them do?

![9324189_references_hint_allusion_mention_quotation_icon](https://user-images.githubusercontent.com/4120797/209612136-c1c38b46-2bcc-4be5-a744-e541d3a763fa.svg)
![4120422_citation_mention_reference_review_talk_icon](https://user-images.githubusercontent.com/4120797/209612139-85452a02-4756-4e9a-a6d8-d759b90311af.svg)
![4958720_border_citation_extract_indications_poster_icon](https://user-images.githubusercontent.com/4120797/209612140-4a00d1cf-d7c6-49d7-82b2-f68f9e46125f.svg)

**Comment by davidfarmer** [comment]
I find the middle one confusing, because I can't tell who he is and why I would want to listen to him.  And, he is a white him.

**Comment by jvoight** [comment]
Would you like to consider a racial recasting of the middle one, or would it still be confusing?  Are either of the other two satisfactory?

**Comment by davidfarmer** [comment]
I think having a person as part of the icon would still be confusing, even if suitably inclusive.

I like the last one because it doesn't seem to be trying to be too clever with the message it is sending.

**Comment by jwj61** [comment]
I forget, where can we view the new home page (so I can think about the icons in context)?

**Comment by AndrewVSutherland** [comment]
You can view the frontpage branch (with two images TBA) at https://purple.lmfdb.xyz/  Note that we also need an image for the announcements box.

**Comment by davidfarmer** [comment]
It is considered poor usability to have the text of a link be "here"
or "click here".  Sometimes it takes a bit of rewriting so that the text
you click describes the target or action when you click it.

Under the "A database" box, the 2nd link would be better as
"go to a random page".

The sentence containing the first link could perhaps be rewritten
as  (I put asterisks around the link)

Information is available regarding the *source, reliability, and completeness* of the database.

**Comment by AndrewVSutherland** [comment]
@davidfarmer I implemented your suggestions on https://purple.lmfdb.xyz/ (and would welcome any other you may have).

**Comment by davidfarmer** [comment]
Looks good.

Not sure when you plan to involve all the editors, but I would not be 
surprised at some push-back and suggestions to add two more boxes for 
highlighting specific interesting objects.

I am *not* making that suggestion.  But I will think about what has been 
lost, from the perspective of a first-time visitor.

**Comment by jvoight** [comment]
Here are three options for announcements:

![1198826_announcement_promotion_megaphone_discount_marketing](https://user-images.githubusercontent.com/4120797/209870883-66f90e9e-770e-46e8-ac47-c17bc52b1b9a.png)
![3100617_announcement_announcer_poster_architecture_signs_advertising](https://user-images.githubusercontent.com/4120797/209870884-a4b20575-ca93-480d-afa9-af9ce97d14bc.png)
![10121214_announcement_post_like_megaphone_online_marketing](https://user-images.githubusercontent.com/4120797/209870886-ee668b69-d4f9-4cc4-8298-9bbefdb21ee2.png)

**Comment by jvoight** [comment]
@davidfarmer : I also wouldn't make that suggestion.  

I'd be very happy if we had something to welcome and orient a first-time visitor, but it wouldn't be the hall of fame (or a link to GL(4) Maass forms).  Perhaps a link under the "Learn more" box ("Welcome and highlights"?) which could link to a curated page with explanatory text?  Wouldn't want to hold up the front page remodel for this, but seems like it'd be a good thing to discuss at our LuCaNT gathering (and more generally, broadening use/expanding ease of access)?

**Comment by jwj61** [comment]
I like the first one for announcements the best.

I am not sure about the 3rd citation image.  I think the simple black and white would not fit in with the rest of the page.

**Comment by davidfarmer** [comment]
I think you have described what we need: something to welcome and orient the first-time visitor.

A link to a separate page could be good.  Can be added later.

(I also prefer the 1st announcement image)

**Comment by jvoight** [comment]
We could color in the citation image, like: 
![8543115_quote_speech_bubble_message_dialogue_icon](https://user-images.githubusercontent.com/4120797/209872708-6f26031c-5d21-4a2f-81de-a670e651766c.png)

**Comment by pascalmolin** [comment]
I am also in favor of the third announcement image. I like the colored
version.
The same should be done with the announcement: I prefer the third one with
the heart removed. Here is also the first one turned blue (quick and dirty).

Pascal

[image: anouncement2_heartless.png]
[image: anouncement1_blue.png]

Le mer. 28 déc. 2022 à 22:14, John Voight ***@***.***> a
écrit :

**Comment by jwj61** [comment]
The colored citation image looks good.

**Comment by AndrewVSutherland** [comment]
I added blue-filled citations (3rd option) and annoucnements (1st option) to https://purple.lmfdb.xyz.  I'm happy to try others (including changes to the database and learn more images, which are now quite different from the announcements and citations images).  @pascalmolin I wasn't able to access the image links in your ealier message but I'm happy to try a heartless third option (but I'll wait to give people a chance to look at what I just posted).  If/when we get down to a handful of options that people favor I can easily post multiple options on different color servers and we can solicit feedback from a wider group, but I don't think we are quite ready for that (but anyone who is following this thread and is welcome to chime in).

**Comment by AndrewVSutherland** [comment]
I wanted to mention one thought I had about about highlighting particular objects that might help to address the potential concern @davidfarmer raised.  Aside from a desire to simplify and streamline the front page, part of the reason for removing the "hall of fame" is that, aside from inevitable disagreements about what to put there, we can't show more than one or two links/pictures, and whatever we do show will start to feel stale very quickly.

A way we could more democratically and more diversely highlight particular objects would be to use the space below the four boxes to show an automated list of "objects of the day" (a reel that would show one object at a time but cycle through maybe a dozen different objects in 5 second intervals).  The server would randomly pick one object (maybe one tagged as an interesting object) from each of various categories and show its portrait and maybe a few details from its properties box along with a link.  So each day you visit the LMFDB you would see a rotating cast of "elliptic curve of the day", "number field of the day", "modular form of the day", "L-function of the day", etc... and this might invite people to click on things they might not have otherwise clicked on (and it would make the front page less static).

Just a thought.

**Comment by jvoight** [comment]
If we'd like more uniformity in the icons, I can also grab ones for the database and learn more boxes.  I like the "object of the day", but I'm not sure that's the same thing as providing a welcoming on-ramp to newbies.

**Comment by AndrewVSutherland** [comment]
@jvoight I think it would be at least worth trying out some alternatives for the database and learnmore boxes that are in the same style.

My "object of the day" suggestion was aimed more at the goal of highlighting particular objects and drawing  both new and old visitors into the LMFDB by making the home page more interesting, not as an on-ramp (I don't think either the current "hall of fame" or "visualizing data" boxes do a good job of achieving that goal either).  I think adding a "getting started" link to the learnmore box that takes you to a completely separate page (as I think you suggested) would be better.

**Comment by JohnCremona** [comment]
I like the "Object of the day" suggestion.

John

**Comment by edgarcosta** [comment]
Overall I am not sold on the homepage as it is.
In particular, the grid structure.
It restricts what we can have there, and that doesn't seem to be helpful.
For example, `A database` and `Learn more` feel like they should be merged.
We are not going to change the format now, but I think it should be worth to think about it in the future.

Some minor observations:

#### A database
- I would expand
```quote
The LMFDB is a database of mathematical objects arising in number theory and arithmetic geometry.
```
to 
```quote
The LMFDB is a database of mathematical objects arising in number theory and arithmetic geometry, with the goal 
to illustrate the mathematical connections predicted by the Langlands program.
```
this makes the first sentence from `Learn more` obsolete.
- `source, reliability, and completeness` points to https://purple.lmfdb.xyz/about, which doesn't have much.
- `Click a heading on the left to browse` one perhaps should try to indicate that many of the headings on the left lead to interconnected databases.

#### Learn more
- The word `Knowls` should be a know explaining knowls.
- `Overview` pointing to https://purple.lmfdb.xyz/intro could also be in the list.
- `Knowledge` is a nice item, but a non LMFDB expert will be lost in that 


#### Citations and acknowledgments
-  `How to cite LMFDB` shouble be higher on that list.
-  I think we should rephrase the ambiguous `Open source code` to something like `Follow LMFDB's development on GitHub` or `Contribute to LMFDB on GitHub`.
Neither sound great, but `Open source code` is very unclear.

**Comment by AndrewVSutherland** [comment]
Thanks for the feedback @edgarcosta!  I just made some changes that attempt to address your comments (most of which I agree with except that I don't agree that "A database" and "Learn more" should be merged).

Regarding https://purple.lmfdb.xyz/about, the content of that page will change.  We are planning to add a completely new "meta-rcs page" that is meant to explain to mathematicians what is in the LMFDB, where that data came from, how much of it is and is not rigorous, and how they can figure out exactly how that information applies in their case of interest (e.g. how to answer questions like does the LMFDB prove there are no elliptic curves of conductor 13?  Does it prove there are no genus 2 curves of conductor 117? Does it include every imaginary quadratic field with class number 101?)  It would also explain 

I've temporarily changed it to point to https://purple.lmfdb.xyz/knowledge/show/rcs which should be viewed purely as a place holder for the moment (but it is a knowl so people can edit it and/or make comments).

On a related topic, I completely agree  with you that "How to cite the LMFDB" should be at the top of the list (that has been changed), and we also have plans to add a lot more to the "How to cite the LMFDB" section explaining when and how users should cite the papers linked to in the source and acknowledgments page, possibly including a table of all the citable papers in each section and instructions on when to cite them (e.g. if your paper has a proof that depends critically on knowing the exact adelic image of some elliptic curve over Q, you should not just be citing the LMFDB and/or the elliptic curve's home page, you should also cite https://arxiv.org/abs/2206.14959, because without that paper the data would not be there).

There are many situations where data in the LMFDB exists solely because someone figured out how to compute it and wrote a paper about it, and it is incumbent on us to encourage people to cite these papers (and it is in our self interest -- if the LMFDB generates citations to the papers that helped us to construct the database, people will write more papers like this, and if it does not, they won't).  I expect I am preaching to the choir, but I think it is worth all of us thinking about ways we can structure the interface (both on the front page and elsewhere) to encourage citations to papers we rely on.
