### ISSUE TITLE
Downloading one elliptic curve per isogeny class problem

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5091]
From the feedback page:

Selecting one curve per isogeny class and downloading the data to magma seems to download the data for all curves in the isogeny classes, not just the single curves displayed on the page.

**Comment by JohnCremona** [comment]
My debugging has reached the following conclusions so far. I noted that (when running in debug mode so that the query is shown at the bottom of the page), on http://localhost:37777/EllipticCurve/Q/?conductor=11&optimal=on&search_type=List the quesry is only {'conductor': 11}. The effect of "optimal=on" is to add query["one_per"] = "lmfdb_iso" to the query, but then the search wrapper removes this as it handles the condition of showing only one search result per value in a column (here the lmfdb_iso column identifies the isogeny class). So by the time the Download button is pressed, the query has changed.

So this is a bug in the implementation of the one_per mechanism -- which I see is not used anywhere else than EC/Q.

I note that for ECNF this is handled in a simpler way, namely instead of "optimal=on" we have "number=1" which means that only the first curve in each class is returned. This is not actually adequate (and that's why something more complicated was done for EC/Q), since it does not work properly when search fields specify something which is not an isogeny invariant. SO, while I quick fix would apparently be to use the same mechanism for EC/Q as we used to and we still do for ECNF, it woul be better to fix the one_per code, and then also use it for ECNF.

**Comment by roed314** [comment]
This was fixed in #5702.
