### ISSUE TITLE
Browse box problem

### ISSUE THREAD

**Issue by swisherh** [LMFDB/lmfdb#510]
When you put something inappropriate into a search box, instead of letting you know as in the elliptic curves page, it gives a server error.
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/ranges?level=r&weight=&character=0&Submit=Search
gives a TypeError: coercing to Unicode: need string or buffer, int found

**Comment by AurelPage** [comment]
In the refactor branch, this is not fixed, but it is now a ValueError: invalid literal for int() with base 10: 'r'.

**Comment by AurelPage** [comment]
This issue actually refers to the browse box (there is no search box yet).

**Comment by JohnCremona** [comment]
I can work on this since others are busy

**Comment by sanni85** [comment]
The new parsing functions have not been applied for classical modular forms yet. So these errors do still occur.

**Comment by fredstro** [comment]
If I knew how to apply the new parsing functions I would do that but they seem to be completely undocumented and I can't figure out how to use them or if they are even in a state that they could be used.
Since I didn't scroll down far enough to see John's comment that this shouldn't be fixed I went ahead and fixed it but I can just refrain from doing a pull request...

**Comment by AndrewVSutherland** [comment]
This is fixed as of PR #1465 (possibly earlier), closing.
