### ISSUE TITLE
Display inconsistency for elliptic curves

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5130]
If you search for elliptic curves (over Q or over number fields), the torsion subgroup (if it is not cyclic) is displayed in the search result list using \oplus.  If you click to see a curve, the Mordell-Weil group is displayed with \times to indicate product.

I think \times is used more in the lmfdb

**Comment by AndrewVSutherland** [comment]
They are of course both correct, but I would vote for \oplus as the "more correct" choice (they are Z-modules, not just abstract groups).

**Comment by jwj61** [comment]
So the same would hold for any group which is automatically abelian?  Class groups come to mind as an example.

**Comment by AndrewVSutherland** [comment]
Every abelian group can of course be given the structure of a Z-module, but the mordell-Weil group of an elliptic curve is naturally equipped with multiplication-by-n maps for every integer n in Z; this is in some sense more fundamental than, and independent of, the fact that it is an abelian group that happens to be finitely generated for elliptic curves over number fields.  Over the complex number the torsion subgroup of an elliptic curve is a Z-module, but it does not make sense to view it as as a product of finite cyclic groups; the direct sum and direct product are no longer the same in this setting, and it is the direct sum that corresponds to the torsion subgroup.

In the case of the class group of a number field there isn't a "multiplication-by-n" map that is as natural (and the group operation is usually written multiplicatively), and here I think it makes more sense to view them as products of cyclic groups.

**Comment by JohnCremona** [comment]
I am not entirely convinced. Why is multiplying a point by n more "natural" than raising an ideal class to power n?  Is it that there's an endomorphism *ring* (of the elliptic curve) around, which happens to be Z?

We have some curves with actual CM e.g. with endomorphism ring Z[i] over K=Q(i).  One might want to show the structure of E(K) or the torsion subgroup as an End(E)-module in such cases, perhaps.

**Comment by AndrewVSutherland** [comment]
I guess I am making two distinct arguments.  The first is that torsion subgroups really are direct sums, not direct products, as can be seen in the situation where they have infinite cardinality (as occurs for elliptic curves over C, for example), and the second is the point that you made, which is that they are naturally End(E)-modules (I agree that it would also be interesting to show the End(E)-structure of the torsion subgroups of CM elliptic curves E).

A third argument would be that \plus is used more frequently in the literature -- you can certainly find examples of both, but a quick search on MathSciNet for articles that contain the phrases "torsion subgroups" and "elliptic curves" finds that the five most cited papers all use \oplus.

So if you asked me to pick one (which I guess is what this issue is doing), I would say \oplus, but I'm happy to go with whatever the consensus is.   What do you think @jvoight ?

I see that the genus 2 curve pages use \times (probably because I cloned the E/Q pages), but the genus 2 search results use \oplus, so whatever decision we make, one of those needs to change as well.

**Comment by JohnCremona** [comment]
OK! I certainly have no objection to using oplus.

**Comment by jwj61** [comment]
I agree with JC that multiplication by n is natural for any abelian group.  I take AS's point on the torsion subgroup of elliptic curves over C.  The fact that it is an End(E)-module doesn't seem (to me) to be a strong argument since a curve with CM, it may be written as a direct sum, but may be a cyclic module.

The fact that class groups are naturally multiplicative would make \oplus a little weird there, but a similar mismatch might happen with elliptic curves.  What would you do with an elliptic curve with M-W group Z^2 x Z/2 x Z/2?  For a set A, A^2 is widely used to mean A x A.  If one wrote Z^2 \oplus Z/2 \oplus Z/2, then they would be mixing \oplus and (implicit) \times. If we do use \oplus, then I would change a case like this to Z \oplus Z \oplus Z/2 \oplus Z/2.  We don't have curves with very high rank.

By the way, I just noticed a third variation in the elliptic curve pages.  When searching for elliptic curves, there is a drop-down menu of torsion structures, and it lists C2 x C2.

**Comment by AndrewVSutherland** [comment]
I agree that we should not mix notation (one could write either Z \oplus Z \oplus or Z^{\oplus 2} rather than Z^2 if we decide on \oplus), and that we should make the drop-down menus match whatever we decide.  The pending PR #5137 addresses the drop-down menus, assuming we decide on \oplus, but we should settle this issue before merging or changing that PR.  I just emailed @jvoight to ask him to weigh-in with an opinion, since the three of us seem to be more or less tied (correct me if I am wrong, but it sounds like JJ has a slight preference for \times, I have a slight preference for \oplus, and JC is neutral), and I think we could all live with either choice.  But of course anyone else is also welcome to chime in!

**Comment by JohnCremona** [comment]
While I am fairly neutral, I don find it a bit extreme to disallow Z^2 as a shorthand for Z\oplus Z.

**Comment by jvoight** [comment]
Sorry I missed this thread--it slipped by two weeks ago.

Good, I think we're just making a single choice here for consistency within elliptic curves.  (I'm not sure we can make one choice for abelian groups across the LMFDB.)

Agreed that both notations are completely common, but we should just pick one.

For me: I use times when the group is written multiplicatively and oplus when it is written additively, at least when they're finitely generated and I have a choice.  (I always use times when dealing with rings.)  I use the symbol as a reminder of how the group law is written.  

For elliptic curves, we write P + Q and [n]*P, so I would write ZZ/n*ZZ oplus ZZ^2.  I don't mind pedantically writing ZZ^{oplus 2}, but it's adding a symbol that almost no one uses.  

Agree also with class groups being multiplicative: by contrast we write [aa]*[bb] and [aa]^n, so I'd write C_2 x C_34 and I'd think of the "nth power map" not the multiplication by n map.  FWIW, I've found this useful when thinking about class groups as Galois groups (where again you want functional composition, which is multiplicative notation).

Conversely, I don't think I would want to write FF_5^times oplus C_4.

**Comment by AndrewVSutherland** [comment]
Thanks @jvoight.  Just to confirm, this issue is about elliptic curves and genus 2 curves, its not meant to apply to all abelian groups in the LMFDB.  In particular, I think it's fine to have different conventions for groups that are written additively/multiplicatively, and I like your suggestion.

Regarding Z^2, what do you think of John Jones suggestion to just write Z \oplus Z (which won't be that cumbersome and consistent with the fact that we appear to always write Z/2Z \times Z/2Z or Z/2Z \plus Z/2Z and never (Z/2Z)^2, this is true even in genus 2 curves where there may by up to four Z/2Z's).  If fact we already do this with genus 2 curves (but I would change \times to \oplus if that is our decision).

**Comment by jwj61** [comment]
I would use \Z \oplus \Z for say rank <= 4.  When there are more, it is a chore to count them, but I think I would register the number of factors up to 4 of them.  When there is less and you use an exponent, it doesn't register as quickly.

**Comment by AndrewVSutherland** [comment]
Okay it sounds like we have a plan.  If/when we add Elkies' rank 28 curve I will be happy to write Z^28.  Let's cross the genus 3 full 2-torsion bridge when we come to it (I'm also happy to add a blanket disclaimer that we reserve the right to abuse notation whenever we think it is warranted and unlikely to cause confusion).  The convention will be to use \plus for Mordell-Weil groups (and more generally, I link JV's suggestion to use \oplus for abelian groups where the group operation is most naturally written additively and use \times when it is written multiplicatively -- I think the latter would apply to class groups of number fields, groups of Dirichlet characters, and abstract groups that happen to be abelian).
