### ISSUE TITLE
Maximal elliptic curve image

### ISSUE THREAD

**Issue by jvoight** [LMFDB/lmfdb#5226]
Hmm, the elliptic curve
  http://www.lmfdb.org/EllipticCurve/Q/441/c/4
says that it has maximal Galois image, but it has a 2-torsion point and a cyclic 7-isogeny.  

What am I missing?  It's a PCM curve, and "maximal" means these extra torsion structure?

**Comment by AndrewVSutherland** [comment]
See https://beta.lmfdb.org/knowledge/show/ec.maximal_elladic_galois_rep for the definition of maximal.  The data looks correct to me.

**Comment by jvoight** [comment]
The failure of maximality is in the adelic image, issue resolved.

**Comment by AndrewVSutherland** [comment]
That is possible, but it is ell-adically maximal for all ell (the rational 2-isogeny = rational 2-torsion point and the rational 7-isogeny are both forced by the endomorphism ring which is why it is called "maximal" (I know you know this JV, I'm just recording it for posterity).  For an example with a non-maximal ell-adic image, see the minimal quadratic twist: http://www.lmfdb.org/EllipticCurve/Q/49/a/4.

BTW, I have computed adelic image data for all E/Q in the LMFDB using [Zywina's algorithm](https://arxiv.org/abs/2206.14959) and hope to add this data before the modular curves workshop (Zywina's algorithm does not nail down the level, just the index and some reduction to finite level that determines the adelic image, there is still work to do to compute the level).  I don't yet have an easy way to compute this in the CM case (this is something I want to talk to Alvaro about).

**Comment by jvoight** [comment]
That's right, the page is correct.  But it's not displaying what I was looking for--proven by Alvaro Lozano-Robledo and Benjamin York.  Alvaro and I agree, this would be a good thing to work on at Modular Curves Week 2!
