### ISSUE TITLE
Base change for ECNF from other fields

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5279]
Currently we store whether an elliptic curve over a number field is a base change from Q.  It would be nice to also record whether it is a base change from intermediate subfields (only relevant, of course, if the base field has degree 4 or 6).  From a schema perspective, it probably makes sense to just add labels for curves over intermediate fields to the `base_change` column, but this will currently break our search UI, which uses that column to determine whether the curve is a base change from Q.  We could either change the search UI to filter based on whether it's a base change from any proper subfield, or we could add a boolean column storing whether it's a base change from Q.

Using Sage's [descend_to](https://git.sagemath.org/sage.git/tree/src/sage/schemes/elliptic_curves/ell_field.py#n608) function and [this script](https://github.com/roed314/ModularCurves/blob/main/upload/descends_ecnf.py), I've made a first pass at finding examples of base changes.  In the data file [here](https://math.mit.edu/~roed/ecnf_bc.txt), The format is
```
Elabel|Kpoly|ainvs|labels|missing
```
where `Elabel` is the label of an elliptic curve over a number field `L`, `Kpoly` is the polredabs reduced defining polynomial for a subfield `K` of `L`, `ainvs` is a list of 5-tuples giving a-invariants for descents of `L` to `K` (in terms of a generator `a` of `K` satisfying `Kpoly`), `labels` is a set of labels for curves over `K` that are isomorphic to one in the list of `ainvs`, and `missing` is either the string `"missing"` (if there are fewer labels then a-invariants) or the string `"found"` (if there are as many labels as there are a-invariants).

I hope that this data is complete, but it's possible that I messed up the identification process, which I think requires taking Galois conjugates of j-invariants to find the right label.

I have what I need to get back to building the modular curve tables, so I'll turn this over to @JohnCremona!

**Comment by JohnCremona** [comment]
OK, I am onto this.  I have added the necessary scripts to those in my repo ecnf-data and will be running them shortly on all the relevant degree 4 and 6 fields.

My plan is to change the meaning of the UI so that "base-change" means "base-change from any proper subfield".  The only website code change (other than documenting this) will be to construct the URL for the underlying curves differently when they are over Q (as at present) or over an intermediate field.

In cases where a curve over K is bc from L and there is more than curve over L which it descends to, I see from yout (@roed314 ) output that in about half the cases only one of the downstairs curves is in the database.  What I plan to do is keep the string "missing" in the list of labels in the table, but not mention the missing cases on the top curve's home page; but that can be adjusted later.  At a glance I get the impression that we have at least one of the downstairs curves in all cases, but I will verify that when I run my code.  If we have cases where all the downstairs curves are missing, more thought will be needed.

**Comment by JohnCremona** [comment]
For an example like   6.6.300125.1-729.1-a1  which is bc from Q surely we do not need to also record that it is bc from both the intermediate quadratic and cubic fields?

Assuming this, my code will only look for extra bc for curves which are not bc from Q, and when a curve is bc from Q that (the curve(s)/Q) is/are the curve which will be shown on the home page

**Comment by JohnCremona** [comment]
NB We already have cases of curves which are base change from Q but not all the curves over Q have labels, for example 2.0.163.1-361.1-a3 has base_change column ['504811.?.?', '19a3'] but in the display https://beta.lmfdb.org/EllipticCurve/2.0.163.1/361.1/a/3 the label containing '?' is ignored.  We never had to deal with a case where none of the base curves had a label, which we will now have to do, for example 6.6.820125.1-64.1-b1is base_change of 2.2.5.1-26244.1-?-?, meaning a  curve over 2.2.5.1 of conductor norm 26244 which is not in the database and has incomplete label. (The last component of the label would be easy to compute by computing the isogeny class and sorting it, but the '?' before that depends on sorting the isogeny classes with conductor 26244.1 and could only be done if we knew all the classes, which would require hard work -- for example, more HMF computations.)

There are 3519 curves which are relative base change (i.e. not just from Q) with at least one unknown label, though only 39 for which all the labels are unknown.

**Comment by JohnCremona** [comment]
My plan is this:
   1. Make a small code change and PR so that having complete or incomplete  ECNF labels in the base_change list will not raise an error, they will be ignored.
   2. Upload new entries for the base_change column for the 6272 curves which are relative base change (or just the 5717 which are not b.c. from Q).  Thanks to step 1 this will have no effect on web pages (but will confuse the result of searches when base-change curves are requested).
   3. Make additional code changes to display the new relative base changes.  I will try to deal with the '?' cases by displaying something like "an elliptic curve over Q with conductor ... not in the database" or "an elliptic curve over ... with conductor norm ... not in the database" in the Base Change section of home pages;  only base curves actually in the database will be displayed in the Related objects list.

**Comment by JohnCremona** [comment]
PR #5281 addresses step 1.  I'll only do the upload for step 2 when that has been merged and is no beta.

Previously I was in doubt as to whether to include the labels of base curves over intermediate fields for a curve which is b.c. from Q (for example, a curve over a biquadratic field which is b.c. from Q will have 4 base curves over Q and 2 each over the intermediate fields).  Now I am going to include them all.  If, later on, we decide to only show the base curves over the smallest possible field of definition, that can be handled without changing the data, by adding one line of code to delete any labels in the list which do not contain "-" in cases where at least one label does contain "-".  [If we ever have curves over (say) degree 8 fields with subfields of degree 2 and 4, so have longer inclusion chains of fields, this logic would have to be enhanced.]

**Comment by JohnCremona** [comment]
I now have a file ready for upload for step 2, and a branch ready for a second PR for Step 3, but will not mak ethe second PR yet.

**Comment by JohnCremona** [comment]
Thanks for merging the first PR. I have now uploaded the new data and will prepare the second PR.

**Comment by JohnCremona** [comment]
#5287 was merged, so I am closing this

**Comment by roed314** [comment]
Thank you for your work on this @JohnCremona!  I used it yesterday to create the new table of [modular curve points](https://red.lmfdb.xyz/api/modcurve_points_test/), and we're planning to have the [modular curve section](https://red.lmfdb.xyz/ModularCurve/Q/) expanded to higher level by next week when I'm giving a talk about it.
