### ISSUE TITLE
Random number field sometime ignores CM

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5346]
If you go to https://www.lmfdb.org/NumberField set CM to yes and click the random button, you will often get a field that is not a CM field.  Note that this can be tricky to reproduce, you may need to first to a random search without CM set, then set it and click random again.

Reproduced in firefox on windows and in chrome on linux

**Comment by edgarcosta** [comment]
I have not managed to recreate it:
do you observe it if you follow https://www.lmfdb.org/NumberField/?cm_field=yes&search_type=Random ?

**Comment by jwj61** [comment]
I saw it (brave on linux).  I had to do a regular random field first.

**Comment by edgarcosta** [comment]
https://user-images.githubusercontent.com/322822/221618507-a04466c7-9fab-4b2f-be1a-a43bdc58a6a9.mov

**Comment by AndrewVSutherland** [comment]
@edgarcosta I also was unable to reproduce the problem using the URL (which I tried before creating this issue), it only seems to happen when you click the random button.  I was also able to get into a state where the button did work consistently, then after doing a random search without CM selected then selecting CM again was able to get the problem to return.  This me think something strange is happening in the java script or browser cache.

**Comment by AndrewVSutherland** [comment]
I was able to reproduce the same problem in elliptic curves overs Q.  First do a random search with nothing selected, then select potential CM and click random.

**Comment by roed314** [comment]
@alexjbest diagnosed the problem I think, and it affects both search and random.  On any LMFDB page, if perform a search from the browse page, then click the "back" button, and add a condition to a search box that was not used in the first search, the new input is ignored.

Alex's hypothesis is that `cleanSubmit` deletes the input boxes in a way that the browser remembers, so that when you go back they're no longer there.

I'm going to experiment a bit with this today, and will report on what I find.
