### ISSUE TITLE
Incompatible data in curve torsion field degree

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#5457]
I look at http://www.lmfdb.org/EllipticCurve/Q/14450/b/1

At the end of the Galois representations block, the LMFDB currently states that the degree of the torsion field K = QQ(E[680]) is a degree `696320` Galois extension.

With the given magma code, we can recompute this from the generators of the representation and looking at the size of the subgroup. This leads to

```
 Gens := [[103, 34, 119, 579], [69, 306, 85, 579], [137, 0, 0, 273], [559, 5\
44, 544, 143], [1, 136, 0, 1], [545, 136, 544, 545], [81, 442, 17, 531], [1, 2\
2, 0, 1], [1, 0, 170, 1], [256, 425, 119, 1], [1, 170, 0, 1], [511, 510, 170, \
171]];
#sub<GL(2,Integers(680))|Gens>;
// 100270080
```

This prints `100270080`, which seems to be a factor of `144` off from the claimed degree `696320`.

There are other examples with similar inconsistencies, but it's nonuniform.

(This was observed while using the LMFDB to check work in the COUNT project proposed by Abbey Bourdon).

**Comment by AndrewVSutherland** [comment]
The data is correct, the inconsistency caused by a bug in the display code when it is computing #GL(2,Integers(N))/index to get the group order (without constructing the group).  The formula for the size of GL2 involves squaring, but the code was using "^2" to do this (which works in Sage but performs a bitwse xor in the flask/python LMFDB environment).

It might be useful to have a lint check that warns abou the  use of the "^" operator -- given the inconsistency between Sage and python on the semantics of this symbol I think it would be safer if we never used it (in particular, it makes it difficult to test code snippets in the sage).
