### ISSUE TITLE
Dirichlet call to gp takes too long

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5488]
Here is an example from the logs:

```
Exception on /Character/Dirichlet/51869/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 424, in render_Dirichletwebpage
    info = WebDBDirichletGroup(**args).to_dict()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 92, in to_dict
    d[k] = getattr(self,k,None)
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 795, in contents
    self._fill_contents()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 777, in _fill_contents
    self.add_row(c)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 870, in add_row
    prim, order, orbit_label, valuepairs = self.char_dbdata(mod, num)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 892, in char_dbdata
    gal_orbit = chi.galois_orbit
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/TinyConrey.py", line 204, in galois_orbit
    an_orbit = pari("znconreyexp(%s,charpow(%s,%s,%d))"%(self.G,self.G,self.chi_pari,k))
  File "cypari2/pari_instance.pyx", line 841, in cypari2.pari_instance.Pari.__call__
  File "cypari2/gen.pyx", line 4813, in cypari2.gen.objtogen
  File "cypari2/convert.pyx", line 557, in cypari2.convert.PyObject_AsGEN
RuntimeError: Aborted
[2023-06-04 07:22:56 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/51869/ ()
```

on beta, we manage to render it: https://beta.lmfdb.org/Character/Dirichlet/51869/

**Comment by BarinderBanwait** [comment]
This is happening because it's taking a long time to compute the galois orbit of each of the roughly 30 characters on that page.

Really what is needed is the minimal conrey conjugate. At the moment this is done by computing the entire Galois orbit (viewed as a list of conrey indices), sorting the list, and returning the first one. For `51869.2` this takes about 4 seconds, so adding it up across the 30 characters ends up taking a long time. The implementation is as follows:

```
def galois_orbit(self):
    order = self.order
    if order == 1:
        return [1]

    output = []

    for k in range(1,order):
        if gcd(k,order) == 1:
            an_orbit = pari("znconreyexp(%s,charpow(%s,%s,%d))"%(self.G,self.G,self.chi_pari,k))
            output.append(Integer(an_orbit))
    output.sort()
    return output
```

On the other hand, the code that @AndrewVSutherland gave on #4924 to do this, i.e.

```
intrinsic MinimalConreyConjugate(q::RngIntElt, n::RngIntElt) -> RngIntElt
{ The minimal Conrey index among all conjugates of q.n. }
    if n eq 1 then return 1; end if;
    R := Integers(q); U, pi := MultiplicativeGroup(R); x := Inverse(pi)(n);
    return i where i := Min([Integers()|pi(n*x):n in [1..m]|GCD(m,n) eq 1]) where m := Order(R!n);
end intrinsic;
```

takes 0.12 seconds. To me it looks like the two implementations are basically doing the same thing (sorting the list in the python takes no time at all), so not sure why the magma is much faster than the Sage+Pari/GP

**Comment by AndrewVSutherland** [comment]
There is no reason Sage+Pari should be taking 4 seconds, but even 0.12 seconds is too slow to do 32 times.

But I don't think we actually need this page.  I would suggest just redirecting to a search on the modulus https://www.lmfdb.org/Character/Dirichlet/?hst=List&modulus=51869&search_type=List, which is what the link after the first 32 does anyway.

**Comment by BarinderBanwait** [comment]
that sounds like a very major user-facing change: you're suggesting removing "Group of dirichlet characters of modulus X" pages, for all X? even nice pages like this: https://www.lmfdb.org/Character/Dirichlet/13 that present useful information on all characters of that modulus at a glance? I could potentially get behind this idea if we kept these pages for some modest range of X; but let me think for a bit about how the computation of galois orbits/minimal conrey conjugates could be made faster

**Comment by AndrewVSutherland** [comment]
We could do what I am suggesting only when above a certain level, or only when phi(modulus) is larger  than we want to put on one page (which could be more than 32).  I personally don't see a lot of value in listing the first 32 of 51868 conrey labels, especially when there are actually only 6 Galois orbits!  I'd rather see the Galois orbits.

But if one wanted to efficiently display this page as it is, rather than computing the minimal conjugate of 51869.n for n=1,32 a better approach would be to use a database lookup to figure out for which n in [1,32] are the minimal conjugates in their orbit, and for the remaining n figure out which of these is their minimal conjugate by grouping them by order (in this case that is already enough, in general you might need to do a discrete log computation but for moduli up to 1,000,000 that will be plenty fast).

**Comment by AndrewVSutherland** [comment]
I agree that https://www.lmfdb.org/Character/Dirichlet/13 is a nice page.  Maybe we could keep these for moduli up to 100  (and list all the characters, not just the first 32), and then switch to the search page.

**Comment by BarinderBanwait** [comment]
> I personally don't see a lot of value in listing the first 32 of 51868 conrey labels, especially when there are actually only 6 Galois orbits! I'd rather see the Galois orbits.

Yeah that's a fair point ...

> Maybe we could keep these for moduli up to 100 (and list all the characters, not just the first 32), and then switch to the search page.

Yep I'm happy with that

> a better approach would be to use a database lookup to figure out for which n in [1,32] are the minimal conjugates in their orbit, and for the remaining n figure out which of these is their minimal conjugate by grouping them by order 

Just to check I understand what's being suggested here: so in this case of modulus 51869, there are only six "minimal conjugates", viz. 1, 2, 4, 5, 22744, 51868. So the "remaining n" will be 3, 6, 7, 8, ..., 32. For these, we look at the order of the character, which must agree with the order of the orbit; so we take e.g. the order of 51869.3, which is 51868; in this case this immediately tells us that the orbit is 51869.f. But in general there might be several orbits of a given order; to decide between these we use a "discrete log computation", by which I think you mean basically what is happening in your magma code above.

Is that what you're suggesting here? I suppose given that we'll only be showing these for modulus up to 100, we won't be cutting off the "remaining n" at 32?

And actually, if we're not going to be cutting off the list of characters artificially, then we could just take the orbits in char_orbits, enumerate the characters in each one (by calling `galois_orbit` on the `first_label`), and reconstructing the table ordered by ascending conrey index?

**Comment by AndrewVSutherland** [comment]
Much faster via #5591 (still not lightning fast, but I think it's fast enough).
