### ISSUE TITLE
Stop the computation on the fly of L-functions of large coductor/degree

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5599]
Our servers are struggling today, as bots are going through lovely L-functions like `L/ArtinRepresentation/6.13639404879872.18t319.a.a/`
that are being computed on the fly.

I am unsure where the bots found the link, but we should stop enabling these computations.

**Comment by roed314** [comment]
I looked into this a bit, and wasn't sure exactly what we wanted to disable.  All Artin L-functions are computed on the fly, right?  So we want to raise an error for these L-functions, or find some minimal set of precomputations that we can do that makes it feasible for the pages to load?

**Comment by AndrewVSutherland** [comment]
The only L-functions we should be computing on the fly are those explicitly listed on https://www.lmfdb.org/L/Completeness.  We should display an error whenever someone or something tries to dynamically compute an L-function otherwise.

There is no L-function link on https://www.lmfdb.org/ArtinRepresentation/1.30269.2t1.a.a/, because we do not display L-function links on Artin pages when the conductor dimension product exceeds 729000000000000, see [this line](https://github.com/LMFDB/lmfdb/blob/d884641dc08c8494e118d0e63418b22829733c12/lmfdb/artin_representations/main.py#L390) in the Artin rep code.

The problem is that the bots are somehow finding links to the L-function anyway, so we may need to put a separate check into the L-function code rather than relying on the absence of links (which is annoying, because the bound really depends on the type of L-function, but maybe there is a generic bound on the analytic conductor that we could use as a simpler cutoff.

A better solution would be to permanently disable all dynamically computed L-functions and precompute the L-functions we actually want to show, which has been on our todo list for a long time now.  I could make an argument that we should just disable all dynamic L-function computations now, since this would put more pressure on us to do the precomputations we have been planning to do (for more than 5 years now).  Many of the dynamically computed L-functions with conductors below the cutoff we currently use still put a heavy load on the server (e.g. https://www.lmfdb.org/L/ArtinRepresentation/1.30269.2t1.a.a/)

I'd also like to know where/how bots are finding the link in the OP, we should not be displaying it anywhere.
