### ISSUE TITLE
Maybe wrong l-adic image for an elliptic curve

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#5692]
From the feedback page:

The CM curve 144.a3 has a rational 3-isogeny, but its 3-adic image is maximal. According to Table 19 in the paper on l-adic images by Rouse, Sutherland, and Zureick-Brown, this should have image 27.324.18.1, but such an image doesn't exist for any CM curve. Is there a mistake or am I reading things wrong?

https://www.lmfdb.org/EllipticCurve/Q/144/a/3

**Comment by AndrewVSutherland** [comment]
Both the LMFDB page for 144.a3 and Table 19 of the RSZB paper are correct, but let me explain why.

For elliptic curves over Q with CM by an imaginary quadratic order O the adelic Galosi representation is an open subgroup of the adelic group N_O defined on page 39 of https://arxiv.org/abs/2106.11141.  As in the non-CM case, this implies that its ell-adic image is an open subgroup of the projection of N_O to GL(2,Z_ell), hence of finite index (and unlike the non-CM case, we even have a bound on the index, see Proposition 12.1.3).

In the LMFDB, a CM elliptic curve has [maximal](https://www.lmfdb.org/knowledge/show/ec.maximal_elladic_galois_rep?timestamp=1632044318021678) ell-adic image if its image is equal to the projection N_O(3^infty) of N_O to GL_2(Z_ell).  In this case O=Z[zeta_3] and the elliptic curve 144.a3 has maximal 3-adic image N_O(3^infty) -- this is the generic 3-adic image one should expect for E/Q wth CM by Z[zeta_3] and applies to almost all of the twists of 144.a3.

It is true that 144.a3 admits a rational 3-isogeny, but then so does every curve with CM by Z[zeta_3].  For CM curves, maximal image does not preclude a rational isogenies.  Indeed, if you base change to the CM field there will be infinitely many (a pair for every ell = 1 mod 3).  In the ell-adic image table we only list cases where the image is not maximal, we don't list every ell for which an ell-isogeny exists. This is why, for example, the list for the base change  [2.0.3.1-2304.1-CMa1](https://www.lmfdb.org/EllipticCurve/2.0.3.1/2304.1/CMa/1) to Q(zeta_3) is finite rather than infinite.

As for Table 19, as explained in the paper, for each prime ell there is a minimal power ell^e such that the open subgroups of N_O that arise for elliptic curves over Q with CM by O all have distinct projections modulo ell^e.  For O=Z[zeta_3] and ell=3, one has ell^e=3^3=27, and Table 19 is identifying the subgroups of GL(2,Z/27Z) that arise as mod-27 images of E/Q with CM by Z[zeta_3].  Each subgroup should be interpreted as identifying an open subgroup of N_O that is the full inverse image of its projection to GL(2,Z/27Z).  As you can see in the table, the line labelled 27.324.18.1 is the largest (so it must be maximal), and in fact it identifies the mod-27 projection of N_O itself.
