### ISSUE TITLE
Search instrucitons for lattices

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#585]
http://beta.lmfdb.org/Lattice/

Search box lists options (E_8, Leech) which do not work.

**Comment by kedlaya** [comment]
In fact none of the given options 

3.4.16.1.1, D3, E8, Leech lattice

seems to work. The first one is a label that doesn't occur. In the case of E8, the lattice exists (8.1.1.1.1) but the name doesn't find it.

**Comment by kedlaya** [comment]
This is related (and trivial), so I'll add it rather than making a new issue: the explanations for the individual search boxes are not formatted consistently.

Dimension: e.g. 2, 3, 5 or a range of integers 1-5
Determinant: e.g. 1, 2, 3, or a range of integers 1-5
Level: e.g. 48, 336, 456 a range of integers 48-150

There is an inconsistency between whether or not the list example ends with a comma, and whether or not it is followed by the word "or".

**Comment by sanni85** [comment]
This is fixed in #1017 #1115
