### ISSUE TITLE
beta version of sidebar

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#615]
The sidebar now has links to the top level headings (such as "Varieties").

Those links are just placeholders, so they should not appear in the production version.

But the current method lets us either include an entry or not.  It does not let us make
it always there, but with or without a link.

**Comment by JohnCremona** [comment]
I just looked at all these and the Issue is almost resolved, since all these top-level headings now link to pages with actual content and further browsing links.

A few small things remain: 
   1. L-functions: http://www.lmfdb.org/L/ needs some expository text ("What is an L-function" for beginners).
   2.  Groups: http://www.lmfdb.org/Group mentions both Galois groups and lattices.  I would prefer Lattices not to be mentioned here as they are in a completely different category from Galois groups.  But anyway, since Lattices are only in beta it is (possibly) confusing to see here that the LMFDB contains lattice information.
   3. Knowledge:  http://www.lmfdb.org/knowledge/ should have a paragraph of introductory text.

**Comment by JohnCremona** [comment]
Also (perhaps a separate Issue?) the Data section of the sidebar should not be there at all, or certainly not in www.lmfdb.org.  I thought we had removed it put it's back...

**Comment by davidfarmer** [comment]
seems to be okay now
