### ISSUE TITLE
elliptic curves over number fields search

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#618]
Suppose I search for elliptic curves over number fields by conductor norm,
and put in the range 545-555.  The returned list first gives me all results
for the field 2.0.11.1, then for the field 2.0.3.1, then 2.0.7.1.

It would be good to discuss how such search results should be ordered.

I recall similar issues with Maass forms search by eigenvalue.

**Comment by JohnCremona** [comment]
The results are sorted by field label, then conductor norm, then 3 other
fields.  So the issues are (1) do we want to first sort by field? and (2)
do we want to sort field labels differently.   Mongo does not allow custom
sort functions so that would involve storing with every curve the field
degrr, disc. etc.

**Comment by JohnCremona** [comment]
I have a branch which refines the search: instead of the field label being sorted as a string it is first decomposed into a tuple [degree, #real embs, abs disc, index] and for a fixed field the sorting is as before.
This is a little different, but not a lot.  With the search suggested, the order of fields starts (with all quadratic)
2.0.11.1, 2.0.3.1, 2.0.7.1, 2.2.12.1, 2.2.13.1, 2.2.17.1, 2.2.21.1, ...
which seems to be exactly the same as it was before!

**Comment by AndrewVSutherland** [comment]
@JohnCremona Can we close this?

**Comment by JohnCremona** [comment]
Perhaps @davidfarmer should decide.  I don't know where the branch referred to is.

**Comment by davidfarmer** [comment]
In my original issue I said "It would be good to discuss how such search results should be ordered."

I still think it should be discussed.

My point was that (to a naive user) it seems odd to search on a range in a field
(In this case the conductor norm) and then not have the results sorted according to the
value of that field.

I added "feature request" as a label, meaning I am okay with leaving this alone for a while.

**Comment by AndrewVSutherland** [comment]
@davidfarmer Sorry I interpreted John's earlier response as addressing the issue.

As a contribution to the discussion I might add that I think it seems even more odd (even to users that are not so naive) that results for elliptic curves over Q are not included.

**Comment by davidfarmer** [comment]
It could be useful to explain the current ordering on the page where the results are returned,
but the more I think about it the more it makes sense to me to first order by conductor norm,
and then by the field.  Take an extreme case: show me all the elliptic curves in the database.
You will only ever see the curves over the first field listed.

I realize that when people search for curves they do that one field at a time, and so in
that situation it is natural to give the field highest priority.  But when you are searching
and don't specify the field?

From the L-function perspective, (conductor norm)(field discriminant)^2 is the natural
measure of the size.  But that can be left for the L-function search page to handle --
I don't think that perspective needs to be forced onto the EC people.

**Comment by AurelPage** [comment]
If the ordering is by conductor norm and you ask for all elliptic curves, don't you still obtain the extreme case where you only ever see curves with everywhere good reduction? (but maybe this extreme case will not be very visible in a finite database)

**Comment by JohnCremona** [comment]
@AurelPage that's already 497 curves (so far) hence the first 10 pages.  I think that if a used does a search which results in hundreds of matches we can hardly guess which 20 they want to see at the top of the list.  That's why we have a "further refine search" option.

@davidfarmer sorting the results according to which fields were in the query is going to be very complicated indeed.  This one case (if they enter anything in the conductor norm box then sort by conductor first) would of course be easy to implement.

@AndrewVSutherland I have been dreading the moment someone suggested that.  Either we would merge the two databases (a lot of work) and then curves over Q would dominate, or we would have to make two queries into the database for each search, and somehow combine the results.  On the ec/nf top page they can go to the ec/Q top page by clicking on Q in the browse section.  Compromise: At the top of the search section of /EllipticCurve add a clear statement that this search will only find curves not defined over Q, and perhaps add another link to /EllipticCurve/Q there.

**Comment by AndrewVSutherland** [comment]
Related to @AurelPage's point, it would be nice if there existed some ordering of all elliptic curves over number fields for which the displayed search results were a reasonable approximation to a finite prefix.  Ordering by conductor norm would suggest we have no business showing any curves with conductor norm greater than 1 until we have all the conductor norm 1 curves in the database :).

This would argue for instead ordering by height, which might not be so intuitive to the naive user nor relate directly to the L-function world, but is a much more sensible way to order arithmetic objects (heights were arguably invented for this purpose).

@JohnCremona I wasn't suggesting it would be easy to include the elliptic curves over Q, I was just following @davidfarmer's lead over what a naive (or not so naive) user might expect.  At a minimum I think it might be a good idea to make it clear on the ecnf results page that elliptic curves over Q are not included (and you have to admit it seems strange to exclude them, what if I want to see all the curves in the database with a 7-torsion point, say?).

**Comment by JohnCremona** [comment]
The more times I add very similar functionality to both ec and ecnf, finding it very tedious to have to duplicate work, the more I wonder about unifying the two.  It would be possible, though quite a lot of work and at the moment there are more important things.

**Comment by JohnCremona** [comment]
Right now, it is possible to choose which columns are displayed in the search results, and to sort by any of them.  Does that mean that this feature request can be closed?  @davidfarmer ?

**Comment by roed314** [comment]
I'm going to close this, since the original issue was addressed.  Feel free to reopen if there's something still to be done.
