### ISSUE TITLE
CMF newspace page times out on load

### ISSUE THREAD

**Issue by davidlowryduda** [LMFDB/lmfdb#6215]
I haven't looked into why, but the page https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/3312/1/c/ seems to time out.

**Comment by AndrewVSutherland** [comment]
This is very strange (similar newspace pages like https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/3315/1/b/ load without trouble), and this also happens on beta.

**Comment by AndrewVSutherland** [comment]
This is caused by trying to compute dimensions of weight 1 spaces on the fly when computing the decomposition of the oldspace, which is very slow.  PR #6218 fixes this by reverting to a database lookup in weight 1 (for weight > 1 we continue to avoid the database lookup by using dimension formulas, which is faster).
