### ISSUE TITLE
truncate powerseries

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#650]
Page not loading http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/9/8/1/a/
on refactor branch it raises a truncate_powerseries error

**Comment by sehlen** [comment]
The error was/is caused because the data in the db is invalid in this case. This is fixed in so far (in my refactor branch, I just issued a pull request) as that an error is raised when this happens and the page does not load anymore. Moreover, I check that q_expansion is not None before applying truncate_powerseries. But the data has to be fixed to resolve the original issue @fredstro.

**Comment by davidfarmer** [comment]
Fixed in Fredrik's refactor branch
