### ISSUE TITLE
Make pretty coefficients

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#654]
Use pari to find nicer coefficients

**Comment by JohnCremona** [comment]
Nicolas wrote a script which will be incorporated into the LMFDB code after consideration by Stephan and/or Fredrik.

**Comment by JohnCremona** [comment]
I am removing December from this one; it still has v1.0

**Comment by AndrewVSutherland** [comment]
Perhaps this issue should be merged with #1237

**Comment by sehlen** [comment]
I think these are two separate issues.
This one here is not so much about the display itself but about the data being converted, i.e. find a nicer basis for the number field so that the coefficients become simpler (as expressed in terms of that basis). The other issue #1237 is imho more about how to display the data that has been computed in cases where it just is to complicated to be human-readable.

I think @fredstro started using Nicolas Mascot's pari script already and tested it a bit but I don't know how much it helped and if it has been tested enough. But I know for sure that it does not always terminate and that we need a smart way of calling it with a timeout or we might need to improve the routine. It might in fact be better to improve the way sage computes the coefficients in the first place to not do work twice when computing the forms.

Btw, my impression is that the data magma produces is not better at all but I can take a look at it in a more systematic way at some point.

**Comment by AndrewVSutherland** [comment]
OK, lets keep them separate (and FWIW I don't think Magma is much better at this, if anything is likely to help it is probably Pari).  I am in the process of writing up a separate issue, which is how we identify the coefficient field, where we can easily do something much better than what we are are doing now (but this is a separate issue from choosing a basis that gives nice q-expansion coefficients).

**Comment by sehlen** [comment]
What do you mean with "identify the coefficient field"? Do you mean finding the lmfdb-label?
Because we do use a custom method using pari that's in the modforms-db repository at computation time and not the one that can be found in the lmfdb code. It builds on Nicolas Mascots pari code that can also be used to make pretty coefficients (if it terminates).

**Comment by AndrewVSutherland** [comment]
@sehlen, see #1386

**Comment by edgarcosta** [comment]
@davidfarmer I think we have achieved this (the last two are quite horrible):
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/95/2/b/b/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/161/2/a/d/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/420/2/bv/b/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/114/3/c/a/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/40/7/l/b/
* http://cmfs.lmfdb.xyz/ModularForm/GL2/Q/holomorphic/9/12/c/a/

**Comment by AndrewVSutherland** [comment]
Addressed by #2717.
