### ISSUE TITLE
Display reasonable error messages for non-existing characters

### ISSUE THREAD

**Issue by sehlen** [LMFDB/lmfdb#679]
See for instance /ModularForm/GL2/Q/holomorphic/12/2/3/a/

**Comment by fredstro** [comment]
I now give a reasonable error message in my refactor branch. 
I also try to handle requests for paths like: ModularForm/GL2/Q/holomorphic/x/x/x/x/
where the format of the parameters are wrong.

**Comment by JohnCremona** [comment]
Unfortunately although this was fixed a day or two ago it now gives server errors

  File "/home/jec/lmfdb/lmfdb/modular_forms/elliptic_modular_forms/backend/web_character.py", line 73, in __init__
    raise ValueError,"Character number {0} of modulus {1} does not exist!".format(number,modulus)

**Comment by JohnCremona** [comment]
As far as I can tell the code in the pull request which fixed this is no longer there.  Certainly, the new tests I included in test_emf.py are not!   I will investigate.  Perhaps some pull request got closed instead of merged...

**Comment by JohnCremona** [comment]
OK, I had this fixed in a sub-branch of refactor but never merged it;  I have now done so.

I fear that whatever Fredrik did in his own branch will conflict with this since I only fixed the specific issue with the error message for invalid character numbers, so 
ModularForm/GL2/Q/holomorphic/12/8/x/
gives a sensible error message, but
ModularForm/GL2/Q/holomorphic/12/x/x/
and
ModularForm/GL2/Q/holomorphic/x/8/x/
do not.  So I am going to close this and another issue could re opened for the general case, though I do not regard it as a priority to catch mal-formed manually entered URLs.
