### ISSUE TITLE
Browse to individual space: char=None

### ISSUE THREAD

**Issue by SallyKoutsoliotas** [LMFDB/lmfdb#727]
When on the main holomorphic modular forms page:  /ModularForm/GL2/Q/holomorphic/  When using the "Change the range covered by the table" to level range: 6 and weight range: 12, an error occurs, even though it exists.  Error:
"We are sorry. The sought space can not be found in the database.
Detailed information: Character number None of modulus 6 does not exist! "

page:  http://localhost:37777/ModularForm/GL2/Q/holomorphic/6/12/?group=0

**Comment by JohnCremona** [comment]
It works if you put 6-6 and 12-14, or 6-8 and 12-14, or 6-8 and 12-12: it then displays the appropriate smaller table.  But when the ranges reduce to a singleton it tries to show the page for a single space, but with character=None instead of =1, and this causes the error.

I am working on fixing this.

**Comment by JohnCremona** [comment]
It is ModularForm/GL2/Q/holomorphic/6/12/?group=0 which gives the wrong result, while ModularForm/GL2/Q/holomorphic/6/12/?group=1 is fine.  I can fix it so those entries in the form redirect to ModularForm/GL2/Q/holomorphic/6/12/1/?group=0 but that is not optimal, and I am now going to make ModularForm/GL2/Q/holomorphic/6/12/?group=0 work.

**Comment by JohnCremona** [comment]
Fixed by PR#19 in my refactor branch.
