### ISSUE TITLE
dimension not clickable even though there is data

### ISSUE THREAD

**Issue by AurelPage** [LMFDB/lmfdb#728]
On the home page for Gamma_1, the dimension for level 1 and weight 12 is not clickable even though there is data for this space. You can assign this to me.

**Comment by AurelPage** [comment]
Idem (5,10).

**Comment by AurelPage** [comment]
Idem /ModularForm/GL2/Q/holomorphic/10/9/?group=1

**Comment by fredstro** [comment]
The problem with weight 12, level 1 was due to incorrect computed checks in the dimension table. This is now fixed. 
The final two examples do not really give any example of a problem:
/ModularForm/GL2/Q/holomorphic/10/9/?group=1 -- this data is not in the database and not clickable
/ModularForm/GL2/Q/holomorphic/10/3/?group=1 -- is in the database and is clickable

This ticket can be closed.
