### ISSUE TITLE
Title of page for newforms for Gamma_0(N)

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#733]
The page showing all the newforms of fixed level and weight has title e.g. "Newforms of weight 8 for Gamma_0(14) with character chi_14(1,.)"

The "with character..." part should be removed.

**Comment by nmascot** [comment]
Actually, the phrase "modular for Gamma0 with character chi" (where chi is not trivial) has always puzzled me: such forms are by definition modular of level Gamma1 but **not** of level Gamma0; they just happen to transform under Gamma0 more nicely than a "random" form of level Gamma1.
If it were up to me, I would say "newform for Gamma1 with character chi", and reserve "for Gamma0" for forms with trivial character (i.e. actually invariant under Gamma0).
This confuses me to the point that if I saw "newform for Gamma0" without the "with character chi(1,.)" part, I would need a little time to understand what the page is actually about; after all it could be a page about forms with character for which "with character chi" has failed to display...
I do agree with John that "Newforms of weight 8 for Gamma_0(14) with character chi_14(1,.)" is ugly and that removing the character is the right thing to do, what I am saying is we should also replace Gamma0 with Gamma1 in the nontrivial character case.
I do realise that I'm going against well-established conventions though... what do you all think ?

**Comment by sehlen** [comment]
Hi,

I vote for sticking to "Gamma0(N) with character ..." for those forms
because the character is a character of the group Gamma0(N) and it is
trivial on Gamma1.
This is important because it distinguishes these space from the ones that
transform with a non-trivial character of Gamma1 (which do exist but are
not in the db at all).
(@Nicolas: Also note that the level is usually just an integer N and means
nothing else as that it is a form for Gamma(N), the principal congruence
subgroup. Maybe others have other conventions?)

However, I agree that the page showing all forms with all characters
shouldn't have a specific character in the title. However, I never saw it
anywhere and it's not the case on the current beta (it says Gamma1, which
is correct:
http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/11/6/?group=1). John's
change seems to remove the character from the title on the page of forms
with trivial character. But that change is also ok for me.

**Comment by JohnCremona** [comment]
I agree with Stephan.  The forms for Gamma_1 form a space which is a direct sum of subspaces, one for each character chi.  It is traditional to refer to the forms in ecah such subspace as forms "for Gamma_0(N) with character chi", meaning that they transform under Gamma_0(N) via a transformation which involves chi -- which as Stephan says is a character on Gamma_0(N) itself.
