### ISSUE TITLE
Possible: modular form labelled as cm is not cm

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#787]
This came in via the feedback page.  There was no e-mail address, so just fix it or mark it as invalid.

http://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/15/2/1/a/

is marked as CM.  The commenter says it is not CM, but is Steinberg at 3 and 5.

**Comment by sehlen** [comment]
Indeed, this is not a CM form.
I will look at it.

**Comment by fredstro** [comment]
We have now added a complete test for CM with checks up to the correct Sturm bound, i.e. 
the bound for Gamma_0( N^2) which is the maximum level we can end up at if we twist by a character of conductor dividing N.
This new code is now running and updating the existing data in the database.
Since in some cases we might not have sufficient coefficients  in the database to verify that something is CM I added a "third state" for the variable .is_cm which now takes values 0,1,-1 with 0 = definitely not CM, 1 = is CM and -1 = possibly CM but we were not able to check sufficiently many coefficients to be sure. I will submit a pull-request soon.
