### ISSUE TITLE
GL2 modular form search problem

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#818]
From the feedback script:

In the page corresponding to classical modular forms for GL(2):
http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/
A new table can be requested by specifying a range of levels and weights. If only only specifies the level or the weight and leaves the other textbox empty, the button 'make table', the error is not caught.

**Comment by fredstro** [comment]
I added default values so that when the table is shown with certain ranges then these ranges are also directly inserted in the form. 
If this is deemed inappropriate these default values can of course also be added in the background when submiting the form but I think this is a clean solution. 
I will submit a pull request.

**Comment by davidfarmer** [comment]
See pull request #819
