### ISSUE TITLE
More information about twists

### ISSUE THREAD

**Issue by davidfarmer** [LMFDB/lmfdb#91]
When an elliptic curve has a twist of smaller conductor, the LMFDB provides a link
to the minimal twist. But it would be more helpful if it said what the precise twist was.

Example page:

http://www.lmfdb.org/EllipticCurve/Q/275.b3

Perhaps similar information could be on the "all twists" page.

**Comment by JohnCremona** [comment]
For the minimal quadratic twist it would be easy to say what the twist was: the Sage function E.minimal_quadratic_twist() returns the discriminant as the second returned value, currently discarded.

But it would be harder to give the same information for all twists, since nothing is stored on the original curve's home page at all -- clicking the link just does a search for all curves with the same j-invariant, and once you do that search the original curve is forgotten, so the search results list cannot say what the twists are.

This could work though:  for any search which specifies one j-invariants (possibly with other search parameters), the search results page could give the twisting parameter for each curve with respect to the first one listed.  Is that worth it?

**Comment by JohnCremona** [comment]
There's now a pull request for the simple part of this.

**Comment by JohnCremona** [comment]
The main part of this issue was fixed by Pull Request #240.   I suggest closing this issue.  If deemed a good idea we could open a new one, for the additional suggestion which might now go like this:  In any elliptic curve search where a specific j-invariant is one of the search terms, so that all the curves are twists (and perhaps only when that j-invariant is not 0 or 1728 so it is only quadratic twists which arise), in the search results page there could be an extra column "twsit by" and on every line the appropriate discriminant would be shown, *relative to the minimal twist* for that j-invariant.   Thta would be possible.  It is not exactly what was suggested above, though, since one way of initiating such a search is to click on the "all twists" link on one elliptic curve's home page, and I am not proposing a solution to show the twisting discriminant relative to that base curve.
