### ISSUE TITLE
Labels as input and spaces

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#928]
If you enter as label input for an elliptic curve over a number field "2.2.5.1-31.1-a1          " you are redirect to the right page but the url is the following:

http://beta.lmfdb.org/EllipticCurve/?label=2.2.5.1-31.1-a1++++++++++&jump=label

**Comment by sanni85** [comment]
Same for number fields, for example typing "X^2+4          "

http://beta.lmfdb.org/NumberField/?natural=X^2%2B4++++++++++&search=Go

**Comment by sanni85** [comment]
Same for Galois groups

**Comment by JohnCremona** [comment]
This has been fixed for global number fields, but not for local fields or elliptic curves yet.

**Comment by JohnCremona** [comment]
The "fix" for number fields has a bad feature: if the box in http://www.lmfdb.org/NumberField/ is left empty and you click the button "Go" you get a server error, because in lines 381-382 of search_parsing.py it raises a ValueError!  If we raise errors in the website code, since they causes a server error which is completely unhelpful, they must be caught.  In this case in line 452 of number_field.py the error should have been caught, so this needs investigating.

For the specific issue here, I would have thought that just applying strip() to the string would do.  I will try this.

**Comment by sanni85** [comment]
it has been fixed for lattices 
I will check it once I am back from the workshop in Sarajevo, in a week time
